# Do not edit this file as it will be overwritten if HAMR codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

MSD ?= microkit.system

IMAGES := gen_gen.elf gen_gen_MON.elf splitter_splitter.elf splitter_splitter_MON.elf incx_incx.elf incx_incx_MON.elf clampx_clampx.elf clampx_clampx_MON.elf decy_decy.elf decy_decy_MON.elf merger_merger.elf merger_merger_MON.elf consume_consume.elf consume_consume_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_SysPropStructSplit_Data_Model_StructXY_1.o $(TOP_DIR)/build/sb_queue_int32_t_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_SysPropStructSplit_Data_Model_StructXY_1.o: $(TOP_DIR)/types/src/sb_queue_SysPropStructSplit_Data_Model_StructXY_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


$(TOP_DIR)/build/sb_queue_int32_t_1.o: $(TOP_DIR)/types/src/sb_queue_int32_t_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
gen_gen_MON.o: $(TOP_DIR)/components/gen_gen/src/gen_gen_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/gen_gen/include

# user code
gen_gen_rust:
	make -C ${CRATES_DIR}/gen_gen $(RUST_MAKE_TARGET)

gen_gen.o: $(TOP_DIR)/components/gen_gen/src/gen_gen.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/gen_gen/include

# monitor
splitter_splitter_MON.o: $(TOP_DIR)/components/splitter_splitter/src/splitter_splitter_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/splitter_splitter/include

# user code
splitter_splitter_rust:
	make -C ${CRATES_DIR}/splitter_splitter $(RUST_MAKE_TARGET)

splitter_splitter.o: $(TOP_DIR)/components/splitter_splitter/src/splitter_splitter.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/splitter_splitter/include

# monitor
incx_incx_MON.o: $(TOP_DIR)/components/incx_incx/src/incx_incx_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/incx_incx/include

# user code
incx_incx_rust:
	make -C ${CRATES_DIR}/incx_incx $(RUST_MAKE_TARGET)

incx_incx.o: $(TOP_DIR)/components/incx_incx/src/incx_incx.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/incx_incx/include

# monitor
clampx_clampx_MON.o: $(TOP_DIR)/components/clampx_clampx/src/clampx_clampx_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/clampx_clampx/include

# user code
clampx_clampx_rust:
	make -C ${CRATES_DIR}/clampx_clampx $(RUST_MAKE_TARGET)

clampx_clampx.o: $(TOP_DIR)/components/clampx_clampx/src/clampx_clampx.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/clampx_clampx/include

# monitor
decy_decy_MON.o: $(TOP_DIR)/components/decy_decy/src/decy_decy_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/decy_decy/include

# user code
decy_decy_rust:
	make -C ${CRATES_DIR}/decy_decy $(RUST_MAKE_TARGET)

decy_decy.o: $(TOP_DIR)/components/decy_decy/src/decy_decy.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/decy_decy/include

# monitor
merger_merger_MON.o: $(TOP_DIR)/components/merger_merger/src/merger_merger_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/merger_merger/include

# user code
merger_merger_rust:
	make -C ${CRATES_DIR}/merger_merger $(RUST_MAKE_TARGET)

merger_merger.o: $(TOP_DIR)/components/merger_merger/src/merger_merger.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/merger_merger/include

# monitor
consume_consume_MON.o: $(TOP_DIR)/components/consume_consume/src/consume_consume_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/consume_consume/include

# user code
consume_consume_rust:
	make -C ${CRATES_DIR}/consume_consume $(RUST_MAKE_TARGET)

consume_consume.o: $(TOP_DIR)/components/consume_consume/src/consume_consume.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/consume_consume/include

pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

gen_gen_MON.elf: gen_gen_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

gen_gen.elf: $(UTIL_OBJS) $(TYPE_OBJS) gen_gen_rust gen_gen.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/gen_gen/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lgen_gen -o $@

splitter_splitter_MON.elf: splitter_splitter_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

splitter_splitter.elf: $(UTIL_OBJS) $(TYPE_OBJS) splitter_splitter_rust splitter_splitter.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/splitter_splitter/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lsplitter_splitter -o $@

incx_incx_MON.elf: incx_incx_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

incx_incx.elf: $(UTIL_OBJS) $(TYPE_OBJS) incx_incx_rust incx_incx.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/incx_incx/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lincx_incx -o $@

clampx_clampx_MON.elf: clampx_clampx_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

clampx_clampx.elf: $(UTIL_OBJS) $(TYPE_OBJS) clampx_clampx_rust clampx_clampx.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/clampx_clampx/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lclampx_clampx -o $@

decy_decy_MON.elf: decy_decy_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

decy_decy.elf: $(UTIL_OBJS) $(TYPE_OBJS) decy_decy_rust decy_decy.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/decy_decy/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -ldecy_decy -o $@

merger_merger_MON.elf: merger_merger_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

merger_merger.elf: $(UTIL_OBJS) $(TYPE_OBJS) merger_merger_rust merger_merger.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/merger_merger/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lmerger_merger -o $@

consume_consume_MON.elf: consume_consume_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

consume_consume.elf: $(UTIL_OBJS) $(TYPE_OBJS) consume_consume_rust consume_consume.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/consume_consume/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lconsume_consume -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(TOP_DIR)/$(MSD)
	xmllint --xinclude $(TOP_DIR)/$(MSD) | awk 'FNR==1{print; print "<!--"; print "  DO NOT EDIT: This file is generated by merging"; print "    $(TOP_DIR)/$(MSD)"; print "  and its xi:included files."; print "  Modify the source files and run make instead."; print "-->"; next}1' > $(TOP_BUILD_DIR)/$(MSD).merged
	$(MICROKIT_TOOL) $(TOP_BUILD_DIR)/$(MSD).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu:
	$(QEMU) -machine virt,virtualization=on \
			-cpu cortex-a53 \
			-serial mon:stdio \
			-device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
			-m size=2G \
			-nographic

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/gen_gen test
	make -C ${CRATES_DIR}/splitter_splitter test
	make -C ${CRATES_DIR}/incx_incx test
	make -C ${CRATES_DIR}/clampx_clampx test
	make -C ${CRATES_DIR}/decy_decy test
	make -C ${CRATES_DIR}/merger_merger test
	make -C ${CRATES_DIR}/consume_consume test

clean:: 
	make -C ${CRATES_DIR}/gen_gen clean
	make -C ${CRATES_DIR}/splitter_splitter clean
	make -C ${CRATES_DIR}/incx_incx clean
	make -C ${CRATES_DIR}/clampx_clampx clean
	make -C ${CRATES_DIR}/decy_decy clean
	make -C ${CRATES_DIR}/merger_merger clean
	make -C ${CRATES_DIR}/consume_consume clean

verus: 
	make -C ${CRATES_DIR}/gen_gen verus
	make -C ${CRATES_DIR}/splitter_splitter verus
	make -C ${CRATES_DIR}/incx_incx verus
	make -C ${CRATES_DIR}/clampx_clampx verus
	make -C ${CRATES_DIR}/decy_decy verus
	make -C ${CRATES_DIR}/merger_merger verus
	make -C ${CRATES_DIR}/consume_consume verus

verus-sys-proof: 
	make -C ${CRATES_DIR}/sys_nominal_proof all
