// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn Isolette_Data_Model_On_Off_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::On_Off>
{
  Isolette_Data_Model_On_Off_strategy_cust(1, 1)
}

pub fn Isolette_Data_Model_On_Off_strategy_cust(
  Onn_bias: u32,
  Off_bias: u32) -> impl Strategy<Value = Isolette_Data_Model::On_Off>
{
  prop_oneof![
    Onn_bias => Just(Isolette_Data_Model::On_Off::Onn),
    Off_bias => Just(Isolette_Data_Model::On_Off::Off)
  ]
}

pub fn Isolette_Data_Model_Temp_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Temp>
{
  Isolette_Data_Model_Temp_strategy_cust(
    any::<i32>()
  )
}

pub fn Isolette_Data_Model_Temp_strategy_cust<degrees_i32_strategy: Strategy<Value = i32>> (degrees_strategy: degrees_i32_strategy) -> impl Strategy<Value = Isolette_Data_Model::Temp>
{
  (degrees_strategy).prop_map(|(degrees)| {
    Isolette_Data_Model::Temp { degrees }
  })
}

pub fn Isolette_Data_Model_Set_Points_strategy_default() -> impl Strategy<Value = Isolette_Data_Model::Set_Points>
{
  Isolette_Data_Model_Set_Points_strategy_cust(
    Isolette_Data_Model_Temp_strategy_default(),
    Isolette_Data_Model_Temp_strategy_default()
  )
}

pub fn Isolette_Data_Model_Set_Points_strategy_cust
  <lower_Isolette_Data_Model_Temp_strategy: Strategy<Value = Isolette_Data_Model::Temp>, 
   upper_Isolette_Data_Model_Temp_strategy: Strategy<Value = Isolette_Data_Model::Temp>> (
  lower_strategy: lower_Isolette_Data_Model_Temp_strategy,
  upper_strategy: upper_Isolette_Data_Model_Temp_strategy) -> impl Strategy<Value = Isolette_Data_Model::Set_Points>
{
  (lower_strategy, upper_strategy).prop_map(|(lower, upper)| {
    Isolette_Data_Model::Set_Points { lower, upper }
  })
}
