// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum On_Off {
    pub Onn = 0,
    pub Off = 1,
  }

  impl Default for On_Off {
    fn default() -> Self
    {
      On_Off::Onn
    }
  }
}