#include <stdint.h>
#include <microkit.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#define PORT_TO_GEN_GEN_MON 61
#define PORT_TO_SPLITTER_SPLITTER_MON 59
#define PORT_TO_INCX_INCX_MON 57
#define PORT_TO_CLAMPX_CLAMPX_MON 55
#define PORT_TO_DECY_DECY_MON 53
#define PORT_TO_MERGER_MERGER_MON 51
#define PORT_TO_CONSUME_CONSUME_MON 49

void init(void) {}

void notified(microkit_channel channel) {
  switch(channel) {
    case PORT_TO_GEN_GEN_MON:
      microkit_notify(PORT_TO_GEN_GEN_MON);
      break;
    case PORT_TO_SPLITTER_SPLITTER_MON:
      microkit_notify(PORT_TO_SPLITTER_SPLITTER_MON);
      break;
    case PORT_TO_INCX_INCX_MON:
      microkit_notify(PORT_TO_INCX_INCX_MON);
      break;
    case PORT_TO_CLAMPX_CLAMPX_MON:
      microkit_notify(PORT_TO_CLAMPX_CLAMPX_MON);
      break;
    case PORT_TO_DECY_DECY_MON:
      microkit_notify(PORT_TO_DECY_DECY_MON);
      break;
    case PORT_TO_MERGER_MERGER_MON:
      microkit_notify(PORT_TO_MERGER_MERGER_MON);
      break;
    case PORT_TO_CONSUME_CONSUME_MON:
      microkit_notify(PORT_TO_CONSUME_CONSUME_MON);
      break;
  }
}
