// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Assm: Integration constraint on operator_interface's incoming data port display_temp
  *
  * assume REQ_OP_5
  */
pub fn I_Assm_display_temp(display_temp: Isolette_Data_Model::Temp) -> bool
{
  (90i32 <= display_temp.degrees) &
    (display_temp.degrees <= 110i32)
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for operator_interface
  *
  * @param api_display_temp incoming data port
  */
pub fn compute_CEP_Pre(api_display_temp: Isolette_Data_Model::Temp) -> bool
{
  // I-Assm-Guard: Integration constraints for operator_interface's incoming ports
  let r0: bool = I_Assm_display_temp(api_display_temp);

  return r0;
}
