#![cfg_attr(not(test), no_std)]

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#![allow(dead_code)]
#![allow(static_mut_refs)]
#![allow(unused_imports)]
#![allow(unused_macros)]
#![allow(unused_parens)]
#![allow(unused_unsafe)]
#![allow(unused_variables)]

#![feature(proc_macro_hygiene)]
#![cfg_attr(not(verus_keep_ghost), feature(stmt_expr_attributes))]

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

mod bridge;
mod component;
mod logging;

#[cfg(test)]
mod test;

use crate::bridge::splitter_splitter_api::{self as api, *};
use crate::component::splitter_splitter_app::*;
use data::*;

static mut app: Option<splitter_splitter> = None;
static mut init_api: splitter_splitter_Application_Api<splitter_splitter_Initialization_Api> = api::init_api();
static mut compute_api: splitter_splitter_Application_Api<splitter_splitter_Compute_Api> = api::compute_api();

#[no_mangle]
pub extern "C" fn splitter_splitter_initialize() {
  logging::init_logging();

  unsafe {
    #[cfg(test)]
    crate::bridge::extern_c_api::initialize_test_globals();

    let mut _app = splitter_splitter::new();
    _app.initialize(&mut init_api);
    app = Some(_app);
  }
}

#[no_mangle]
pub extern "C" fn splitter_splitter_timeTriggered() {
  unsafe {
    if let Some(_app) = app.as_mut() {
      _app.timeTriggered(&mut compute_api);
    } else {
      panic!("Unexpected: app is None");
    }
  }
}

#[no_mangle]
pub extern "C" fn splitter_splitter_notify(channel: microkit_channel) {
  unsafe {
    if let Some(_app) = app.as_mut() {
      _app.notify(channel);
    } else {
      panic!("Unexpected: app is None");
    }
  }
}

// Need a Panic handler in a no_std environment
#[panic_handler]
#[cfg(not(test))]
fn panic(info: &core::panic::PanicInfo) -> ! {
  log::error!("PANIC: {info:#?}");
  loop {}
}
