// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Place-assertion spec functions of property `gen_range_sanity` -- one per
//! point its decoration binds (unbound points carry `true`, design D5).

#![allow(non_snake_case)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::assertions::*;
use crate::system_state::SystemState;

verus! {

/** property gen_range_sanity, bound 'after gen' (place after_gen)
  *   GenStruct integration guarantee
  */
pub open spec fn sys_assert_gen_range_sanity_after_gen(st: SystemState) -> bool
{
  inRange100(st.gen_out.x) && inRange100(st.gen_out.y)
}

} // verus!
