// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property gen_range_sanity -- Pre-Assert and Next-Assert VCs for every schema transition.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::gen_range_sanity::assertions::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[1]: Pre-Assert -- START |- GEN compute assumes */
pub proof fn vc_pre_assert_gen(st: SystemState)
  requires
    true /* START has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[2]: Next-Assert (task) -- START + frames + GEN postcondition + GEN's integration guarantees |- after_gen.
  * The integration guarantees hold by GEN's own contract proof (its component crate). */
pub proof fn vc_next_assert_task_gen(pre: SystemState, post: SystemState)
  requires
    true /* START has no assertion */,
    gen_local_write_frame(pre, post),
    gen_global_write_frame(pre, post),
    gen::integration_spec_outstruct_range_guarantee(post.gen_out),
  ensures
    sys_assert_gen_range_sanity_after_gen(post),
{}

/** VC[3]: Pre-Assert -- trivial: this property does not use SPLIT_STAGE's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_split_stage(st: SystemState)
  requires
    sys_assert_gen_range_sanity_after_gen(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[4]: Next-Assert (task) -- after_gen + frames + SPLIT_STAGE postcondition |- after_split_stage */
pub proof fn vc_next_assert_task_split_stage(pre: SystemState, post: SystemState)
  requires
    sys_assert_gen_range_sanity_after_gen(pre),
    split_stage_local_write_frame(pre, post),
    split_stage_global_write_frame(pre, post),
  ensures
    true /* after_split_stage has no assertion */,
{}

/** VC[5]: Pre-Assert -- trivial: this property does not use INCX's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_incx(st: SystemState)
  requires
    true /* before_incx has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[6]: Next-Assert (task) -- before_incx + frames + INCX postcondition |- after_incx */
pub proof fn vc_next_assert_task_incx(pre: SystemState, post: SystemState)
  requires
    true /* before_incx has no assertion */,
    incx_local_write_frame(pre, post),
    incx_global_write_frame(pre, post),
  ensures
    true /* after_incx has no assertion */,
{}

/** VC[7]: Pre-Assert -- trivial: this property does not use CLAMPX's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_clampx(st: SystemState)
  requires
    true /* after_incx has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[8]: Next-Assert (task) -- after_incx + frames + CLAMPX postcondition |- after_clampx */
pub proof fn vc_next_assert_task_clampx(pre: SystemState, post: SystemState)
  requires
    true /* after_incx has no assertion */,
    clampx_local_write_frame(pre, post),
    clampx_global_write_frame(pre, post),
  ensures
    true /* after_clampx has no assertion */,
{}

/** VC[9]: Pre-Assert -- trivial: this property does not use DECY's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_decy(st: SystemState)
  requires
    true /* before_decy has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[10]: Next-Assert (task) -- before_decy + frames + DECY postcondition |- after_decy */
pub proof fn vc_next_assert_task_decy(pre: SystemState, post: SystemState)
  requires
    true /* before_decy has no assertion */,
    decy_local_write_frame(pre, post),
    decy_global_write_frame(pre, post),
  ensures
    true /* after_decy has no assertion */,
{}

/** VC[11]: Next-Assert (control point) -- after_split_stage |- before_incx, before_decy (state unchanged) */
pub proof fn vc_next_assert_skip_t5(st: SystemState)
  requires
    true /* after_split_stage has no assertion */,
  ensures
    true /* before_incx has no assertion */,
    true /* before_decy has no assertion */,
{}

/** VC[12]: Next-Assert (control point) -- after_clampx, after_decy |- post_join_1 (state unchanged) */
pub proof fn vc_next_assert_skip_t6(st: SystemState)
  requires
    true /* after_clampx has no assertion */,
    true /* after_decy has no assertion */,
  ensures
    true /* post_join_1 has no assertion */,
{}

/** VC[13]: Pre-Assert -- trivial: this property does not use MERGE_STAGE's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_merge_stage(st: SystemState)
  requires
    true /* post_join_1 has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[14]: Next-Assert (task) -- post_join_1 + frames + MERGE_STAGE postcondition |- after_merge_stage */
pub proof fn vc_next_assert_task_merge_stage(pre: SystemState, post: SystemState)
  requires
    true /* post_join_1 has no assertion */,
    merge_stage_local_write_frame(pre, post),
    merge_stage_global_write_frame(pre, post),
  ensures
    true /* after_merge_stage has no assertion */,
{}

/** VC[15]: Pre-Assert -- trivial: this property does not use CONSUME's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_consume(st: SystemState)
  requires
    true /* after_merge_stage has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[16]: Next-Assert (task) -- after_merge_stage + frames + CONSUME postcondition |- after_consume */
pub proof fn vc_next_assert_task_consume(pre: SystemState, post: SystemState)
  requires
    true /* after_merge_stage has no assertion */,
    consume_local_write_frame(pre, post),
    consume_global_write_frame(pre, post),
  ensures
    true /* after_consume has no assertion */,
{}

/** VC[17]: Next-Assert (control point) -- after_consume |- END (state unchanged) */
pub proof fn vc_next_assert_skip_t9(st: SystemState)
  requires
    true /* after_consume has no assertion */,
  ensures
    true /* END has no assertion */,
{}

} // verus!
