#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool get_instruct(SysPropStructSplit_Data_Model_StructXY *data);
bool put_xfield(const int32_t *data);
bool put_yfield(const int32_t *data);
