// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property end_to_end_functional -- Init-State VC: the initial state (all initialize + integration guarantees) satisfies the START assertion.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::end_to_end_functional::assertions::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[0]: Init-State -- all initialize + integration guarantees |- START */
pub proof fn vc_init_state(st: SystemState)
  requires
    gen::initialize_init_outstruct(st.gen_out),
    gen::integration_spec_outstruct_range_guarantee(st.gen_out),
    split_stage::integration_spec_xfield_range_guarantee(st.x0),
    split_stage::integration_spec_yfield_range_guarantee(st.y0),
    consume::initialize_init_last_x(st.consume_last_x),
  ensures
    true /* START has no assertion */,
{}

} // verus!
