// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property end_to_end_functional -- Pre-Assert and Next-Assert VCs for every schema transition.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::end_to_end_functional::assertions::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[1]: Pre-Assert -- START |- GEN compute assumes */
pub proof fn vc_pre_assert_gen(st: SystemState)
  requires
    true /* START has no assertion */,
  ensures
    true /* no assertions at out-places */,
{}

/** VC[2]: Next-Assert (task) -- START + frames + GEN postcondition + GEN's integration guarantees |- after_gen.
  * The integration guarantees hold by GEN's own contract proof (its component crate). */
pub proof fn vc_next_assert_task_gen(pre: SystemState, post: SystemState)
  requires
    true /* START has no assertion */,
    gen_local_write_frame(pre, post),
    gen_global_write_frame(pre, post),
    gen::integration_spec_outstruct_range_guarantee(post.gen_out),
  ensures
    sys_assert_end_to_end_functional_after_gen(post),
{}

/** VC[3]: Pre-Assert -- after_gen |- SPLIT_STAGE compute assumes.
  * SPLIT_STAGE's integration assumes are not obligations here; they are discharged
  * per-connection in vc_integration.rs (upstream guarantee => assume). */
pub proof fn vc_pre_assert_split_stage(st: SystemState)
  requires
    sys_assert_end_to_end_functional_after_gen(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[4]: Next-Assert (task) -- after_gen + frames + SPLIT_STAGE postcondition + SPLIT_STAGE's integration guarantees + SPLIT_STAGE's integration assumes |- after_split_stage.
  * The integration guarantees hold by SPLIT_STAGE's own contract proof (its component crate); the integration assumes are discharged per-connection in vc_integration.rs (upstream guarantee => assume). */
pub proof fn vc_next_assert_task_split_stage(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_after_gen(pre),
    split_stage_local_write_frame(pre, post),
    split_stage_global_write_frame(pre, post),
    split_stage::compute_spec_split_x_guarantee(pre.gen_out, post.x0),
    split_stage::compute_spec_split_y_guarantee(pre.gen_out, post.y0),
    split_stage::integration_spec_instruct_range_assume(pre.gen_out),
    split_stage::integration_spec_xfield_range_guarantee(post.x0),
    split_stage::integration_spec_yfield_range_guarantee(post.y0),
  ensures
    sys_assert_end_to_end_functional_after_split_stage(post),
{}

/** VC[5]: Pre-Assert -- before_incx |- INCX compute assumes */
pub proof fn vc_pre_assert_incx(st: SystemState)
  requires
    sys_assert_end_to_end_functional_before_incx(st),
  ensures
    incx::compute_spec_inxfield_bounded_assume(st.x0),
{}

/** VC[6]: Next-Assert (task) -- before_incx + frames + INCX postcondition |- after_incx */
pub proof fn vc_next_assert_task_incx(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_incx(pre),
    incx_local_write_frame(pre, post),
    incx_global_write_frame(pre, post),
    incx::compute_spec_incx_guarantee(pre.x0, post.x1),
  ensures
    sys_assert_end_to_end_functional_after_incx(post),
{}

/** VC[7]: Pre-Assert -- after_incx |- CLAMPX compute assumes */
pub proof fn vc_pre_assert_clampx(st: SystemState)
  requires
    sys_assert_end_to_end_functional_after_incx(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[8]: Next-Assert (task) -- after_incx + frames + CLAMPX postcondition |- after_clampx */
pub proof fn vc_next_assert_task_clampx(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_after_incx(pre),
    clampx_local_write_frame(pre, post),
    clampx_global_write_frame(pre, post),
    clampx::compute_case_In_Range(pre.x1, post.x2),
    clampx::compute_case_Above(pre.x1, post.x2),
    clampx::compute_case_Below(pre.x1, post.x2),
  ensures
    sys_assert_end_to_end_functional_after_clampx(post),
{}

/** VC[9]: Pre-Assert -- before_decy |- DECY compute assumes */
pub proof fn vc_pre_assert_decy(st: SystemState)
  requires
    sys_assert_end_to_end_functional_before_decy(st),
  ensures
    decy::compute_spec_inyfield_bounded_assume(st.y0),
{}

/** VC[10]: Next-Assert (task) -- before_decy + frames + DECY postcondition |- after_decy */
pub proof fn vc_next_assert_task_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_decy(pre),
    decy_local_write_frame(pre, post),
    decy_global_write_frame(pre, post),
    decy::compute_spec_decy_guarantee(pre.y0, post.y1),
  ensures
    sys_assert_end_to_end_functional_after_decy(post),
{}

/** VC[11]: Next-Assert (control point) -- after_split_stage |- before_incx, before_decy (state unchanged) */
pub proof fn vc_next_assert_skip_t5(st: SystemState)
  requires
    sys_assert_end_to_end_functional_after_split_stage(st),
  ensures
    sys_assert_end_to_end_functional_before_incx(st),
    sys_assert_end_to_end_functional_before_decy(st),
{}

/** VC[12]: Next-Assert (control point) -- after_clampx, after_decy |- post_join_1 (state unchanged) */
pub proof fn vc_next_assert_skip_t6(st: SystemState)
  requires
    sys_assert_end_to_end_functional_after_clampx(st),
    sys_assert_end_to_end_functional_after_decy(st),
  ensures
    sys_assert_end_to_end_functional_post_join_1(st),
{}

/** VC[13]: Pre-Assert -- post_join_1 |- MERGE_STAGE compute assumes */
pub proof fn vc_pre_assert_merge_stage(st: SystemState)
  requires
    sys_assert_end_to_end_functional_post_join_1(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[14]: Next-Assert (task) -- post_join_1 + frames + MERGE_STAGE postcondition |- after_merge_stage */
pub proof fn vc_next_assert_task_merge_stage(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_post_join_1(pre),
    merge_stage_local_write_frame(pre, post),
    merge_stage_global_write_frame(pre, post),
    merge_stage::compute_spec_merge_x_guarantee(pre.x2, post.merged),
    merge_stage::compute_spec_merge_y_guarantee(pre.y1, post.merged),
  ensures
    sys_assert_end_to_end_functional_after_merge_stage(post),
{}

/** VC[15]: Pre-Assert -- trivial: this property does not use CONSUME's contract (no bound out-place; contract projection) */
pub proof fn vc_pre_assert_consume(st: SystemState)
  requires
    sys_assert_end_to_end_functional_after_merge_stage(st),
  ensures
    true /* no assertions at out-places */,
{}

/** VC[16]: Next-Assert (task) -- after_merge_stage + frames + CONSUME postcondition |- after_consume */
pub proof fn vc_next_assert_task_consume(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_after_merge_stage(pre),
    consume_local_write_frame(pre, post),
    consume_global_write_frame(pre, post),
  ensures
    true /* after_consume has no assertion */,
{}

/** VC[17]: Next-Assert (control point) -- after_consume |- END (state unchanged) */
pub proof fn vc_next_assert_skip_t9(st: SystemState)
  requires
    true /* after_consume has no assertion */,
  ensures
    true /* END has no assertion */,
{}

} // verus!
