// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait cons_cons_Api {}

  pub trait cons_cons_Put_Api: cons_cons_Api {
  }

  pub trait cons_cons_Get_Api: cons_cons_Api {
    #[verifier::external_body]
    fn unverified_get_input(
      &mut self,
      value: &Ghost<Option<ProdCons::Message>>) -> (res : Option<ProdCons::Message>)
      ensures
        res == value@,
        (res.is_none() ||
          // assume Payload_Range
          (0i32 <= res.unwrap().payload) &&
            (res.unwrap().payload <= 100i32)),
    {
      return extern_api::unsafe_get_input();
    }
  }

  pub trait cons_cons_Full_Api: cons_cons_Put_Api + cons_cons_Get_Api {}

  pub struct cons_cons_Application_Api<API: cons_cons_Api> {
    pub api: API,

    pub ghost input: Option<ProdCons::Message>
  }

  impl<API: cons_cons_Put_Api> cons_cons_Application_Api<API> {
  }

  impl<API: cons_cons_Get_Api> cons_cons_Application_Api<API> {
    pub fn get_input(&mut self) -> (res : Option<ProdCons::Message>)
      ensures
        old(self).input == self.input,
        res == self.input,
        (res.is_none() ||
          // assume Payload_Range
          (0i32 <= res.unwrap().payload) &&
            (res.unwrap().payload <= 100i32)),
    {
      self.api.unverified_get_input(&Ghost(self.input))
    }
  }

  pub struct cons_cons_Initialization_Api;
  impl cons_cons_Api for cons_cons_Initialization_Api {}
  impl cons_cons_Put_Api for cons_cons_Initialization_Api {}

  pub const fn init_api() -> cons_cons_Application_Api<cons_cons_Initialization_Api> {
    return cons_cons_Application_Api {
      api: cons_cons_Initialization_Api {},

      input: None
    }
  }

  pub struct cons_cons_Compute_Api;
  impl cons_cons_Api for cons_cons_Compute_Api {}
  impl cons_cons_Put_Api for cons_cons_Compute_Api {}
  impl cons_cons_Get_Api for cons_cons_Compute_Api {}
  impl cons_cons_Full_Api for cons_cons_Compute_Api {}

  pub const fn compute_api() -> cons_cons_Application_Api<cons_cons_Compute_Api> {
    return cons_cons_Application_Api {
      api: cons_cons_Compute_Api {},

      input: None
    }
  }
}