// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

pub fn Init_Payload_Sum() -> i32
{
  0i32
}

/** I-Assm: Integration constraint on cons's incoming event data port input
  *
  * assume Payload_Range
  */
pub fn I_Assm_input(input: ProdCons::Message) -> bool
{
  (0i32 <= input.payload) &
    (input.payload <= 100i32)
}

/** I-Assm: Integration constraint on cons's incoming event data port input
  *
  * assume Payload_Range
  */
pub fn I_Assm_Guard_input(input: Option<ProdCons::Message>) -> bool
{
  implies!(
    input.is_some(),
    I_Assm_input(input.unwrap())
  )
}

/** Initialize EntryPointContract
  *
  * guarantee initSum
  * @param payload_sum post-state state variable
  */
pub fn initialize_initSum(payload_sum: i32) -> bool
{
  payload_sum == Init_Payload_Sum()
}

/** IEP-Guar: Initialize Entrypoint for cons
  *
  * @param payload_sum post-state state variable
  */
pub fn initialize_IEP_Guar(payload_sum: i32) -> bool
{
  initialize_initSum(payload_sum)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param payload_sum post-state state variable
  */
pub fn initialize_IEP_Post(payload_sum: i32) -> bool
{
  initialize_IEP_Guar(payload_sum)
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for cons
  *
  * @param In_payload_sum pre-state state variable
  * @param api_input incoming event data port
  */
pub fn compute_CEP_Pre(
  In_payload_sum: i32,
  api_input: Option<ProdCons::Message>) -> bool
{
  // I-Assm-Guard: Integration constraints for cons's incoming ports
  let r0: bool = I_Assm_Guard_input(api_input);

  return r0;
}
