// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on temp_sensor's outgoing data port current_temp
  *
  * guarantee temp_range
  */
pub fn I_Guar_current_temp(current_temp: Isolette_Data_Model::Temp) -> bool
{
  (96i32 <= current_temp.degrees) &
    (current_temp.degrees <= 103i32)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_current_temp outgoing data port
  */
pub fn initialize_IEP_Post(api_current_temp: Isolette_Data_Model::Temp) -> bool
{
  // I-Guar-Guard: Integration constraints for temp_sensor's outgoing ports"
  I_Guar_current_temp(api_current_temp)
}

/** CEP-Post: Compute Entrypoint Post-Condition for temp_sensor
  *
  * @param api_current_temp outgoing data port
  */
pub fn compute_CEP_Post(api_current_temp: Isolette_Data_Model::Temp) -> bool
{
  // I-Guar-Guard: Integration constraints for temp_sensor's outgoing ports
  let r0: bool = I_Guar_current_temp(api_current_temp);

  return r0;
}
