// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait operator_interface_operator_interface_Api {}

  pub trait operator_interface_operator_interface_Put_Api: operator_interface_operator_interface_Api {
    #[verifier::external_body]
    fn unverified_put_desired_temp(
      &mut self,
      value: Isolette_Data_Model::Set_Points)
    {
      extern_api::unsafe_put_desired_temp(&value);
    }
  }

  pub trait operator_interface_operator_interface_Get_Api: operator_interface_operator_interface_Api {
    #[verifier::external_body]
    fn unverified_get_display_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp>) -> (res : Isolette_Data_Model::Temp)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_display_temp();
    }
  }

  pub trait operator_interface_operator_interface_Full_Api: operator_interface_operator_interface_Put_Api + operator_interface_operator_interface_Get_Api {}

  pub struct operator_interface_operator_interface_Application_Api<API: operator_interface_operator_interface_Api> {
    pub api: API,

    pub ghost display_temp: Isolette_Data_Model::Temp,
    pub ghost desired_temp: Isolette_Data_Model::Set_Points
  }

  impl<API: operator_interface_operator_interface_Put_Api> operator_interface_operator_interface_Application_Api<API> {
    pub fn put_desired_temp(
      &mut self,
      value: Isolette_Data_Model::Set_Points)
      ensures
        self.desired_temp == value,
        old(self).display_temp == self.display_temp,
    {
      self.api.unverified_put_desired_temp(value);
      self.desired_temp = value;
    }
  }

  impl<API: operator_interface_operator_interface_Get_Api> operator_interface_operator_interface_Application_Api<API> {
    pub fn get_display_temp(&mut self) -> (res : Isolette_Data_Model::Temp)
      ensures
        old(self).desired_temp == self.desired_temp,
        old(self).display_temp == self.display_temp,
        res == self.display_temp,
    {
      self.api.unverified_get_display_temp(&Ghost(self.display_temp))
    }
  }

  pub struct operator_interface_operator_interface_Initialization_Api;
  impl operator_interface_operator_interface_Api for operator_interface_operator_interface_Initialization_Api {}
  impl operator_interface_operator_interface_Put_Api for operator_interface_operator_interface_Initialization_Api {}

  pub const fn init_api() -> operator_interface_operator_interface_Application_Api<operator_interface_operator_interface_Initialization_Api> {
    return operator_interface_operator_interface_Application_Api {
      api: operator_interface_operator_interface_Initialization_Api {},

      display_temp: Isolette_Data_Model::Temp { degrees: 0 },
      desired_temp: Isolette_Data_Model::Set_Points { lower: Isolette_Data_Model::Temp { degrees: 0 }, upper: Isolette_Data_Model::Temp { degrees: 0 } }
    }
  }

  pub struct operator_interface_operator_interface_Compute_Api;
  impl operator_interface_operator_interface_Api for operator_interface_operator_interface_Compute_Api {}
  impl operator_interface_operator_interface_Put_Api for operator_interface_operator_interface_Compute_Api {}
  impl operator_interface_operator_interface_Get_Api for operator_interface_operator_interface_Compute_Api {}
  impl operator_interface_operator_interface_Full_Api for operator_interface_operator_interface_Compute_Api {}

  pub const fn compute_api() -> operator_interface_operator_interface_Application_Api<operator_interface_operator_interface_Compute_Api> {
    return operator_interface_operator_interface_Application_Api {
      api: operator_interface_operator_interface_Compute_Api {},

      display_temp: Isolette_Data_Model::Temp { degrees: 0 },
      desired_temp: Isolette_Data_Model::Set_Points { lower: Isolette_Data_Model::Temp { degrees: 0 }, upper: Isolette_Data_Model::Temp { degrees: 0 } }
    }
  }
}