// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

/// default proptest strategy for i32: any value of the type
pub fn i32_strategy_default() -> impl Strategy<Value = i32>
{
  any::<i32>()
}

/// custom proptest strategy for i32 restricted to an inclusive range
pub fn i32_strategy_cust(range: core::ops::RangeInclusive<i32>) -> impl Strategy<Value = i32>
{
  range
}

/// default proptest strategy for bool: any value of the type
pub fn bool_strategy_default() -> impl Strategy<Value = bool>
{
  any::<bool>()
}

pub fn SysPropStructSplit_Data_Model_StructXY_strategy_default() -> impl Strategy<Value = SysPropStructSplit_Data_Model::StructXY>
{
  SysPropStructSplit_Data_Model_StructXY_strategy_cust(
    any::<i32>(),
    any::<i32>()
  )
}

pub fn SysPropStructSplit_Data_Model_StructXY_strategy_cust
  <x_i32_strategy: Strategy<Value = i32>, 
   y_i32_strategy: Strategy<Value = i32>> (
  x_strategy: x_i32_strategy,
  y_strategy: y_i32_strategy) -> impl Strategy<Value = SysPropStructSplit_Data_Model::StructXY>
{
  (x_strategy, y_strategy).prop_map(|(x, y)| {
    SysPropStructSplit_Data_Model::StructXY { x, y }
  })
}
