// #Sireum

package ProdConsExample.Producer

import org.sireum._
import art._
import ProdConsExample._
import ProdConsExample.Producer.{ProducerThr_i_prod_producerThr => component}

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@datatype class ProducerThr_i_prod_producerThr_Bridge(
  val id: Art.BridgeId,
  val name: String,
  val dispatchProtocol: DispatchPropertyProtocol,
  val dispatchTriggers: Option[ISZ[Art.PortId]],

  outMessage: Port[ProdCons.Message_i]
  ) extends Bridge {

  val ports : Bridge.Ports = Bridge.Ports(
    dataIns = ISZ[art.UPort](),

    dataOuts = ISZ[art.UPort](),

    eventIns = ISZ[art.UPort](),

    eventOuts = ISZ[art.UPort](outMessage)
  )

  val initialization_api : ProducerThr_i_Initialization_Api = {
    val api = ProducerThr_i_Initialization_Api(
      id,
      outMessage.id
    )
    ProducerThr_i_prod_producerThr_Bridge.c_initialization_api = Some(api)
    api
  }

  val operational_api : ProducerThr_i_Operational_Api = {
    val api = ProducerThr_i_Operational_Api(
      id,
      outMessage.id
    )
    ProducerThr_i_prod_producerThr_Bridge.c_operational_api = Some(api)
    api
  }

  val entryPoints : Bridge.EntryPoints =
    ProducerThr_i_prod_producerThr_Bridge.EntryPoints(
      id,

      outMessage.id,

      dispatchTriggers,

      initialization_api,
      operational_api)
}

object ProducerThr_i_prod_producerThr_Bridge {

  var c_initialization_api: Option[ProducerThr_i_Initialization_Api] = None()
  var c_operational_api: Option[ProducerThr_i_Operational_Api] = None()

  @datatype class EntryPoints(
    ProducerThr_i_prod_producerThr_BridgeId : Art.BridgeId,
    outMessage_Id : Art.PortId,
    dispatchTriggers : Option[ISZ[Art.PortId]],
    initialization_api: ProducerThr_i_Initialization_Api,
    operational_api: ProducerThr_i_Operational_Api) extends Bridge.EntryPoints {

    val dataInPortIds: ISZ[Art.PortId] = IS()

    val eventInPortIds: ISZ[Art.PortId] = IS()

    val dataOutPortIds: ISZ[Art.PortId] = IS()

    val eventOutPortIds: ISZ[Art.PortId] = IS(outMessage_Id)

    def initialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: ProducerThr_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def compute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: ProducerThr_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.sendOutput(eventOutPortIds, dataOutPortIds)
    }

    def finalise(): Unit = {
      // implement the following method in 'component':  def finalise(api: ProducerThr_i_Operational_Api): Unit = {}
      component.finalise(operational_api)
    }

    override
    def testInitialise(): Unit = {
      // implement the following method in 'component':  def initialise(api: ProducerThr_i_Initialization_Api): Unit = {}
      component.initialise(initialization_api)
      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }

    override
    def testCompute(): Unit = {
      Art.receiveInput(eventInPortIds, dataInPortIds)

      // implement the following in 'component':  def timeTriggered(api: ProducerThr_i_Operational_Api): Unit = {}
      component.timeTriggered(operational_api)

      Art.releaseOutput(eventOutPortIds, dataOutPortIds)
    }
  }
}