// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * assumes inxfield_bounded
  *   Overflow guard only: the input lies in a
  *   conservative [-1000, 1000] envelope so the increment cannot overflow.
  * @param api_inxfield incoming data port
  */
pub fn compute_spec_inxfield_bounded_assume(api_inxfield: i32) -> bool
{
  (-1000i32 <= api_inxfield) &
    (api_inxfield <= 1000i32)
}

/** CEP-T-Assm: Top-level assume contracts for incx's compute entrypoint
  *
  * @param api_inxfield incoming data port
  */
pub fn compute_CEP_T_Assm(api_inxfield: i32) -> bool
{
  let r0: bool = compute_spec_inxfield_bounded_assume(api_inxfield);

  return r0;
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for incx
  *
  * @param api_inxfield incoming data port
  */
pub fn compute_CEP_Pre(api_inxfield: i32) -> bool
{
  // CEP-Assm: assume clauses of incx's compute entrypoint
  let r0: bool = compute_CEP_T_Assm(api_inxfield);

  return r0;
}

/** Compute Entrypoint Contract
  *
  * guarantee incx
  *   Output is the input incremented by one.
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_spec_incx_guarantee(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  api_outxfield == api_inxfield + 1i32
}

/** CEP-T-Guar: Top-level guarantee contracts for incx's compute entrypoint
  *
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_CEP_T_Guar(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  let r0: bool = compute_spec_incx_guarantee(api_inxfield, api_outxfield);

  return r0;
}

/** CEP-Post: Compute Entrypoint Post-Condition for incx
  *
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_CEP_Post(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  // CEP-Guar: guarantee clauses of incx's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_inxfield, api_outxfield);

  return r0;
}
