// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::heat_source_heat_source_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::heat_source_heat_source_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let heater_state = get_heater_state();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (heater_state) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_heat_control incoming event data port
  */
pub fn testComputeCB(api_heat_control: Option<Isolette_Data_Model::On_Off>) -> HarnessResult
{
  // Initialize the app
  crate::heat_source_heat_source_initialize();

  // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved
  //                from the component state
  let In_heater_state: Isolette_Data_Model::On_Off = get_heater_state();

  // [PutInPorts]: Set values on the input ports
  put_heat_control(api_heat_control);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::heat_source_heat_source_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let heater_state = get_heater_state();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_heater_state, heater_state, api_heat_control) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_heat_control)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_heat_control: $api_heat_control_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_heat_control)
            in ($api_heat_control_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_heat_control) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param In_heater_state pre-state state variable
  * @param api_heat_control incoming event data port
  */
pub fn testComputeCBwGSV(
  In_heater_state: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> HarnessResult
{
  // Initialize the app
  crate::heat_source_heat_source_initialize();

  // [PutInPorts]: Set values on the input ports
  put_heat_control(api_heat_control);

  // [SetInStateVars]: set the pre-state values of state variables
  put_heater_state(In_heater_state);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::heat_source_heat_source_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let heater_state = get_heater_state();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_heater_state, heater_state, api_heat_control) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCBwGSV_container(container: PreStateContainer_wGSV) -> HarnessResult
{
  return testComputeCBwGSV(container.In_heater_state, container.api_heat_control)
}

#[macro_export]
macro_rules!
testComputeCBwGSV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    In_heater_state: $In_heater_state_strat:expr,
    api_heat_control: $api_heat_control_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (In_heater_state, api_heat_control)
            in ($In_heater_state_strat, $api_heat_control_strat)
      ) {
        match $crate::test::util::cb_apis::testComputeCBwGSV(In_heater_state, api_heat_control) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
