// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_heat_control: Option<Isolette_Data_Model::On_Off>
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_heater_state: Isolette_Data_Model::On_Off,
  pub api_heat_control: Option<Isolette_Data_Model::On_Off>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_heat_control(container.api_heat_control);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_heater_state(container.In_heater_state);
  put_heat_control(container.api_heat_control);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(heat_control: Option<Isolette_Data_Model::On_Off>)
{
  put_heat_control(heat_control);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_heater_state: Isolette_Data_Model::On_Off,
  heat_control: Option<Isolette_Data_Model::On_Off>)
{
  put_heater_state(In_heater_state);
  put_heat_control(heat_control);
}

/// setter for IN EventDataPort
pub fn put_heat_control(value: Option<Isolette_Data_Model::On_Off>)
{
  *extern_api::IN_heat_control.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for GUMBO State Variable
pub fn get_heater_state() -> Isolette_Data_Model::On_Off
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.heater_state,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_heater_state(value: Isolette_Data_Model::On_Off)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.heater_state = value,
      None => panic!("The app is None")
    }
  }
}
