#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool get_current_temp(Isolette_Data_Model_Temp *data);
bool temp_changed_is_empty(void);
bool get_temp_changed_poll(sb_event_counter_t *numDropped, Isolette_Data_Model_Temp *data);
bool get_temp_changed(Isolette_Data_Model_Temp *data);
bool desired_temp_is_empty(void);
bool get_desired_temp_poll(sb_event_counter_t *numDropped, Isolette_Data_Model_Set_Points *data);
bool get_desired_temp(Isolette_Data_Model_Set_Points *data);
bool put_heat_control(const Isolette_Data_Model_On_Off *data);
