#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool get_inxfield(int32_t *data);
bool put_outxfield(const int32_t *data);
