// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property end_to_end_functional -- Non-Blocking and Preservation VCs for every
//! MHIP transition pair (per direction whose firing member is a component).
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::end_to_end_functional::assertions::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[19]: Non-Blocking -- INCX firing does not block DECY (MHIP pair t2/t4) */
pub proof fn vc_non_blocking_incx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_incx(pre),
    sys_assert_end_to_end_functional_before_decy(pre),
    incx_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_before_decy(post),
{}

/** VC[20]: Non-Blocking -- DECY firing does not block INCX (MHIP pair t2/t4) */
pub proof fn vc_non_blocking_decy_incx(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_incx(pre),
    sys_assert_end_to_end_functional_before_decy(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_before_incx(post),
{}

/** VC[21]: Preservation -- INCX firing preserves DECY's post-assertions (MHIP pair t2/t4) */
pub proof fn vc_preservation_incx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_incx(pre),
    sys_assert_end_to_end_functional_after_decy(pre),
    incx_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_after_decy(post),
{}

/** VC[22]: Preservation -- DECY firing preserves INCX's post-assertions (MHIP pair t2/t4) */
pub proof fn vc_preservation_decy_incx(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_decy(pre),
    sys_assert_end_to_end_functional_after_incx(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_after_incx(post),
{}

/** VC[23]: Non-Blocking -- CLAMPX firing does not block DECY (MHIP pair t3/t4) */
pub proof fn vc_non_blocking_clampx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_after_incx(pre),
    sys_assert_end_to_end_functional_before_decy(pre),
    clampx_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_before_decy(post),
{}

/** VC[24]: Non-Blocking -- DECY firing does not block CLAMPX (MHIP pair t3/t4) */
pub proof fn vc_non_blocking_decy_clampx(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_after_incx(pre),
    sys_assert_end_to_end_functional_before_decy(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_after_incx(post),
{}

/** VC[25]: Preservation -- CLAMPX firing preserves DECY's post-assertions (MHIP pair t3/t4) */
pub proof fn vc_preservation_clampx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_after_incx(pre),
    sys_assert_end_to_end_functional_after_decy(pre),
    clampx_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_after_decy(post),
{}

/** VC[26]: Preservation -- DECY firing preserves CLAMPX's post-assertions (MHIP pair t3/t4) */
pub proof fn vc_preservation_decy_clampx(pre: SystemState, post: SystemState)
  requires
    sys_assert_end_to_end_functional_before_decy(pre),
    sys_assert_end_to_end_functional_after_clampx(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_end_to_end_functional_after_clampx(post),
{}

} // verus!
