// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Initialize EntryPointContract
  *
  * guarantee REQ_THERM_1_HS
  *   The heater shall be Off initially.
  *   This preserves the system-level intent of REQ_THERM_1:
  *   event data ports need no initialization message, so
  *   the heat source itself guarantees the initial Off state.
  * @param heater_state post-state state variable
  */
pub fn initialize_REQ_THERM_1_HS(heater_state: Isolette_Data_Model::On_Off) -> bool
{
  heater_state == Isolette_Data_Model::On_Off::Off
}

/** IEP-Guar: Initialize Entrypoint for heat_source
  *
  * @param heater_state post-state state variable
  */
pub fn initialize_IEP_Guar(heater_state: Isolette_Data_Model::On_Off) -> bool
{
  initialize_REQ_THERM_1_HS(heater_state)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param heater_state post-state state variable
  */
pub fn initialize_IEP_Post(heater_state: Isolette_Data_Model::On_Off) -> bool
{
  initialize_IEP_Guar(heater_state)
}

/** Compute Entrypoint Contract
  *
  * guarantee HS_latch_cmd
  *   A received command is latched into the heater state.
  * @param heater_state post-state state variable
  * @param api_heat_control incoming event data port
  */
pub fn compute_spec_HS_latch_cmd_guarantee(
  heater_state: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  implies!(
    api_heat_control.is_some(),
    (heater_state == api_heat_control.unwrap()))
}

/** Compute Entrypoint Contract
  *
  * guarantee HS_hold_cmd
  *   If no command arrives, the heater state is unchanged.
  * @param In_heater_state pre-state state variable
  * @param heater_state post-state state variable
  * @param api_heat_control incoming event data port
  */
pub fn compute_spec_HS_hold_cmd_guarantee(
  In_heater_state: Isolette_Data_Model::On_Off,
  heater_state: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  implies!(
    !(api_heat_control.is_some()),
    (heater_state == In_heater_state))
}

/** CEP-T-Guar: Top-level guarantee contracts for heat_source's compute entrypoint
  *
  * @param In_heater_state pre-state state variable
  * @param heater_state post-state state variable
  * @param api_heat_control incoming event data port
  */
pub fn compute_CEP_T_Guar(
  In_heater_state: Isolette_Data_Model::On_Off,
  heater_state: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  let r0: bool = compute_spec_HS_latch_cmd_guarantee(heater_state, api_heat_control);
  let r1: bool = compute_spec_HS_hold_cmd_guarantee(In_heater_state, heater_state, api_heat_control);

  return r0 && r1;
}

/** CEP-Post: Compute Entrypoint Post-Condition for heat_source
  *
  * @param In_heater_state pre-state state variable
  * @param heater_state post-state state variable
  * @param api_heat_control incoming event data port
  */
pub fn compute_CEP_Post(
  In_heater_state: Isolette_Data_Model::On_Off,
  heater_state: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  // CEP-Guar: guarantee clauses of heat_source's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(In_heater_state, heater_state, api_heat_control);

  return r0;
}
