// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait heat_source_heat_source_Api {}

  pub trait heat_source_heat_source_Put_Api: heat_source_heat_source_Api {
  }

  pub trait heat_source_heat_source_Get_Api: heat_source_heat_source_Api {
    #[verifier::external_body]
    fn unverified_get_heat_control(
      &mut self,
      value: &Ghost<Isolette_Data_Model::On_Off>) -> (res : Isolette_Data_Model::On_Off)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_heat_control();
    }
  }

  pub trait heat_source_heat_source_Full_Api: heat_source_heat_source_Put_Api + heat_source_heat_source_Get_Api {}

  pub struct heat_source_heat_source_Application_Api<API: heat_source_heat_source_Api> {
    pub api: API,

    pub ghost heat_control: Isolette_Data_Model::On_Off
  }

  impl<API: heat_source_heat_source_Put_Api> heat_source_heat_source_Application_Api<API> {
  }

  impl<API: heat_source_heat_source_Get_Api> heat_source_heat_source_Application_Api<API> {
    pub fn get_heat_control(&mut self) -> (res : Isolette_Data_Model::On_Off)
      ensures
        old(self).heat_control == self.heat_control,
        res == self.heat_control,
    {
      self.api.unverified_get_heat_control(&Ghost(self.heat_control))
    }
  }

  pub struct heat_source_heat_source_Initialization_Api;
  impl heat_source_heat_source_Api for heat_source_heat_source_Initialization_Api {}
  impl heat_source_heat_source_Put_Api for heat_source_heat_source_Initialization_Api {}

  pub const fn init_api() -> heat_source_heat_source_Application_Api<heat_source_heat_source_Initialization_Api> {
    return heat_source_heat_source_Application_Api {
      api: heat_source_heat_source_Initialization_Api {},

      heat_control: Isolette_Data_Model::On_Off::Onn
    }
  }

  pub struct heat_source_heat_source_Compute_Api;
  impl heat_source_heat_source_Api for heat_source_heat_source_Compute_Api {}
  impl heat_source_heat_source_Put_Api for heat_source_heat_source_Compute_Api {}
  impl heat_source_heat_source_Get_Api for heat_source_heat_source_Compute_Api {}
  impl heat_source_heat_source_Full_Api for heat_source_heat_source_Compute_Api {}

  pub const fn compute_api() -> heat_source_heat_source_Application_Api<heat_source_heat_source_Compute_Api> {
    return heat_source_heat_source_Application_Api {
      api: heat_source_heat_source_Compute_Api {},

      heat_control: Isolette_Data_Model::On_Off::Onn
    }
  }
}