// This file will not be overwritten if codegen is rerun

//============================================================================
//  T e m p   S e n s o r  -- Thread Component
//
//  This Thread component implements a (simulated) air temperature sensor.
//  The "sensed" value is placed on the component's output data port.
//
//  There is no software application level input.  The component encapsulates
//  a hardware driver that fetches information from a simulated hardware 
//  interface.  The simulation produces temperature values within a range
//  specified by constants declared in this file.
//
//  The behavior of the temperature simulation is as follows:
//    - the latest value of the simulated sensed temperature is stored in the 
//      component state (HAMR-generated struct for the component)
//    - on each activation of the Compute Entry Point (timeTriggered method), 
//      a new simulated temperature value is generated by incrementing or 
//      decrementing the latest temperature value
//    - a component state variable indicates the simulation temperature
//      trajectory (trending up (+1 value), or trending down (-1 value)
//    - if the simulated temperature reaches a declared upper or lower bound,
//      the trajectory is reversed.  This ensures the simulated temperature
//      value stays within a declared range.
//============================================================================

use data::*;
use data::Isolette_Data_Model::*;  // Add for easy access to data type names
use crate::bridge::temp_sensor_temp_sensor_api::*;
use vstd::prelude::*;

verus! {

  //-------------------------------------------
  //  Constants
  //-------------------------------------------

  // --- temp bounds ---
  //  ..Upper and lowers bounds for sensed temperature
  //  We will see later that this can also be accomplished using model-level GUMBO constants
  pub const sensed_temp_lower_bound: i32 = 96;
  pub const sensed_temp_upper_bound: i32 = 103;

  // constants declared to support temp simulation (not publicly visible)
  const temp_trajectory_up: i32 = 1;
  const temp_trajectory_down: i32 = -1;

  //-------------------------------------------
  //  Application State (as a struct)
  //-------------------------------------------
  
  pub struct temp_sensor_temp_sensor {
    // PLACEHOLDER MARKER STATE VARS

    //  ..Note: if GUMBO state variable declarations are declared,
    //   HAMR uses the marker above to weave autogenerated variable 
    //   declarations into the code at the point of the marker.
    //   We recommend not deleting the marker.
    
    // Two variables below are used for sensor simulation.
    // This also illustrates non-GUMBO declared state variable for a component
    pub latest_temp: i32, 
    pub temp_trajectory: i32,
  }

 
  impl temp_sensor_temp_sensor {
    //-------------------------------------------
    //  Application Component Constructor
    //-------------------------------------------
    pub fn new() -> Self
    {
      Self {
        // PLACEHOLDER MARKER STATE VAR INIT

         // initialization of non-GUMBO declared state variable
        latest_temp: sensed_temp_lower_bound, 
        temp_trajectory: temp_trajectory_up, // value will either be +1 or -1
      }
    }

    //-------------------------------------------
    //  Initialize Entry Point
    //-------------------------------------------
    pub fn initialize<API: temp_sensor_temp_sensor_Put_Api> (
      &mut self,
      api: &mut temp_sensor_temp_sensor_Application_Api<API>)
      ensures
        // PLACEHOLDER MARKER INITIALIZATION ENSURES
    {
      log_info("initialize entrypoint invoked");

      self.latest_temp = sensed_temp_lower_bound; 
      //  ...set the temperature trajectory to be increaing
      self.temp_trajectory = temp_trajectory_up;

      // put the "sensed value" on the current_temp output port
      api.put_current_temp(Temp { degrees: self.latest_temp });
    }

    //-------------------------------------------
    //  Compute Entry Point
    //-------------------------------------------
    pub fn timeTriggered<API: temp_sensor_temp_sensor_Full_Api> (
      &mut self,
      api: &mut temp_sensor_temp_sensor_Application_Api<API>)
      requires
        // PLACEHOLDER MARKER TIME TRIGGERED REQUIRES
      ensures
        // PLACEHOLDER MARKER TIME TRIGGERED ENSURES
    {
      log_info("compute entrypoint invoked");

      // ((mock read of temperature sensor))
      //   ..update simulation according to trajectory
      self.latest_temp = self.latest_temp + self.temp_trajectory;

      //   ..update the simulation trajectory when temp reaches bounds
      if self.latest_temp == sensed_temp_upper_bound {
        self.temp_trajectory = temp_trajectory_down
      } else if self.latest_temp == sensed_temp_lower_bound {
        self.temp_trajectory = temp_trajectory_up
      };
      // log state of temperature simulation
      log_temp_simulation(&self);

      // put the "sensed" value on current_temp output port
      api.put_current_temp(Temp { degrees: self.latest_temp });
    }

    //-------------------------------------------
    //  seL4 / Microkit Error Handling
    //-------------------------------------------
    pub fn notify(
      &mut self,
      channel: microkit_channel)
    {
      // this method is called when the monitor does not handle the passed in channel
      match channel {
        _ => {
          log_warn_channel(channel)
        }
      }
    }
  }

  //-------------------------------------------
  //  Logging Helper Functions
  //-------------------------------------------
  #[verifier::external_body]
  pub fn log_temp_simulation(state: &temp_sensor_temp_sensor)
  {
     log::info!("Sensed Temp: {}", state.latest_temp);
     log::info!("Simulated Temp Trajectory: {}", state.temp_trajectory);
  }

  #[verifier::external_body]
  pub fn log_info(msg: &str)
  {
    log::info!("{0}", msg);
  }

  #[verifier::external_body]
  pub fn log_warn_channel(channel: u32)
  {
    log::warn!("Unexpected channel: {0}", channel);
  }

  // PLACEHOLDER MARKER GUMBO METHODS

}
