// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

pub fn Temp_Lower_Bound() -> i32
{
  95i32
}

pub fn Temp_Upper_Bound() -> i32
{
  104i32
}

pub fn Default_Lower_Set_Point() -> i32
{
  98i32
}

pub fn Default_Upper_Set_Point() -> i32
{
  101i32
}

/** I-Assm: Integration constraint on thermostat's incoming data port current_temp
  *
  * assume ASSM_CT_Range
  */
pub fn I_Assm_current_temp(current_temp: Isolette_Data_Model::Temp) -> bool
{
  (Temp_Lower_Bound() <= current_temp.degrees) &
    (current_temp.degrees <= Temp_Upper_Bound())
}

/** I-Assm: Integration constraint on thermostat's incoming event data port desired_temp
  *
  * assume ASSM_LDT_LE_UDT
  *   Incoming set point messages must be well-formed
  *   (lower desired temp at most upper desired temp).
  */
pub fn I_Assm_desired_temp(desired_temp: Isolette_Data_Model::Set_Points) -> bool
{
  desired_temp.lower.degrees <= desired_temp.upper.degrees
}

/** I-Assm: Integration constraint on thermostat's incoming event data port desired_temp
  *
  * assume ASSM_LDT_LE_UDT
  *   Incoming set point messages must be well-formed
  *   (lower desired temp at most upper desired temp).
  */
pub fn I_Assm_Guard_desired_temp(desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  implies!(
    desired_temp.is_some(),
    I_Assm_desired_temp(desired_temp.unwrap())
  )
}

/** Initialize EntryPointContract
  *
  * guarantee initCurrentSetPoints
  *   The latched set points start at the default range.
  * @param currentSetPoints post-state state variable
  */
pub fn initialize_initCurrentSetPoints(currentSetPoints: Isolette_Data_Model::Set_Points) -> bool
{
  (currentSetPoints.lower.degrees == Default_Lower_Set_Point()) &
    (currentSetPoints.upper.degrees == Default_Upper_Set_Point())
}

/** Initialize EntryPointContract
  *
  * guarantee REQ_THERM_1
  *   The commanded heat state shall be Off initially.
  *   Adapted from the original REQ_THERM_1: no message is
  *   sent during initialization (event data ports need no
  *   initialization), and the Heat Source independently
  *   initializes its heater state to Off.
  * @param lastCmd post-state state variable
  */
pub fn initialize_REQ_THERM_1(lastCmd: Isolette_Data_Model::On_Off) -> bool
{
  lastCmd == Isolette_Data_Model::On_Off::Off
}

/** IEP-Guar: Initialize Entrypoint for thermostat
  *
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing event data port
  */
pub fn initialize_IEP_Guar(
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  initialize_initCurrentSetPoints(currentSetPoints) &&
  initialize_REQ_THERM_1(lastCmd)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing event data port
  */
pub fn initialize_IEP_Post(
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  initialize_IEP_Guar(currentSetPoints, lastCmd, api_heat_control)
}

/** Compute Entrypoint Contract
  *
  * assumes INV_CSP
  *   The latched set points are well-formed.
  * @param In_currentSetPoints pre-state state variable
  */
pub fn compute_spec_INV_CSP_assume(In_currentSetPoints: Isolette_Data_Model::Set_Points) -> bool
{
  In_currentSetPoints.lower.degrees <= In_currentSetPoints.upper.degrees
}

/** CEP-T-Assm: Top-level assume contracts for thermostat's compute entrypoint
  *
  * @param In_currentSetPoints pre-state state variable
  */
pub fn compute_CEP_T_Assm(In_currentSetPoints: Isolette_Data_Model::Set_Points) -> bool
{
  let r0: bool = compute_spec_INV_CSP_assume(In_currentSetPoints);

  return r0;
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for thermostat
  *
  * @param In_currentSetPoints pre-state state variable
  * @param In_lastCmd pre-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  * @param api_current_temp incoming data port
  */
pub fn compute_CEP_Pre(
  In_currentSetPoints: Isolette_Data_Model::Set_Points,
  In_lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_current_temp: Isolette_Data_Model::Temp) -> bool
{
  // I-Assm-Guard: Integration constraints for thermostat's incoming ports
  let r0: bool = I_Assm_current_temp(api_current_temp);
  let r1: bool = I_Assm_Guard_desired_temp(api_desired_temp);

  // CEP-Assm: assume clauses of thermostat's compute entrypoint
  let r2: bool = compute_CEP_T_Assm(In_currentSetPoints);

  return r0 && r1 && r2;
}

/** Compute Entrypoint Contract
  *
  * guarantee latchSetPointsOnEvent
  *   A newly received set point message is latched.
  * @param currentSetPoints post-state state variable
  * @param api_desired_temp incoming event data port
  */
pub fn compute_spec_latchSetPointsOnEvent_guarantee(
  currentSetPoints: Isolette_Data_Model::Set_Points,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  implies!(
    api_desired_temp.is_some(),
    (currentSetPoints.lower.degrees == api_desired_temp.unwrap().lower.degrees) &&
      (currentSetPoints.upper.degrees == api_desired_temp.unwrap().upper.degrees))
}

/** Compute Entrypoint Contract
  *
  * guarantee latchSetPointsNoEvent
  *   Otherwise the latched set points are unchanged.
  * @param In_currentSetPoints pre-state state variable
  * @param currentSetPoints post-state state variable
  * @param api_desired_temp incoming event data port
  */
pub fn compute_spec_latchSetPointsNoEvent_guarantee(
  In_currentSetPoints: Isolette_Data_Model::Set_Points,
  currentSetPoints: Isolette_Data_Model::Set_Points,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  implies!(
    !(api_desired_temp.is_some()),
    (currentSetPoints == In_currentSetPoints))
}

/** Compute Entrypoint Contract
  *
  * guarantee invCSPMaintained
  *   Well-formedness of the latched set points is
  *   re-established for the next dispatch.
  * @param currentSetPoints post-state state variable
  */
pub fn compute_spec_invCSPMaintained_guarantee(currentSetPoints: Isolette_Data_Model::Set_Points) -> bool
{
  currentSetPoints.lower.degrees <= currentSetPoints.upper.degrees
}

/** Compute Entrypoint Contract
  *
  * guarantee noTriggerNoChange
  *   Without a triggering event (temperature change or
  *   new set points) the commanded state is unchanged.
  * @param In_lastCmd pre-state state variable
  * @param lastCmd post-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  */
pub fn compute_spec_noTriggerNoChange_guarantee(
  In_lastCmd: Isolette_Data_Model::On_Off,
  lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  implies!(
    !(api_temp_changed.is_some() || api_desired_temp.is_some()),
    (lastCmd == In_lastCmd))
}

/** Compute Entrypoint Contract
  *
  * guarantee REQ_THERM_2
  *   If triggered and the Current Temperature is less than
  *   the Lower Desired Temperature, the commanded heat state
  *   shall be set to On.
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  * @param api_current_temp incoming data port
  */
pub fn compute_spec_REQ_THERM_2_guarantee(
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_current_temp: Isolette_Data_Model::Temp) -> bool
{
  implies!(
    (api_temp_changed.is_some() || api_desired_temp.is_some()) &&
      (api_current_temp.degrees < currentSetPoints.lower.degrees),
    (lastCmd == Isolette_Data_Model::On_Off::Onn))
}

/** Compute Entrypoint Contract
  *
  * guarantee REQ_THERM_3
  *   If triggered and the Current Temperature is greater than
  *   the Upper Desired Temperature, the commanded heat state
  *   shall be set to Off.
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  * @param api_current_temp incoming data port
  */
pub fn compute_spec_REQ_THERM_3_guarantee(
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_current_temp: Isolette_Data_Model::Temp) -> bool
{
  implies!(
    (api_temp_changed.is_some() || api_desired_temp.is_some()) &&
      (api_current_temp.degrees > currentSetPoints.upper.degrees),
    (lastCmd == Isolette_Data_Model::On_Off::Off))
}

/** Compute Entrypoint Contract
  *
  * guarantee REQ_THERM_4
  *   If triggered and the Current Temperature is greater than
  *   or equal to the Lower Desired Temperature and less than
  *   or equal to the Upper Desired Temperature, the commanded
  *   heat state shall not be changed.
  * @param In_lastCmd pre-state state variable
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  * @param api_current_temp incoming data port
  */
pub fn compute_spec_REQ_THERM_4_guarantee(
  In_lastCmd: Isolette_Data_Model::On_Off,
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_current_temp: Isolette_Data_Model::Temp) -> bool
{
  implies!(
    (api_temp_changed.is_some() || api_desired_temp.is_some()) &&
      (api_current_temp.degrees >= currentSetPoints.lower.degrees) &&
      (api_current_temp.degrees <= currentSetPoints.upper.degrees),
    (lastCmd == In_lastCmd))
}

/** Compute Entrypoint Contract
  *
  * guarantee mustSendOnChange
  *   A command message is sent exactly when the commanded
  *   state changes, and it carries the new state.
  * @param In_lastCmd pre-state state variable
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing event data port
  */
pub fn compute_spec_mustSendOnChange_guarantee(
  In_lastCmd: Isolette_Data_Model::On_Off,
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  implies!(
    (lastCmd != In_lastCmd),
    api_heat_control.is_some() &&
      (api_heat_control.unwrap() == lastCmd))
}

/** Compute Entrypoint Contract
  *
  * guarantee noSendNoChange
  *   No message is sent when the commanded state is unchanged.
  * @param In_lastCmd pre-state state variable
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing event data port
  */
pub fn compute_spec_noSendNoChange_guarantee(
  In_lastCmd: Isolette_Data_Model::On_Off,
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  implies!(
    (lastCmd == In_lastCmd),
    api_heat_control.is_none())
}

/** CEP-T-Guar: Top-level guarantee contracts for thermostat's compute entrypoint
  *
  * @param In_currentSetPoints pre-state state variable
  * @param In_lastCmd pre-state state variable
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  * @param api_current_temp incoming data port
  * @param api_heat_control outgoing event data port
  */
pub fn compute_CEP_T_Guar(
  In_currentSetPoints: Isolette_Data_Model::Set_Points,
  In_lastCmd: Isolette_Data_Model::On_Off,
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_current_temp: Isolette_Data_Model::Temp,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  let r0: bool = compute_spec_latchSetPointsOnEvent_guarantee(currentSetPoints, api_desired_temp);
  let r1: bool = compute_spec_latchSetPointsNoEvent_guarantee(In_currentSetPoints, currentSetPoints, api_desired_temp);
  let r2: bool = compute_spec_invCSPMaintained_guarantee(currentSetPoints);
  let r3: bool = compute_spec_noTriggerNoChange_guarantee(In_lastCmd, lastCmd, api_temp_changed, api_desired_temp);
  let r4: bool = compute_spec_REQ_THERM_2_guarantee(currentSetPoints, lastCmd, api_temp_changed, api_desired_temp, api_current_temp);
  let r5: bool = compute_spec_REQ_THERM_3_guarantee(currentSetPoints, lastCmd, api_temp_changed, api_desired_temp, api_current_temp);
  let r6: bool = compute_spec_REQ_THERM_4_guarantee(In_lastCmd, currentSetPoints, lastCmd, api_temp_changed, api_desired_temp, api_current_temp);
  let r7: bool = compute_spec_mustSendOnChange_guarantee(In_lastCmd, lastCmd, api_heat_control);
  let r8: bool = compute_spec_noSendNoChange_guarantee(In_lastCmd, lastCmd, api_heat_control);

  return r0 && r1 && r2 && r3 && r4 && r5 && r6 && r7 && r8;
}

/** CEP-Post: Compute Entrypoint Post-Condition for thermostat
  *
  * @param In_currentSetPoints pre-state state variable
  * @param In_lastCmd pre-state state variable
  * @param currentSetPoints post-state state variable
  * @param lastCmd post-state state variable
  * @param api_temp_changed incoming event port
  * @param api_desired_temp incoming event data port
  * @param api_current_temp incoming data port
  * @param api_heat_control outgoing event data port
  */
pub fn compute_CEP_Post(
  In_currentSetPoints: Isolette_Data_Model::Set_Points,
  In_lastCmd: Isolette_Data_Model::On_Off,
  currentSetPoints: Isolette_Data_Model::Set_Points,
  lastCmd: Isolette_Data_Model::On_Off,
  api_temp_changed: Option<u8>,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_current_temp: Isolette_Data_Model::Temp,
  api_heat_control: Option<Isolette_Data_Model::On_Off>) -> bool
{
  // CEP-Guar: guarantee clauses of thermostat's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(In_currentSetPoints, In_lastCmd, currentSetPoints, lastCmd, api_temp_changed, api_desired_temp, api_current_temp, api_heat_control);

  return r0;
}
