#include "consume_consume.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void consume_consume_initialize(void);
void consume_consume_notify(microkit_channel channel);
void consume_consume_timeTriggered(void);

volatile sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *instruct_queue_1;
sb_queue_SysPropStructSplit_Data_Model_StructXY_1_Recv_t instruct_recv_queue;

#define PORT_FROM_MON 48

SysPropStructSplit_Data_Model_StructXY last_instruct_payload;

bool get_instruct(SysPropStructSplit_Data_Model_StructXY *data) {
  sb_event_counter_t numDropped;
  SysPropStructSplit_Data_Model_StructXY fresh_data;
  bool isFresh = sb_queue_SysPropStructSplit_Data_Model_StructXY_1_dequeue((sb_queue_SysPropStructSplit_Data_Model_StructXY_1_Recv_t *) &instruct_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_instruct_payload = fresh_data;
  }
  *data = last_instruct_payload;
  return isFresh;
}

void init(void) {
  sb_queue_SysPropStructSplit_Data_Model_StructXY_1_Recv_init(&instruct_recv_queue, (sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *) instruct_queue_1);

  consume_consume_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      consume_consume_timeTriggered();
      break;
    default:
      consume_consume_notify(channel);
  }
}
