// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_current_temp: Isolette_Data_Model::Temp,
  pub api_desired_temp: Isolette_Data_Model::Set_Points
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_lastCmd: Isolette_Data_Model::On_Off,
  pub api_current_temp: Isolette_Data_Model::Temp,
  pub api_desired_temp: Isolette_Data_Model::Set_Points
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_current_temp(container.api_current_temp);
  put_desired_temp(container.api_desired_temp);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_lastCmd(container.In_lastCmd);
  put_current_temp(container.api_current_temp);
  put_desired_temp(container.api_desired_temp);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  current_temp: Isolette_Data_Model::Temp,
  desired_temp: Isolette_Data_Model::Set_Points)
{
  put_current_temp(current_temp);
  put_desired_temp(desired_temp);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_lastCmd: Isolette_Data_Model::On_Off,
  current_temp: Isolette_Data_Model::Temp,
  desired_temp: Isolette_Data_Model::Set_Points)
{
  put_lastCmd(In_lastCmd);
  put_current_temp(current_temp);
  put_desired_temp(desired_temp);
}

/// setter for IN DataPort
pub fn put_current_temp(value: Isolette_Data_Model::Temp)
{
  *extern_api::IN_current_temp.lock().unwrap() = Some(value)
}

/// setter for IN DataPort
pub fn put_desired_temp(value: Isolette_Data_Model::Set_Points)
{
  *extern_api::IN_desired_temp.lock().unwrap() = Some(value)
}

/// getter for OUT DataPort
pub fn get_heat_control() -> Isolette_Data_Model::On_Off
{
  return extern_api::OUT_heat_control.lock().unwrap().expect("Not expecting None")
}

/// getter for GUMBO State Variable
pub fn get_lastCmd() -> Isolette_Data_Model::On_Off
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.lastCmd,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_lastCmd(value: Isolette_Data_Model::On_Off)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.lastCmd = value,
      None => panic!("The app is None")
    }
  }
}
