// Do not edit this file as it will be overwritten if codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_heat_control(value: *mut Isolette_Data_Model::On_Off) -> bool;
}

pub fn unsafe_get_heat_control() -> Isolette_Data_Model::On_Off
{
  unsafe {
    let value: *mut Isolette_Data_Model::On_Off = &mut Isolette_Data_Model::On_Off::default();
    get_heat_control(value);
    return *value;
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_heat_control: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_heat_control.lock().unwrap() = None;
  }
}

#[cfg(test)]
pub fn get_heat_control(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    *value = IN_heat_control.lock().unwrap().expect("Not expecting None");
    return true;
  }
}
