# Do not edit this file as it will be overwritten if codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

SYSTEM_FILE := $(TOP_DIR)/microkit.system
SCHEDULE_FILE := $(TOP_DIR)/microkit.schedule.xml

IMAGES := gate_gate.elf gate_gate_MON.elf msg_filter_msg_filter.elf msg_filter_msg_filter_MON.elf test_sender_test_sender.elf test_sender_test_sender_MON.elf test_receiver_test_receiver.elf test_receiver_test_receiver_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_SNG_Data_Model_Message_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_SNG_Data_Model_Message_1.o: $(TOP_DIR)/types/src/sb_queue_SNG_Data_Model_Message_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
gate_gate_MON.o: $(TOP_DIR)/components/gate_gate/src/gate_gate_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/gate_gate/include

# user code
gate_gate_rust:
	make -C ${CRATES_DIR}/gate_gate $(RUST_MAKE_TARGET)

gate_gate.o: $(TOP_DIR)/components/gate_gate/src/gate_gate.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/gate_gate/include

# monitor
msg_filter_msg_filter_MON.o: $(TOP_DIR)/components/msg_filter_msg_filter/src/msg_filter_msg_filter_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/msg_filter_msg_filter/include

# user code
msg_filter_msg_filter_rust:
	make -C ${CRATES_DIR}/msg_filter_msg_filter $(RUST_MAKE_TARGET)

msg_filter_msg_filter.o: $(TOP_DIR)/components/msg_filter_msg_filter/src/msg_filter_msg_filter.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/msg_filter_msg_filter/include

# monitor
test_sender_test_sender_MON.o: $(TOP_DIR)/components/test_sender_test_sender/src/test_sender_test_sender_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/test_sender_test_sender/include

# user code
test_sender_test_sender_rust:
	make -C ${CRATES_DIR}/test_sender_test_sender $(RUST_MAKE_TARGET)

test_sender_test_sender.o: $(TOP_DIR)/components/test_sender_test_sender/src/test_sender_test_sender.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/test_sender_test_sender/include

# monitor
test_receiver_test_receiver_MON.o: $(TOP_DIR)/components/test_receiver_test_receiver/src/test_receiver_test_receiver_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/test_receiver_test_receiver/include

# user code
test_receiver_test_receiver_rust:
	make -C ${CRATES_DIR}/test_receiver_test_receiver $(RUST_MAKE_TARGET)

test_receiver_test_receiver.o: $(TOP_DIR)/components/test_receiver_test_receiver/src/test_receiver_test_receiver.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/test_receiver_test_receiver/include

pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

gate_gate_MON.elf: gate_gate_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

gate_gate.elf: $(UTIL_OBJS) $(TYPE_OBJS) gate_gate_rust gate_gate.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/gate_gate/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lgate_gate -o $@

msg_filter_msg_filter_MON.elf: msg_filter_msg_filter_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

msg_filter_msg_filter.elf: $(UTIL_OBJS) $(TYPE_OBJS) msg_filter_msg_filter_rust msg_filter_msg_filter.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/msg_filter_msg_filter/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lmsg_filter_msg_filter -o $@

test_sender_test_sender_MON.elf: test_sender_test_sender_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

test_sender_test_sender.elf: $(UTIL_OBJS) $(TYPE_OBJS) test_sender_test_sender_rust test_sender_test_sender.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/test_sender_test_sender/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -ltest_sender_test_sender -o $@

test_receiver_test_receiver_MON.elf: test_receiver_test_receiver_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

test_receiver_test_receiver.elf: $(UTIL_OBJS) $(TYPE_OBJS) test_receiver_test_receiver_rust test_receiver_test_receiver.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/test_receiver_test_receiver/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -ltest_receiver_test_receiver -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(SYSTEM_FILE)
	xmllint --xinclude $(SYSTEM_FILE) -o $(SYSTEM_FILE).merged
	$(MICROKIT_TOOL) $(SYSTEM_FILE).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu:
	$(QEMU) -machine virt,virtualization=on \
			-cpu cortex-a53 \
			-serial mon:stdio \
			-device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
			-m size=2G \
			-nographic

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/gate_gate test
	make -C ${CRATES_DIR}/msg_filter_msg_filter test
	make -C ${CRATES_DIR}/test_sender_test_sender test
	make -C ${CRATES_DIR}/test_receiver_test_receiver test

clean:: 
	make -C ${CRATES_DIR}/gate_gate clean
	make -C ${CRATES_DIR}/msg_filter_msg_filter clean
	make -C ${CRATES_DIR}/test_sender_test_sender clean
	make -C ${CRATES_DIR}/test_receiver_test_receiver clean

verus: 
	make -C ${CRATES_DIR}/gate_gate verus
	make -C ${CRATES_DIR}/msg_filter_msg_filter verus
	make -C ${CRATES_DIR}/test_sender_test_sender verus
	make -C ${CRATES_DIR}/test_receiver_test_receiver verus
