// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Set_Points {
    pub lower: Temp,
    pub upper: Temp
  }

  impl Default for Set_Points {
    fn default() -> Self
    {
      Self { lower: Isolette_Data_Model::Temp::default(), upper: Isolette_Data_Model::Temp::default() }
    }
  }
}