#include "prod_prod.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void prod_prod_initialize(void);
void prod_prod_notify(microkit_channel channel);
void prod_prod_timeTriggered(void);

volatile sb_queue_ProdCons_Message_1_t *output_queue_1;

#define PORT_FROM_MON 60

bool put_output(const ProdCons_Message *data) {
  sb_queue_ProdCons_Message_1_enqueue((sb_queue_ProdCons_Message_1_t *) output_queue_1, (ProdCons_Message *) data);

  return true;
}

void init(void) {
  sb_queue_ProdCons_Message_1_init((sb_queue_ProdCons_Message_1_t *) output_queue_1);

  prod_prod_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      prod_prod_timeTriggered();
      break;
    default:
      prod_prod_notify(channel);
  }
}
