// Do not edit this file as it will be overwritten if codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_current_temp(value: *mut Isolette_Data_Model::Temp) -> bool;
  fn get_desired_temp(value: *mut Isolette_Data_Model::Set_Points) -> bool;
  fn put_heat_control(value: *mut Isolette_Data_Model::On_Off) -> bool;
}

pub fn unsafe_get_current_temp() -> Isolette_Data_Model::Temp
{
  unsafe {
    let value: *mut Isolette_Data_Model::Temp = &mut Isolette_Data_Model::Temp::default();
    get_current_temp(value);
    return *value;
  }
}

pub fn unsafe_get_desired_temp() -> Isolette_Data_Model::Set_Points
{
  unsafe {
    let value: *mut Isolette_Data_Model::Set_Points = &mut Isolette_Data_Model::Set_Points::default();
    get_desired_temp(value);
    return *value;
  }
}

pub fn unsafe_put_heat_control(value: &Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    return put_heat_control(value as *const Isolette_Data_Model::On_Off as *mut Isolette_Data_Model::On_Off);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_current_temp: Mutex<Option<Isolette_Data_Model::Temp>> = Mutex::new(None);
  pub static ref IN_desired_temp: Mutex<Option<Isolette_Data_Model::Set_Points>> = Mutex::new(None);
  pub static ref OUT_heat_control: Mutex<Option<Isolette_Data_Model::On_Off>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_current_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *IN_desired_temp.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_heat_control.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_current_temp(value: *mut Isolette_Data_Model::Temp) -> bool
{
  unsafe {
    let guard = IN_current_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn get_desired_temp(value: *mut Isolette_Data_Model::Set_Points) -> bool
{
  unsafe {
    let guard = IN_desired_temp.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn put_heat_control(value: *mut Isolette_Data_Model::On_Off) -> bool
{
  unsafe {
    *OUT_heat_control.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
