// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

pub fn Temp_Lower_Bound() -> i32
{
  95i32
}

pub fn Temp_Upper_Bound() -> i32
{
  104i32
}

/** I-Assm: Integration constraint on thermostat's incoming data port current_temp
  *
  * assume ASSM_CT_Range
  */
pub fn I_Assm_current_temp(current_temp: Isolette_Data_Model::Temp) -> bool
{
  (Temp_Lower_Bound() <= current_temp.degrees) &
    (current_temp.degrees <= Temp_Upper_Bound())
}

/** Initialize EntryPointContract
  *
  * guarantee initlastCmd
  * @param lastCmd post-state state variable
  */
pub fn initialize_initlastCmd(lastCmd: Isolette_Data_Model::On_Off) -> bool
{
  lastCmd == Isolette_Data_Model::On_Off::Off
}

/** Initialize EntryPointContract
  *
  * guarantee REQ_THERM_1
  *   The Heat Control command shall be Off initially.
  * @param api_heat_control outgoing data port
  */
pub fn initialize_REQ_THERM_1(api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  api_heat_control == Isolette_Data_Model::On_Off::Off
}

/** IEP-Guar: Initialize Entrypoint for thermostat
  *
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing data port
  */
pub fn initialize_IEP_Guar(
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  initialize_initlastCmd(lastCmd) &&
  initialize_REQ_THERM_1(api_heat_control)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing data port
  */
pub fn initialize_IEP_Post(
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  initialize_IEP_Guar(lastCmd, api_heat_control)
}

/** Compute Entrypoint Contract
  *
  * assumes ASSM_LDT_LE_UDT
  * @param api_desired_temp incoming data port
  */
pub fn compute_spec_ASSM_LDT_LE_UDT_assume(api_desired_temp: Isolette_Data_Model::Set_Points) -> bool
{
  api_desired_temp.lower.degrees <= api_desired_temp.upper.degrees
}

/** CEP-T-Assm: Top-level assume contracts for thermostat's compute entrypoint
  *
  * @param api_desired_temp incoming data port
  */
pub fn compute_CEP_T_Assm(api_desired_temp: Isolette_Data_Model::Set_Points) -> bool
{
  let r0: bool = compute_spec_ASSM_LDT_LE_UDT_assume(api_desired_temp);

  return r0;
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for thermostat
  *
  * @param In_lastCmd pre-state state variable
  * @param api_current_temp incoming data port
  * @param api_desired_temp incoming data port
  */
pub fn compute_CEP_Pre(
  In_lastCmd: Isolette_Data_Model::On_Off,
  api_current_temp: Isolette_Data_Model::Temp,
  api_desired_temp: Isolette_Data_Model::Set_Points) -> bool
{
  // I-Assm-Guard: Integration constraints for thermostat's incoming ports
  let r0: bool = I_Assm_current_temp(api_current_temp);

  // CEP-Assm: assume clauses of thermostat's compute entrypoint
  let r1: bool = compute_CEP_T_Assm(api_desired_temp);

  return r0 && r1;
}

/** Compute Entrypoint Contract
  *
  * guarantee lastCmd
  *   Set lastCmd to value of output Cmd port
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing data port
  */
pub fn compute_spec_lastCmd_guarantee(
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  lastCmd == api_heat_control
}

/** CEP-T-Guar: Top-level guarantee contracts for thermostat's compute entrypoint
  *
  * @param lastCmd post-state state variable
  * @param api_heat_control outgoing data port
  */
pub fn compute_CEP_T_Guar(
  lastCmd: Isolette_Data_Model::On_Off,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  let r0: bool = compute_spec_lastCmd_guarantee(lastCmd, api_heat_control);

  return r0;
}

/** guarantee REQ_THERM_2
  *   If Current Temperature is less than
  *   the Lower Desired Temperature, the Heat Control shall be set to On.
  * @param api_current_temp incoming data port
  * @param api_desired_temp incoming data port
  * @param api_heat_control outgoing data port
  */
pub fn compute_case_REQ_THERM_2(
  api_current_temp: Isolette_Data_Model::Temp,
  api_desired_temp: Isolette_Data_Model::Set_Points,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  implies!(
    api_current_temp.degrees < api_desired_temp.lower.degrees,
    api_heat_control == Isolette_Data_Model::On_Off::Onn)
}

/** guarantee REQ_THERM_3
  *   If the Current Temperature is greater than
  *   the Upper Desired Temperature, the Heat Control shall be set to Off.
  * @param api_current_temp incoming data port
  * @param api_desired_temp incoming data port
  * @param api_heat_control outgoing data port
  */
pub fn compute_case_REQ_THERM_3(
  api_current_temp: Isolette_Data_Model::Temp,
  api_desired_temp: Isolette_Data_Model::Set_Points,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  implies!(
    api_current_temp.degrees > api_desired_temp.upper.degrees,
    api_heat_control == Isolette_Data_Model::On_Off::Off)
}

/** guarantee REQ_THERM_4
  *   If the Current Temperature is greater than or equal 
  *   to the Lower Desired Temperature
  *   and less than or equal to the Upper Desired Temperature, the value of
  *   the Heat Control shall not be changed.
  * @param In_lastCmd pre-state state variable
  * @param api_current_temp incoming data port
  * @param api_desired_temp incoming data port
  * @param api_heat_control outgoing data port
  */
pub fn compute_case_REQ_THERM_4(
  In_lastCmd: Isolette_Data_Model::On_Off,
  api_current_temp: Isolette_Data_Model::Temp,
  api_desired_temp: Isolette_Data_Model::Set_Points,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  implies!(
    (api_current_temp.degrees >= api_desired_temp.lower.degrees) &
      (api_current_temp.degrees <= api_desired_temp.upper.degrees),
    api_heat_control == In_lastCmd)
}

/** CEP-T-Case: Top-Level case contracts for thermostat's compute entrypoint
  *
  * @param In_lastCmd pre-state state variable
  * @param api_current_temp incoming data port
  * @param api_desired_temp incoming data port
  * @param api_heat_control outgoing data port
  */
pub fn compute_CEP_T_Case(
  In_lastCmd: Isolette_Data_Model::On_Off,
  api_current_temp: Isolette_Data_Model::Temp,
  api_desired_temp: Isolette_Data_Model::Set_Points,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  let r0: bool = compute_case_REQ_THERM_2(api_current_temp, api_desired_temp, api_heat_control);
  let r1: bool = compute_case_REQ_THERM_3(api_current_temp, api_desired_temp, api_heat_control);
  let r2: bool = compute_case_REQ_THERM_4(In_lastCmd, api_current_temp, api_desired_temp, api_heat_control);

  return r0 && r1 && r2;
}

/** CEP-Post: Compute Entrypoint Post-Condition for thermostat
  *
  * @param In_lastCmd pre-state state variable
  * @param lastCmd post-state state variable
  * @param api_current_temp incoming data port
  * @param api_desired_temp incoming data port
  * @param api_heat_control outgoing data port
  */
pub fn compute_CEP_Post(
  In_lastCmd: Isolette_Data_Model::On_Off,
  lastCmd: Isolette_Data_Model::On_Off,
  api_current_temp: Isolette_Data_Model::Temp,
  api_desired_temp: Isolette_Data_Model::Set_Points,
  api_heat_control: Isolette_Data_Model::On_Off) -> bool
{
  // CEP-Guar: guarantee clauses of thermostat's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(lastCmd, api_heat_control);

  // CEP-T-Case: case clauses of thermostat's compute entrypoint
  let r1: bool = compute_CEP_T_Case(In_lastCmd, api_current_temp, api_desired_temp, api_heat_control);

  return r0 && r1;
}
