// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait thermostat_thermostat_Api {}

  pub trait thermostat_thermostat_Put_Api: thermostat_thermostat_Api {
    #[verifier::external_body]
    fn unverified_put_heat_control(
      &mut self,
      value: Isolette_Data_Model::On_Off)
    {
      extern_api::unsafe_put_heat_control(&value);
    }
  }

  pub trait thermostat_thermostat_Get_Api: thermostat_thermostat_Api {
    #[verifier::external_body]
    fn unverified_get_current_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Temp>) -> (res : Isolette_Data_Model::Temp)
      ensures
        res == value@,
        // assume ASSM_CT_Range
        (crate::component::thermostat_thermostat_app::Temp_Lower_Bound() <= res.degrees) &&
          (res.degrees <= crate::component::thermostat_thermostat_app::Temp_Upper_Bound()),
    {
      return extern_api::unsafe_get_current_temp();
    }

    #[verifier::external_body]
    fn unverified_get_desired_temp(
      &mut self,
      value: &Ghost<Isolette_Data_Model::Set_Points>) -> (res : Isolette_Data_Model::Set_Points)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_desired_temp();
    }
  }

  pub trait thermostat_thermostat_Full_Api: thermostat_thermostat_Put_Api + thermostat_thermostat_Get_Api {}

  pub struct thermostat_thermostat_Application_Api<API: thermostat_thermostat_Api> {
    pub api: API,

    pub ghost current_temp: Isolette_Data_Model::Temp,
    pub ghost desired_temp: Isolette_Data_Model::Set_Points,
    pub ghost heat_control: Isolette_Data_Model::On_Off
  }

  impl<API: thermostat_thermostat_Put_Api> thermostat_thermostat_Application_Api<API> {
    pub fn put_heat_control(
      &mut self,
      value: Isolette_Data_Model::On_Off)
      ensures
        old(self).current_temp == self.current_temp,
        old(self).desired_temp == self.desired_temp,
        self.heat_control == value,
    {
      self.api.unverified_put_heat_control(value);
      self.heat_control = value;
    }
  }

  impl<API: thermostat_thermostat_Get_Api> thermostat_thermostat_Application_Api<API> {
    pub fn get_current_temp(&mut self) -> (res : Isolette_Data_Model::Temp)
      ensures
        old(self).current_temp == self.current_temp,
        res == self.current_temp,
        old(self).desired_temp == self.desired_temp,
        old(self).heat_control == self.heat_control,
        // assume ASSM_CT_Range
        (crate::component::thermostat_thermostat_app::Temp_Lower_Bound() <= res.degrees) &&
          (res.degrees <= crate::component::thermostat_thermostat_app::Temp_Upper_Bound()),
    {
      self.api.unverified_get_current_temp(&Ghost(self.current_temp))
    }
    pub fn get_desired_temp(&mut self) -> (res : Isolette_Data_Model::Set_Points)
      ensures
        old(self).current_temp == self.current_temp,
        old(self).desired_temp == self.desired_temp,
        res == self.desired_temp,
        old(self).heat_control == self.heat_control,
    {
      self.api.unverified_get_desired_temp(&Ghost(self.desired_temp))
    }
  }

  pub struct thermostat_thermostat_Initialization_Api;
  impl thermostat_thermostat_Api for thermostat_thermostat_Initialization_Api {}
  impl thermostat_thermostat_Put_Api for thermostat_thermostat_Initialization_Api {}

  pub const fn init_api() -> thermostat_thermostat_Application_Api<thermostat_thermostat_Initialization_Api> {
    return thermostat_thermostat_Application_Api {
      api: thermostat_thermostat_Initialization_Api {},

      current_temp: Isolette_Data_Model::Temp { degrees: 0 },
      desired_temp: Isolette_Data_Model::Set_Points { lower: Isolette_Data_Model::Temp { degrees: 0 }, upper: Isolette_Data_Model::Temp { degrees: 0 } },
      heat_control: Isolette_Data_Model::On_Off::Onn
    }
  }

  pub struct thermostat_thermostat_Compute_Api;
  impl thermostat_thermostat_Api for thermostat_thermostat_Compute_Api {}
  impl thermostat_thermostat_Put_Api for thermostat_thermostat_Compute_Api {}
  impl thermostat_thermostat_Get_Api for thermostat_thermostat_Compute_Api {}
  impl thermostat_thermostat_Full_Api for thermostat_thermostat_Compute_Api {}

  pub const fn compute_api() -> thermostat_thermostat_Application_Api<thermostat_thermostat_Compute_Api> {
    return thermostat_thermostat_Application_Api {
      api: thermostat_thermostat_Compute_Api {},

      current_temp: Isolette_Data_Model::Temp { degrees: 0 },
      desired_temp: Isolette_Data_Model::Set_Points { lower: Isolette_Data_Model::Temp { degrees: 0 }, upper: Isolette_Data_Model::Temp { degrees: 0 } },
      heat_control: Isolette_Data_Model::On_Off::Onn
    }
  }
}