#include "test_sender_test_sender.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void test_sender_test_sender_initialize(void);
void test_sender_test_sender_notify(microkit_channel channel);
void test_sender_test_sender_timeTriggered(void);

volatile sb_queue_SNG_Data_Model_Message_1_t *output_queue_1;

#define PORT_FROM_MON 56

bool put_output(const SNG_Data_Model_Message *data) {
  sb_queue_SNG_Data_Model_Message_1_enqueue((sb_queue_SNG_Data_Model_Message_1_t *) output_queue_1, (SNG_Data_Model_Message *) data);

  return true;
}

void init(void) {
  sb_queue_SNG_Data_Model_Message_1_init((sb_queue_SNG_Data_Model_Message_1_t *) output_queue_1);

  test_sender_test_sender_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      test_sender_test_sender_timeTriggered();
      break;
    default:
      test_sender_test_sender_notify(channel);
  }
}
