#pragma once

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_SysPropStructSplit_Data_Model_StructXY_1.h>
#include <sb_queue_int32_t_1.h>
