// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_instruct: SysPropStructSplit_Data_Model::StructXY
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_last_x: i32,
  pub api_instruct: SysPropStructSplit_Data_Model::StructXY
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_instruct(container.api_instruct);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_last_x(container.In_last_x);
  put_instruct(container.api_instruct);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(instruct: SysPropStructSplit_Data_Model::StructXY)
{
  put_instruct(instruct);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_last_x: i32,
  instruct: SysPropStructSplit_Data_Model::StructXY)
{
  put_last_x(In_last_x);
  put_instruct(instruct);
}

/// setter for IN DataPort
pub fn put_instruct(value: SysPropStructSplit_Data_Model::StructXY)
{
  *extern_api::IN_instruct.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// getter for GUMBO State Variable
pub fn get_last_x() -> i32
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.last_x,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_last_x(value: i32)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.last_x = value,
      None => panic!("The app is None")
    }
  }
}
