#include "heat_source_heat_source.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void heat_source_heat_source_initialize(void);
void heat_source_heat_source_notify(microkit_channel channel);
void heat_source_heat_source_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_On_Off_1_t *heat_control_queue_1;
sb_queue_Isolette_Data_Model_On_Off_1_Recv_t heat_control_recv_queue;

#define PORT_FROM_MON 54

bool heat_control_is_empty(void) {
  return sb_queue_Isolette_Data_Model_On_Off_1_is_empty(&heat_control_recv_queue);
}

bool get_heat_control_poll(sb_event_counter_t *numDropped, Isolette_Data_Model_On_Off *data) {
  return sb_queue_Isolette_Data_Model_On_Off_1_dequeue((sb_queue_Isolette_Data_Model_On_Off_1_Recv_t *) &heat_control_recv_queue, numDropped, data);
}

bool get_heat_control(Isolette_Data_Model_On_Off *data) {
  sb_event_counter_t numDropped;
  return get_heat_control_poll (&numDropped, data);
}

void init(void) {
  sb_queue_Isolette_Data_Model_On_Off_1_Recv_init(&heat_control_recv_queue, (sb_queue_Isolette_Data_Model_On_Off_1_t *) heat_control_queue_1);

  heat_source_heat_source_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      heat_source_heat_source_timeTriggered();
      break;
    default:
      heat_source_heat_source_notify(channel);
  }
}
