// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Temp {
    pub degrees: i32
  }

  impl Default for Temp {
    fn default() -> Self
    {
      Self { degrees: 0 }
    }
  }
}