// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn SNG_Data_Model_SecurityLevel_strategy_default() -> impl Strategy<Value = SNG_Data_Model::SecurityLevel>
{
  SNG_Data_Model_SecurityLevel_strategy_cust(1, 1, 1)
}

pub fn SNG_Data_Model_SecurityLevel_strategy_cust(
  Public_bias: u32,
  Restricted_bias: u32,
  Critical_bias: u32) -> impl Strategy<Value = SNG_Data_Model::SecurityLevel>
{
  prop_oneof![
    Public_bias => Just(SNG_Data_Model::SecurityLevel::Public),
    Restricted_bias => Just(SNG_Data_Model::SecurityLevel::Restricted),
    Critical_bias => Just(SNG_Data_Model::SecurityLevel::Critical)
  ]
}

pub fn SNG_Data_Model_Message_strategy_default() -> impl Strategy<Value = SNG_Data_Model::Message>
{
  SNG_Data_Model_Message_strategy_cust(
    any::<i32>(),
    SNG_Data_Model_SecurityLevel_strategy_default()
  )
}

pub fn SNG_Data_Model_Message_strategy_cust
  <payload_i32_strategy: Strategy<Value = i32>, 
   security_level_SNG_Data_Model_SecurityLevel_strategy: Strategy<Value = SNG_Data_Model::SecurityLevel>> (
  payload_strategy: payload_i32_strategy,
  security_level_strategy: security_level_SNG_Data_Model_SecurityLevel_strategy) -> impl Strategy<Value = SNG_Data_Model::Message>
{
  (payload_strategy, security_level_strategy).prop_map(|(payload, security_level)| {
    SNG_Data_Model::Message { payload, security_level }
  })
}
