#include "operator_interface_operator_interface.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void operator_interface_operator_interface_initialize(void);
void operator_interface_operator_interface_notify(microkit_channel channel);
void operator_interface_operator_interface_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_Set_Points_1_t *desired_temp_queue_1;

#define PORT_FROM_MON 58

bool put_desired_temp(const Isolette_Data_Model_Set_Points *data) {
  sb_queue_Isolette_Data_Model_Set_Points_1_enqueue((sb_queue_Isolette_Data_Model_Set_Points_1_t *) desired_temp_queue_1, (Isolette_Data_Model_Set_Points *) data);

  return true;
}

void init(void) {
  sb_queue_Isolette_Data_Model_Set_Points_1_init((sb_queue_Isolette_Data_Model_Set_Points_1_t *) desired_temp_queue_1);

  operator_interface_operator_interface_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      operator_interface_operator_interface_timeTriggered();
      break;
    default:
      operator_interface_operator_interface_notify(channel);
  }
}
