#pragma once

// Do not edit this file as it will be overwritten if codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_Isolette_Data_Model_Temp_1.h>
#include <sb_queue_Isolette_Data_Model_Set_Points_1.h>
#include <sb_queue_Isolette_Data_Model_On_Off_1.h>
