// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait temp_sensor_temp_sensor_Api {}

  pub trait temp_sensor_temp_sensor_Put_Api: temp_sensor_temp_sensor_Api {
    #[verifier::external_body]
    fn unverified_put_current_temp(
      &mut self,
      value: Isolette_Data_Model::Temp)
    {
      extern_api::unsafe_put_current_temp(&value);
    }

    #[verifier::external_body]
    fn unverified_put_temp_changed(
      &mut self,
      value: Isolette_Data_Model::Temp)
    {
      extern_api::unsafe_put_temp_changed(&value);
    }
  }

  pub trait temp_sensor_temp_sensor_Get_Api: temp_sensor_temp_sensor_Api {
  }

  pub trait temp_sensor_temp_sensor_Full_Api: temp_sensor_temp_sensor_Put_Api + temp_sensor_temp_sensor_Get_Api {}

  pub struct temp_sensor_temp_sensor_Application_Api<API: temp_sensor_temp_sensor_Api> {
    pub api: API,

    pub ghost current_temp: Isolette_Data_Model::Temp,
    pub ghost temp_changed: Option<Isolette_Data_Model::Temp>
  }

  impl<API: temp_sensor_temp_sensor_Put_Api> temp_sensor_temp_sensor_Application_Api<API> {
    pub fn put_current_temp(
      &mut self,
      value: Isolette_Data_Model::Temp)
      requires
        // guarantee temp_range
        (96i32 <= value.degrees) &&
          (value.degrees <= 103i32),
      ensures
        self.current_temp == value,
        old(self).temp_changed == self.temp_changed,
    {
      self.api.unverified_put_current_temp(value);
      self.current_temp = value;
    }
    pub fn put_temp_changed(
      &mut self,
      value: Isolette_Data_Model::Temp)
      requires
        // guarantee temp_changed_range
        (96i32 <= value.degrees) &&
          (value.degrees <= 103i32),
      ensures
        old(self).current_temp == self.current_temp,
        self.temp_changed == Some(value),
    {
      self.api.unverified_put_temp_changed(value);
      self.temp_changed = Some(value);
    }
  }

  impl<API: temp_sensor_temp_sensor_Get_Api> temp_sensor_temp_sensor_Application_Api<API> {
  }

  pub struct temp_sensor_temp_sensor_Initialization_Api;
  impl temp_sensor_temp_sensor_Api for temp_sensor_temp_sensor_Initialization_Api {}
  impl temp_sensor_temp_sensor_Put_Api for temp_sensor_temp_sensor_Initialization_Api {}

  pub const fn init_api() -> temp_sensor_temp_sensor_Application_Api<temp_sensor_temp_sensor_Initialization_Api> {
    return temp_sensor_temp_sensor_Application_Api {
      api: temp_sensor_temp_sensor_Initialization_Api {},

      current_temp: Isolette_Data_Model::Temp { degrees: 0 },
      temp_changed: None
    }
  }

  pub struct temp_sensor_temp_sensor_Compute_Api;
  impl temp_sensor_temp_sensor_Api for temp_sensor_temp_sensor_Compute_Api {}
  impl temp_sensor_temp_sensor_Put_Api for temp_sensor_temp_sensor_Compute_Api {}
  impl temp_sensor_temp_sensor_Get_Api for temp_sensor_temp_sensor_Compute_Api {}
  impl temp_sensor_temp_sensor_Full_Api for temp_sensor_temp_sensor_Compute_Api {}

  pub const fn compute_api() -> temp_sensor_temp_sensor_Application_Api<temp_sensor_temp_sensor_Compute_Api> {
    return temp_sensor_temp_sensor_Application_Api {
      api: temp_sensor_temp_sensor_Compute_Api {},

      current_temp: Isolette_Data_Model::Temp { degrees: 0 },
      temp_changed: None
    }
  }

}