// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait gate_gate_Api {}

  pub trait gate_gate_Put_Api: gate_gate_Api {
    #[verifier::external_body]
    fn unverified_put_output(
      &mut self,
      value: SNG_Data_Model::Message)
    {
      extern_api::unsafe_put_output(&value);
    }
  }

  pub trait gate_gate_Get_Api: gate_gate_Api {
    #[verifier::external_body]
    fn unverified_get_input(
      &mut self,
      value: &Ghost<Option<SNG_Data_Model::Message>>) -> (res : Option<SNG_Data_Model::Message>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_input();
    }
  }

  pub trait gate_gate_Full_Api: gate_gate_Put_Api + gate_gate_Get_Api {}

  pub struct gate_gate_Application_Api<API: gate_gate_Api> {
    pub api: API,

    pub ghost input: Option<SNG_Data_Model::Message>,
    pub ghost output: Option<SNG_Data_Model::Message>
  }

  impl<API: gate_gate_Put_Api> gate_gate_Application_Api<API> {
    pub fn put_output(
      &mut self,
      value: SNG_Data_Model::Message)
      requires
        // guarantee No_Critical_Output
        GumboLib::allowedSecurityLevel_spec(value),
      ensures
        old(self).input == self.input,
        self.output == Some(value),
    {
      self.api.unverified_put_output(value);
      self.output = Some(value);
    }
  }

  impl<API: gate_gate_Get_Api> gate_gate_Application_Api<API> {
    pub fn get_input(&mut self) -> (res : Option<SNG_Data_Model::Message>)
      ensures
        old(self).input == self.input,
        res == self.input,
        old(self).output == self.output,
    {
      self.api.unverified_get_input(&Ghost(self.input))
    }
  }

  pub struct gate_gate_Initialization_Api;
  impl gate_gate_Api for gate_gate_Initialization_Api {}
  impl gate_gate_Put_Api for gate_gate_Initialization_Api {}

  pub const fn init_api() -> gate_gate_Application_Api<gate_gate_Initialization_Api> {
    return gate_gate_Application_Api {
      api: gate_gate_Initialization_Api {},

      input: None,
      output: None
    }
  }

  pub struct gate_gate_Compute_Api;
  impl gate_gate_Api for gate_gate_Compute_Api {}
  impl gate_gate_Put_Api for gate_gate_Compute_Api {}
  impl gate_gate_Get_Api for gate_gate_Compute_Api {}
  impl gate_gate_Full_Api for gate_gate_Compute_Api {}

  pub const fn compute_api() -> gate_gate_Application_Api<gate_gate_Compute_Api> {
    return gate_gate_Application_Api {
      api: gate_gate_Compute_Api {},

      input: None,
      output: None
    }
  }
}