#include "gen_gen.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void gen_gen_initialize(void);
void gen_gen_notify(microkit_channel channel);
void gen_gen_timeTriggered(void);

volatile sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *outstruct_queue_1;

#define PORT_FROM_MON 60

bool put_outstruct(const SysPropStructSplit_Data_Model_StructXY *data) {
  sb_queue_SysPropStructSplit_Data_Model_StructXY_1_enqueue((sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *) outstruct_queue_1, (SysPropStructSplit_Data_Model_StructXY *) data);

  return true;
}

void init(void) {
  sb_queue_SysPropStructSplit_Data_Model_StructXY_1_init((sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *) outstruct_queue_1);

  gen_gen_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      gen_gen_timeTriggered();
      break;
    default:
      gen_gen_notify(channel);
  }
}
