// #Sireum

package ProdConsExample.ProdCons

import org.sireum._
import ProdConsExample._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Message_i {
  def example(): ProdCons.Message_i = {
    return ProdCons.Message_i(
      value = Base_Types.Integer_32_example(),
      section = Base_Types.Integer_32_example())
  }
}

@datatype class Message_i(
  val value: S32,
  val section: S32) {
}

object Message_i_Payload {
  def example(): Message_i_Payload = {
    return Message_i_Payload(ProdCons.Message_i.example())
  }
}

@datatype class Message_i_Payload(value: ProdCons.Message_i) extends art.DataContent
