// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_instruct(value: *mut SysPropStructSplit_Data_Model::StructXY) -> bool;
  fn put_xfield(value: *mut i32) -> bool;
  fn put_yfield(value: *mut i32) -> bool;
}

pub fn unsafe_get_instruct() -> SysPropStructSplit_Data_Model::StructXY
{
  unsafe {
    let value: *mut SysPropStructSplit_Data_Model::StructXY = &mut SysPropStructSplit_Data_Model::StructXY::default();
    get_instruct(value);
    return *value;
  }
}

pub fn unsafe_put_xfield(value: &i32) -> bool
{
  unsafe {
    return put_xfield(value as *const i32 as *mut i32);
  }
}

pub fn unsafe_put_yfield(value: &i32) -> bool
{
  unsafe {
    return put_yfield(value as *const i32 as *mut i32);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_instruct: Mutex<Option<SysPropStructSplit_Data_Model::StructXY>> = Mutex::new(None);
  pub static ref OUT_xfield: Mutex<Option<i32>> = Mutex::new(None);
  pub static ref OUT_yfield: Mutex<Option<i32>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_instruct.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_xfield.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_yfield.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_instruct(value: *mut SysPropStructSplit_Data_Model::StructXY) -> bool
{
  unsafe {
    let guard = IN_instruct.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn put_xfield(value: *mut i32) -> bool
{
  unsafe {
    *OUT_xfield.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}

#[cfg(test)]
pub fn put_yfield(value: *mut i32) -> bool
{
  unsafe {
    *OUT_yfield.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
