// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait splitter_splitter_Api {}

  pub trait splitter_splitter_Put_Api: splitter_splitter_Api {
    #[verifier::external_body]
    fn unverified_put_xfield(
      &mut self,
      value: i32)
    {
      extern_api::unsafe_put_xfield(&value);
    }

    #[verifier::external_body]
    fn unverified_put_yfield(
      &mut self,
      value: i32)
    {
      extern_api::unsafe_put_yfield(&value);
    }
  }

  pub trait splitter_splitter_Get_Api: splitter_splitter_Api {
    #[verifier::external_body]
    fn unverified_get_instruct(
      &mut self,
      value: &Ghost<SysPropStructSplit_Data_Model::StructXY>) -> (res : SysPropStructSplit_Data_Model::StructXY)
      ensures
        res == value@,
        // assume instruct_range
        //   Incoming struct fields lie in [-100, 100].
        (((-100i32 <= res.x) &&
          (res.x <= 100i32)) &&
          (-100i32 <= res.y)) &&
          (res.y <= 100i32),
    {
      return extern_api::unsafe_get_instruct();
    }
  }

  pub trait splitter_splitter_Full_Api: splitter_splitter_Put_Api + splitter_splitter_Get_Api {}

  pub struct splitter_splitter_Application_Api<API: splitter_splitter_Api> {
    pub api: API,

    pub ghost instruct: SysPropStructSplit_Data_Model::StructXY,
    pub ghost xfield: i32,
    pub ghost yfield: i32
  }

  impl<API: splitter_splitter_Put_Api> splitter_splitter_Application_Api<API> {
    pub fn put_xfield(
      &mut self,
      value: i32)
      requires
        // guarantee xfield_range
        //   xfield lies in [-100, 100].
        (-100i32 <= value) &&
          (value <= 100i32),
      ensures
        old(self).instruct == self.instruct,
        self.xfield == value,
        old(self).yfield == self.yfield,
    {
      self.api.unverified_put_xfield(value);
      self.xfield = value;
    }
    pub fn put_yfield(
      &mut self,
      value: i32)
      requires
        // guarantee yfield_range
        //   yfield lies in [-100, 100].
        (-100i32 <= value) &&
          (value <= 100i32),
      ensures
        old(self).instruct == self.instruct,
        old(self).xfield == self.xfield,
        self.yfield == value,
    {
      self.api.unverified_put_yfield(value);
      self.yfield = value;
    }
  }

  impl<API: splitter_splitter_Get_Api> splitter_splitter_Application_Api<API> {
    pub fn get_instruct(&mut self) -> (res : SysPropStructSplit_Data_Model::StructXY)
      ensures
        old(self).instruct == self.instruct,
        res == self.instruct,
        old(self).xfield == self.xfield,
        old(self).yfield == self.yfield,
        // assume instruct_range
        //   Incoming struct fields lie in [-100, 100].
        (((-100i32 <= res.x) &&
          (res.x <= 100i32)) &&
          (-100i32 <= res.y)) &&
          (res.y <= 100i32),
    {
      self.api.unverified_get_instruct(&Ghost(self.instruct))
    }
  }

  pub struct splitter_splitter_Initialization_Api;
  impl splitter_splitter_Api for splitter_splitter_Initialization_Api {}
  impl splitter_splitter_Put_Api for splitter_splitter_Initialization_Api {}

  pub const fn init_api() -> splitter_splitter_Application_Api<splitter_splitter_Initialization_Api> {
    return splitter_splitter_Application_Api {
      api: splitter_splitter_Initialization_Api {},

      instruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 },
      xfield: 0,
      yfield: 0
    }
  }

  pub struct splitter_splitter_Compute_Api;
  impl splitter_splitter_Api for splitter_splitter_Compute_Api {}
  impl splitter_splitter_Put_Api for splitter_splitter_Compute_Api {}
  impl splitter_splitter_Get_Api for splitter_splitter_Compute_Api {}
  impl splitter_splitter_Full_Api for splitter_splitter_Compute_Api {}

  pub const fn compute_api() -> splitter_splitter_Application_Api<splitter_splitter_Compute_Api> {
    return splitter_splitter_Application_Api {
      api: splitter_splitter_Compute_Api {},

      instruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 },
      xfield: 0,
      yfield: 0
    }
  }

}