// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

use super::test_apis::*;

use crate::bridge::thermostat_thermostat_GUMBOX as GUMBOX;

pub enum HarnessResult {
  RejectedPrecondition,
  FailedPostcondition(TestCaseError),
  Passed,
}

/** Contract-based test harness for the initialize entry point
  */
pub fn testInitializeCB() -> HarnessResult
{
  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_thermostat_initialize();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let currentSetPoints = get_currentSetPoints();
  let lastCmd = get_lastCmd();
  let api_heat_control = get_heat_control();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::initialize_IEP_Post (currentSetPoints, lastCmd, api_heat_control) {
    return HarnessResult::FailedPostcondition(
      TestCaseError::Fail("Postcondition failed: incorrect output behavior".into())
    );
  }

  return HarnessResult::Passed
}

#[macro_export]
macro_rules!
testInitializeCB_macro {
  (
    $test_name: ident,
    config: $config:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(empty in ::proptest::strategy::Just(())) {
        match $crate::test::util::cb_apis::testInitializeCB() {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            unreachable!("This branch is infeasible")
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param api_desired_temp incoming event data port
  * @param api_temp_changed incoming event data port
  * @param api_current_temp incoming data port
  */
pub fn testComputeCB(
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_temp_changed: Option<Isolette_Data_Model::Temp>,
  api_current_temp: Isolette_Data_Model::Temp) -> HarnessResult
{
  // Initialize the app
  crate::thermostat_thermostat_initialize();

  // [SaveInLocal]: retrieve and save the current (input) values of GUMBO-declared local state variables as retrieved
  //                from the component state
  let In_currentSetPoints: Isolette_Data_Model::Set_Points = get_currentSetPoints();
  let In_lastCmd: Isolette_Data_Model::On_Off = get_lastCmd();

  // [CheckPre]: check/filter based on pre-condition.
  if !GUMBOX::compute_CEP_Pre (In_currentSetPoints, In_lastCmd, api_desired_temp, api_temp_changed, api_current_temp) {
    return HarnessResult::RejectedPrecondition;
  }

  // [PutInPorts]: Set values on the input ports
  put_desired_temp(api_desired_temp);
  put_temp_changed(api_temp_changed);
  put_current_temp(api_current_temp);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_thermostat_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let currentSetPoints = get_currentSetPoints();
  let lastCmd = get_lastCmd();
  let api_heat_control = get_heat_control();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_currentSetPoints, In_lastCmd, currentSetPoints, lastCmd, api_desired_temp, api_temp_changed, api_current_temp, api_heat_control) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCB_container(container: PreStateContainer) -> HarnessResult
{
  return testComputeCB(container.api_desired_temp, container.api_temp_changed, container.api_current_temp)
}

#[macro_export]
macro_rules!
testComputeCB_macro {
  (
    $test_name: ident,
    config: $config:expr,
    api_desired_temp: $api_desired_temp_strat:expr,
    api_temp_changed: $api_temp_changed_strat:expr,
    api_current_temp: $api_current_temp_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (api_desired_temp, api_temp_changed, api_current_temp)
            in ($api_desired_temp_strat, $api_temp_changed_strat, $api_current_temp_strat)
      ) {
        match$crate::test::util::cb_apis::testComputeCB(api_desired_temp, api_temp_changed, api_current_temp) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}

/** Contract-based test harness for the compute entry point
  *
  * @param In_currentSetPoints pre-state state variable
  * @param In_lastCmd pre-state state variable
  * @param api_desired_temp incoming event data port
  * @param api_temp_changed incoming event data port
  * @param api_current_temp incoming data port
  */
pub fn testComputeCBwGSV(
  In_currentSetPoints: Isolette_Data_Model::Set_Points,
  In_lastCmd: Isolette_Data_Model::On_Off,
  api_desired_temp: Option<Isolette_Data_Model::Set_Points>,
  api_temp_changed: Option<Isolette_Data_Model::Temp>,
  api_current_temp: Isolette_Data_Model::Temp) -> HarnessResult
{
  // Initialize the app
  crate::thermostat_thermostat_initialize();

  // [CheckPre]: check/filter based on pre-condition.
  if !GUMBOX::compute_CEP_Pre (In_currentSetPoints, In_lastCmd, api_desired_temp, api_temp_changed, api_current_temp) {
    return HarnessResult::RejectedPrecondition;
  }

  // [PutInPorts]: Set values on the input ports
  put_desired_temp(api_desired_temp);
  put_temp_changed(api_temp_changed);
  put_current_temp(api_current_temp);

  // [SetInStateVars]: set the pre-state values of state variables
  put_currentSetPoints(In_currentSetPoints);
  put_lastCmd(In_lastCmd);

  // [InvokeEntryPoint]: Invoke the entry point
  crate::thermostat_thermostat_timeTriggered();

  // [RetrieveOutState]: retrieve values of the output ports via get operations and GUMBO declared local state variable
  let currentSetPoints = get_currentSetPoints();
  let lastCmd = get_lastCmd();
  let api_heat_control = get_heat_control();

  // [CheckPost]: invoke the oracle function
  if !GUMBOX::compute_CEP_Post(In_currentSetPoints, In_lastCmd, currentSetPoints, lastCmd, api_desired_temp, api_temp_changed, api_current_temp, api_heat_control) {
    return HarnessResult::FailedPostcondition(TestCaseError::Fail("Postcondition failed: incorrect output behavior".into()));
  }

  return HarnessResult::Passed
}

/** Contract-based test harness for the compute entry point
  */
pub fn testComputeCBwGSV_container(container: PreStateContainer_wGSV) -> HarnessResult
{
  return testComputeCBwGSV(container.In_currentSetPoints, container.In_lastCmd, container.api_desired_temp, container.api_temp_changed, container.api_current_temp)
}

#[macro_export]
macro_rules!
testComputeCBwGSV_macro {
  (
    $test_name: ident,
    config: $config:expr,
    In_currentSetPoints: $In_currentSetPoints_strat:expr,
    In_lastCmd: $In_lastCmd_strat:expr,
    api_desired_temp: $api_desired_temp_strat:expr,
    api_temp_changed: $api_temp_changed_strat:expr,
    api_current_temp: $api_current_temp_strat:expr
  ) => {
    proptest!{
      #![proptest_config($config)]
      #[test]
      #[serial]
      fn $test_name(
        (In_currentSetPoints, In_lastCmd, api_desired_temp, api_temp_changed, api_current_temp)
            in ($In_currentSetPoints_strat, $In_lastCmd_strat, $api_desired_temp_strat, $api_temp_changed_strat, $api_current_temp_strat)
      ) {
        match $crate::test::util::cb_apis::testComputeCBwGSV(In_currentSetPoints, In_lastCmd, api_desired_temp, api_temp_changed, api_current_temp) {
          $crate::test::util::cb_apis::HarnessResult::RejectedPrecondition => {
            return Err(proptest::test_runner::TestCaseError::reject(
              "Precondition failed: invalid input combination",
            ))
          }
          $crate::test::util::cb_apis::HarnessResult::FailedPostcondition(e) => {
            return Err(e)
          }
          $crate::test::util::cb_apis::HarnessResult::Passed => { }
        }
      }
    }
  };
}
