// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_current_temp: Isolette_Data_Model::Temp,
  pub api_temp_changed: Option<u8>,
  pub api_desired_temp: Option<Isolette_Data_Model::Set_Points>
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_currentSetPoints: Isolette_Data_Model::Set_Points,
  pub In_lastCmd: Isolette_Data_Model::On_Off,
  pub api_current_temp: Isolette_Data_Model::Temp,
  pub api_temp_changed: Option<u8>,
  pub api_desired_temp: Option<Isolette_Data_Model::Set_Points>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_current_temp(container.api_current_temp);
  put_temp_changed(container.api_temp_changed);
  put_desired_temp(container.api_desired_temp);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_lastCmd(container.In_lastCmd);
  put_currentSetPoints(container.In_currentSetPoints);
  put_current_temp(container.api_current_temp);
  put_temp_changed(container.api_temp_changed);
  put_desired_temp(container.api_desired_temp);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(
  current_temp: Isolette_Data_Model::Temp,
  temp_changed: Option<u8>,
  desired_temp: Option<Isolette_Data_Model::Set_Points>)
{
  put_current_temp(current_temp);
  put_temp_changed(temp_changed);
  put_desired_temp(desired_temp);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_currentSetPoints: Isolette_Data_Model::Set_Points,
  In_lastCmd: Isolette_Data_Model::On_Off,
  current_temp: Isolette_Data_Model::Temp,
  temp_changed: Option<u8>,
  desired_temp: Option<Isolette_Data_Model::Set_Points>)
{
  put_lastCmd(In_lastCmd);
  put_currentSetPoints(In_currentSetPoints);
  put_current_temp(current_temp);
  put_temp_changed(temp_changed);
  put_desired_temp(desired_temp);
}

/// setter for IN DataPort
pub fn put_current_temp(value: Isolette_Data_Model::Temp)
{
  *extern_api::IN_current_temp.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// setter for IN EventPort
pub fn put_temp_changed(value: Option<u8>)
{
  *extern_api::IN_temp_changed.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// setter for IN EventDataPort
pub fn put_desired_temp(value: Option<Isolette_Data_Model::Set_Points>)
{
  *extern_api::IN_desired_temp.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for OUT EventDataPort
pub fn get_heat_control() -> Option<Isolette_Data_Model::On_Off>
{
  return extern_api::OUT_heat_control.lock().unwrap_or_else(|e| e.into_inner()).clone()
}

/// getter for GUMBO State Variable
pub fn get_currentSetPoints() -> Isolette_Data_Model::Set_Points
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.currentSetPoints,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_currentSetPoints(value: Isolette_Data_Model::Set_Points)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.currentSetPoints = value,
      None => panic!("The app is None")
    }
  }
}

/// getter for GUMBO State Variable
pub fn get_lastCmd() -> Isolette_Data_Model::On_Off
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.lastCmd,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_lastCmd(value: Isolette_Data_Model::On_Off)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.lastCmd = value,
      None => panic!("The app is None")
    }
  }
}
