#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun


bool heat_control_is_empty(void);
bool get_heat_control_poll(sb_event_counter_t *numDropped, Isolette_Data_Model_On_Off *data);
bool get_heat_control(Isolette_Data_Model_On_Off *data);
