#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if codegen is rerun

typedef
  enum {Onn, Off} Isolette_Data_Model_On_Off;

typedef struct Isolette_Data_Model_Temp {
  int32_t degrees;
} Isolette_Data_Model_Temp;

typedef struct Isolette_Data_Model_Set_Points {
  Isolette_Data_Model_Temp lower;
  Isolette_Data_Model_Temp upper;
} Isolette_Data_Model_Set_Points;
