// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_input: Option<SNG_Data_Model::Message>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_input(container.api_input);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(input: Option<SNG_Data_Model::Message>)
{
  put_input(input);
}

/// setter for IN EventDataPort
pub fn put_input(value: Option<SNG_Data_Model::Message>)
{
  *extern_api::IN_input.lock().unwrap_or_else(|e| e.into_inner()) = value
}
