// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait gen_gen_Api {}

  pub trait gen_gen_Put_Api: gen_gen_Api {
    #[verifier::external_body]
    fn unverified_put_outstruct(
      &mut self,
      value: SysPropStructSplit_Data_Model::StructXY)
    {
      extern_api::unsafe_put_outstruct(&value);
    }
  }

  pub trait gen_gen_Get_Api: gen_gen_Api {
  }

  pub trait gen_gen_Full_Api: gen_gen_Put_Api + gen_gen_Get_Api {}

  pub struct gen_gen_Application_Api<API: gen_gen_Api> {
    pub api: API,

    pub ghost outstruct: SysPropStructSplit_Data_Model::StructXY
  }

  impl<API: gen_gen_Put_Api> gen_gen_Application_Api<API> {
    pub fn put_outstruct(
      &mut self,
      value: SysPropStructSplit_Data_Model::StructXY)
      requires
        // guarantee outstruct_range
        //   Both fields of the generated struct lie in [-100, 100].
        (((-100i32 <= value.x) &&
          (value.x <= 100i32)) &&
          (-100i32 <= value.y)) &&
          (value.y <= 100i32),
      ensures
        self.outstruct == value,
    {
      self.api.unverified_put_outstruct(value);
      self.outstruct = value;
    }
  }

  impl<API: gen_gen_Get_Api> gen_gen_Application_Api<API> {
  }

  pub struct gen_gen_Initialization_Api;
  impl gen_gen_Api for gen_gen_Initialization_Api {}
  impl gen_gen_Put_Api for gen_gen_Initialization_Api {}

  pub const fn init_api() -> gen_gen_Application_Api<gen_gen_Initialization_Api> {
    return gen_gen_Application_Api {
      api: gen_gen_Initialization_Api {},

      outstruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 }
    }
  }

  pub struct gen_gen_Compute_Api;
  impl gen_gen_Api for gen_gen_Compute_Api {}
  impl gen_gen_Put_Api for gen_gen_Compute_Api {}
  impl gen_gen_Get_Api for gen_gen_Compute_Api {}
  impl gen_gen_Full_Api for gen_gen_Compute_Api {}

  pub const fn compute_api() -> gen_gen_Application_Api<gen_gen_Compute_Api> {
    return gen_gen_Application_Api {
      api: gen_gen_Compute_Api {},

      outstruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 }
    }
  }

}