// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on gen's outgoing data port outstruct
  *
  * guarantee outstruct_range
  *  Both fields of the generated struct lie in [-100, 100].
  */
pub fn I_Guar_outstruct(outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (-100i32 <= outstruct.x) &
    (outstruct.x <= 100i32) &
    (-100i32 <= outstruct.y) &
    (outstruct.y <= 100i32)
}

/** Initialize EntryPointContract
  *
  * guarantee init_outstruct
  *   The output data port must be initialized.
  * @param api_outstruct outgoing data port
  */
pub fn initialize_init_outstruct(api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (api_outstruct.x == 0i32) &
    (api_outstruct.y == 0i32)
}

/** IEP-Guar: Initialize Entrypoint for gen
  *
  * @param api_outstruct outgoing data port
  */
pub fn initialize_IEP_Guar(api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  initialize_init_outstruct(api_outstruct)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_outstruct outgoing data port
  */
pub fn initialize_IEP_Post(api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  // I-Guar-Guard: Integration constraints for gen's outgoing ports"
  I_Guar_outstruct(api_outstruct)&& 

  initialize_IEP_Guar(api_outstruct)
}

/** CEP-Post: Compute Entrypoint Post-Condition for gen
  *
  * @param api_outstruct outgoing data port
  */
pub fn compute_CEP_Post(api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  // I-Guar-Guard: Integration constraints for gen's outgoing ports
  let r0: bool = I_Guar_outstruct(api_outstruct);

  return r0;
}
