#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

typedef struct SysPropStructSplit_Data_Model_StructXY {
  int32_t x;
  int32_t y;
} SysPropStructSplit_Data_Model_StructXY;
