#include "decy_decy.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void decy_decy_initialize(void);
void decy_decy_notify(microkit_channel channel);
void decy_decy_timeTriggered(void);

volatile sb_queue_int32_t_1_t *inyfield_queue_1;
sb_queue_int32_t_1_Recv_t inyfield_recv_queue;
volatile sb_queue_int32_t_1_t *outyfield_queue_1;

#define PORT_FROM_MON 52

int32_t last_inyfield_payload;

bool get_inyfield(int32_t *data) {
  sb_event_counter_t numDropped;
  int32_t fresh_data;
  bool isFresh = sb_queue_int32_t_1_dequeue((sb_queue_int32_t_1_Recv_t *) &inyfield_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_inyfield_payload = fresh_data;
  }
  *data = last_inyfield_payload;
  return isFresh;
}

bool put_outyfield(const int32_t *data) {
  sb_queue_int32_t_1_enqueue((sb_queue_int32_t_1_t *) outyfield_queue_1, (int32_t *) data);

  return true;
}

void init(void) {
  sb_queue_int32_t_1_Recv_init(&inyfield_recv_queue, (sb_queue_int32_t_1_t *) inyfield_queue_1);

  sb_queue_int32_t_1_init((sb_queue_int32_t_1_t *) outyfield_queue_1);

  decy_decy_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      decy_decy_timeTriggered();
      break;
    default:
      decy_decy_notify(channel);
  }
}
