// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait decy_decy_Api {}

  pub trait decy_decy_Put_Api: decy_decy_Api {
    #[verifier::external_body]
    fn unverified_put_outyfield(
      &mut self,
      value: i32)
    {
      extern_api::unsafe_put_outyfield(&value);
    }
  }

  pub trait decy_decy_Get_Api: decy_decy_Api {
    #[verifier::external_body]
    fn unverified_get_inyfield(
      &mut self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_inyfield();
    }
  }

  pub trait decy_decy_Full_Api: decy_decy_Put_Api + decy_decy_Get_Api {}

  pub struct decy_decy_Application_Api<API: decy_decy_Api> {
    pub api: API,

    pub ghost inyfield: i32,
    pub ghost outyfield: i32
  }

  impl<API: decy_decy_Put_Api> decy_decy_Application_Api<API> {
    pub fn put_outyfield(
      &mut self,
      value: i32)
      ensures
        old(self).inyfield == self.inyfield,
        self.outyfield == value,
    {
      self.api.unverified_put_outyfield(value);
      self.outyfield = value;
    }
  }

  impl<API: decy_decy_Get_Api> decy_decy_Application_Api<API> {
    pub fn get_inyfield(&mut self) -> (res : i32)
      ensures
        old(self).inyfield == self.inyfield,
        res == self.inyfield,
        old(self).outyfield == self.outyfield,
    {
      self.api.unverified_get_inyfield(&Ghost(self.inyfield))
    }
  }

  pub struct decy_decy_Initialization_Api;
  impl decy_decy_Api for decy_decy_Initialization_Api {}
  impl decy_decy_Put_Api for decy_decy_Initialization_Api {}

  pub const fn init_api() -> decy_decy_Application_Api<decy_decy_Initialization_Api> {
    return decy_decy_Application_Api {
      api: decy_decy_Initialization_Api {},

      inyfield: 0,
      outyfield: 0
    }
  }

  pub struct decy_decy_Compute_Api;
  impl decy_decy_Api for decy_decy_Compute_Api {}
  impl decy_decy_Put_Api for decy_decy_Compute_Api {}
  impl decy_decy_Get_Api for decy_decy_Compute_Api {}
  impl decy_decy_Full_Api for decy_decy_Compute_Api {}

  pub const fn compute_api() -> decy_decy_Application_Api<decy_decy_Compute_Api> {
    return decy_decy_Application_Api {
      api: decy_decy_Compute_Api {},

      inyfield: 0,
      outyfield: 0
    }
  }

}