// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * assumes inyfield_bounded
  *   Underflow guard only: the input lies in a
  *   conservative [-1000, 1000] envelope so the decrement cannot underflow.
  * @param api_inyfield incoming data port
  */
pub fn compute_spec_inyfield_bounded_assume(api_inyfield: i32) -> bool
{
  (-1000i32 <= api_inyfield) &
    (api_inyfield <= 1000i32)
}

/** CEP-T-Assm: Top-level assume contracts for decy's compute entrypoint
  *
  * @param api_inyfield incoming data port
  */
pub fn compute_CEP_T_Assm(api_inyfield: i32) -> bool
{
  let r0: bool = compute_spec_inyfield_bounded_assume(api_inyfield);

  return r0;
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for decy
  *
  * @param api_inyfield incoming data port
  */
pub fn compute_CEP_Pre(api_inyfield: i32) -> bool
{
  // CEP-Assm: assume clauses of decy's compute entrypoint
  let r0: bool = compute_CEP_T_Assm(api_inyfield);

  return r0;
}

/** Compute Entrypoint Contract
  *
  * guarantee decy
  *   Output is the input decremented by one.
  * @param api_inyfield incoming data port
  * @param api_outyfield outgoing data port
  */
pub fn compute_spec_decy_guarantee(
  api_inyfield: i32,
  api_outyfield: i32) -> bool
{
  api_outyfield == api_inyfield - 1i32
}

/** CEP-T-Guar: Top-level guarantee contracts for decy's compute entrypoint
  *
  * @param api_inyfield incoming data port
  * @param api_outyfield outgoing data port
  */
pub fn compute_CEP_T_Guar(
  api_inyfield: i32,
  api_outyfield: i32) -> bool
{
  let r0: bool = compute_spec_decy_guarantee(api_inyfield, api_outyfield);

  return r0;
}

/** CEP-Post: Compute Entrypoint Post-Condition for decy
  *
  * @param api_inyfield incoming data port
  * @param api_outyfield outgoing data port
  */
pub fn compute_CEP_Post(
  api_inyfield: i32,
  api_outyfield: i32) -> bool
{
  // CEP-Guar: guarantee clauses of decy's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_inyfield, api_outyfield);

  return r0;
}
