#![cfg_attr(not(test), no_std)]

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#![allow(dead_code)]
#![allow(static_mut_refs)]
#![allow(unused_imports)]
#![allow(unused_macros)]
#![allow(unused_parens)]
#![allow(unused_unsafe)]
#![allow(unused_variables)]

// Do not edit this file as it will be overwritten if codegen is rerun

mod bridge;
mod component;
mod logging;

#[cfg(test)]
mod test;

use crate::bridge::cons_cons_api::{self as api, *};
use crate::component::cons_cons_app::*;
use data::*;

static mut app: Option<cons_cons> = None;
static mut init_api: cons_cons_Application_Api<cons_cons_Initialization_Api> = api::init_api();
static mut compute_api: cons_cons_Application_Api<cons_cons_Compute_Api> = api::compute_api();

#[no_mangle]
pub extern "C" fn cons_cons_initialize() {
  logging::init_logging();

  unsafe {
    #[cfg(test)]
    crate::bridge::extern_c_api::initialize_test_globals();

    let mut _app = cons_cons::new();
    _app.initialize(&mut init_api);
    app = Some(_app);
  }
}

#[no_mangle]
pub extern "C" fn cons_cons_timeTriggered() {
  unsafe {
    if let Some(_app) = app.as_mut() {
      _app.timeTriggered(&mut compute_api);
    } else {
      panic!("Unexpected: app is None");
    }
  }
}

#[no_mangle]
pub extern "C" fn cons_cons_notify(channel: microkit_channel) {
  unsafe {
    if let Some(_app) = app.as_mut() {
      _app.notify(channel);
    } else {
      panic!("Unexpected: app is None");
    }
  }
}

// Need a Panic handler in a no_std environment
#[panic_handler]
#[cfg(not(test))]
fn panic(info: &core::panic::PanicInfo) -> ! {
  log::error!("PANIC: {info:#?}");
  loop {}
}
