#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if codegen is rerun

typedef struct ProdCons_Message {
  int32_t payload;
  int32_t control_num;
} ProdCons_Message;
