// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Assm: Integration constraint on splitter's incoming data port instruct
  *
  * assume instruct_range
  *   Incoming struct fields lie in [-100, 100].
  */
pub fn I_Assm_instruct(instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (-100i32 <= instruct.x) &
    (instruct.x <= 100i32) &
    (-100i32 <= instruct.y) &
    (instruct.y <= 100i32)
}

/** I-Guar: Integration constraint on splitter's outgoing data port xfield
  *
  * guarantee xfield_range
  *  xfield lies in [-100, 100].
  */
pub fn I_Guar_xfield(xfield: i32) -> bool
{
  (-100i32 <= xfield) &
    (xfield <= 100i32)
}

/** I-Guar: Integration constraint on splitter's outgoing data port yfield
  *
  * guarantee yfield_range
  *  yfield lies in [-100, 100].
  */
pub fn I_Guar_yfield(yfield: i32) -> bool
{
  (-100i32 <= yfield) &
    (yfield <= 100i32)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_xfield outgoing data port
  * @param api_yfield outgoing data port
  */
pub fn initialize_IEP_Post(
  api_xfield: i32,
  api_yfield: i32) -> bool
{
  // I-Guar-Guard: Integration constraints for splitter's outgoing ports"
  I_Guar_xfield(api_xfield) &
  I_Guar_yfield(api_yfield)
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for splitter
  *
  * @param api_instruct incoming data port
  */
pub fn compute_CEP_Pre(api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  // I-Assm-Guard: Integration constraints for splitter's incoming ports
  let r0: bool = I_Assm_instruct(api_instruct);

  return r0;
}

/** Compute Entrypoint Contract
  *
  * guarantee split_x
  *   xfield equals the x field of the incoming struct.
  * @param api_instruct incoming data port
  * @param api_xfield outgoing data port
  */
pub fn compute_spec_split_x_guarantee(
  api_instruct: SysPropStructSplit_Data_Model::StructXY,
  api_xfield: i32) -> bool
{
  api_xfield == api_instruct.x
}

/** Compute Entrypoint Contract
  *
  * guarantee split_y
  *   yfield equals the y field of the incoming struct.
  * @param api_instruct incoming data port
  * @param api_yfield outgoing data port
  */
pub fn compute_spec_split_y_guarantee(
  api_instruct: SysPropStructSplit_Data_Model::StructXY,
  api_yfield: i32) -> bool
{
  api_yfield == api_instruct.y
}

/** CEP-T-Guar: Top-level guarantee contracts for splitter's compute entrypoint
  *
  * @param api_instruct incoming data port
  * @param api_xfield outgoing data port
  * @param api_yfield outgoing data port
  */
pub fn compute_CEP_T_Guar(
  api_instruct: SysPropStructSplit_Data_Model::StructXY,
  api_xfield: i32,
  api_yfield: i32) -> bool
{
  let r0: bool = compute_spec_split_x_guarantee(api_instruct, api_xfield);
  let r1: bool = compute_spec_split_y_guarantee(api_instruct, api_yfield);

  return r0 && r1;
}

/** CEP-Post: Compute Entrypoint Post-Condition for splitter
  *
  * @param api_instruct incoming data port
  * @param api_xfield outgoing data port
  * @param api_yfield outgoing data port
  */
pub fn compute_CEP_Post(
  api_instruct: SysPropStructSplit_Data_Model::StructXY,
  api_xfield: i32,
  api_yfield: i32) -> bool
{
  // I-Guar-Guard: Integration constraints for splitter's outgoing ports
  let r0: bool = I_Guar_xfield(api_xfield);
  let r1: bool = I_Guar_yfield(api_yfield);

  // CEP-Guar: guarantee clauses of splitter's compute entrypoint
  let r2: bool = compute_CEP_T_Guar(api_instruct, api_xfield, api_yfield);

  return r0 && r1 && r2;
}
