// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait merger_merger_Api {}

  pub trait merger_merger_Put_Api: merger_merger_Api {
    #[verifier::external_body]
    fn unverified_put_outstruct(
      &mut self,
      value: SysPropStructSplit_Data_Model::StructXY)
    {
      extern_api::unsafe_put_outstruct(&value);
    }
  }

  pub trait merger_merger_Get_Api: merger_merger_Api {
    #[verifier::external_body]
    fn unverified_get_inxfield(
      &mut self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_inxfield();
    }

    #[verifier::external_body]
    fn unverified_get_inyfield(
      &mut self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_inyfield();
    }
  }

  pub trait merger_merger_Full_Api: merger_merger_Put_Api + merger_merger_Get_Api {}

  pub struct merger_merger_Application_Api<API: merger_merger_Api> {
    pub api: API,

    pub ghost inxfield: i32,
    pub ghost inyfield: i32,
    pub ghost outstruct: SysPropStructSplit_Data_Model::StructXY
  }

  impl<API: merger_merger_Put_Api> merger_merger_Application_Api<API> {
    pub fn put_outstruct(
      &mut self,
      value: SysPropStructSplit_Data_Model::StructXY)
      ensures
        old(self).inxfield == self.inxfield,
        old(self).inyfield == self.inyfield,
        self.outstruct == value,
    {
      self.api.unverified_put_outstruct(value);
      self.outstruct = value;
    }
  }

  impl<API: merger_merger_Get_Api> merger_merger_Application_Api<API> {
    pub fn get_inxfield(&mut self) -> (res : i32)
      ensures
        old(self).inxfield == self.inxfield,
        res == self.inxfield,
        old(self).inyfield == self.inyfield,
        old(self).outstruct == self.outstruct,
    {
      self.api.unverified_get_inxfield(&Ghost(self.inxfield))
    }
    pub fn get_inyfield(&mut self) -> (res : i32)
      ensures
        old(self).inxfield == self.inxfield,
        old(self).inyfield == self.inyfield,
        res == self.inyfield,
        old(self).outstruct == self.outstruct,
    {
      self.api.unverified_get_inyfield(&Ghost(self.inyfield))
    }
  }

  pub struct merger_merger_Initialization_Api;
  impl merger_merger_Api for merger_merger_Initialization_Api {}
  impl merger_merger_Put_Api for merger_merger_Initialization_Api {}

  pub const fn init_api() -> merger_merger_Application_Api<merger_merger_Initialization_Api> {
    return merger_merger_Application_Api {
      api: merger_merger_Initialization_Api {},

      inxfield: 0,
      inyfield: 0,
      outstruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 }
    }
  }

  pub struct merger_merger_Compute_Api;
  impl merger_merger_Api for merger_merger_Compute_Api {}
  impl merger_merger_Put_Api for merger_merger_Compute_Api {}
  impl merger_merger_Get_Api for merger_merger_Compute_Api {}
  impl merger_merger_Full_Api for merger_merger_Compute_Api {}

  pub const fn compute_api() -> merger_merger_Application_Api<merger_merger_Compute_Api> {
    return merger_merger_Application_Api {
      api: merger_merger_Compute_Api {},

      inxfield: 0,
      inyfield: 0,
      outstruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 }
    }
  }

}