// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Compute Entrypoint Contract
  *
  * guarantee merge_x
  *   Output struct's x field equals the inxfield input.
  * @param api_inxfield incoming data port
  * @param api_outstruct outgoing data port
  */
pub fn compute_spec_merge_x_guarantee(
  api_inxfield: i32,
  api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  api_outstruct.x == api_inxfield
}

/** Compute Entrypoint Contract
  *
  * guarantee merge_y
  *   Output struct's y field equals the inyfield input.
  * @param api_inyfield incoming data port
  * @param api_outstruct outgoing data port
  */
pub fn compute_spec_merge_y_guarantee(
  api_inyfield: i32,
  api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  api_outstruct.y == api_inyfield
}

/** CEP-T-Guar: Top-level guarantee contracts for merger's compute entrypoint
  *
  * @param api_inxfield incoming data port
  * @param api_inyfield incoming data port
  * @param api_outstruct outgoing data port
  */
pub fn compute_CEP_T_Guar(
  api_inxfield: i32,
  api_inyfield: i32,
  api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  let r0: bool = compute_spec_merge_x_guarantee(api_inxfield, api_outstruct);
  let r1: bool = compute_spec_merge_y_guarantee(api_inyfield, api_outstruct);

  return r0 && r1;
}

/** CEP-Post: Compute Entrypoint Post-Condition for merger
  *
  * @param api_inxfield incoming data port
  * @param api_inyfield incoming data port
  * @param api_outstruct outgoing data port
  */
pub fn compute_CEP_Post(
  api_inxfield: i32,
  api_inyfield: i32,
  api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  // CEP-Guar: guarantee clauses of merger's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(api_inxfield, api_inyfield, api_outstruct);

  return r0;
}
