#pragma once

#include <printf.h>
#include <util.h>
#include <stdint.h>
#include <microkit.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun


bool put_output(const SNG_Data_Model_Message *data);
bool input_is_empty(void);
bool get_input_poll(sb_event_counter_t *numDropped, SNG_Data_Model_Message *data);
bool get_input(SNG_Data_Model_Message *data);
