// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait test_sender_test_sender_Api {}

  pub trait test_sender_test_sender_Put_Api: test_sender_test_sender_Api {
    #[verifier::external_body]
    fn unverified_put_output(
      &mut self,
      value: SNG_Data_Model::Message)
    {
      extern_api::unsafe_put_output(&value);
    }
  }

  pub trait test_sender_test_sender_Get_Api: test_sender_test_sender_Api {
  }

  pub trait test_sender_test_sender_Full_Api: test_sender_test_sender_Put_Api + test_sender_test_sender_Get_Api {}

  pub struct test_sender_test_sender_Application_Api<API: test_sender_test_sender_Api> {
    pub api: API,

    pub ghost output: Option<SNG_Data_Model::Message>
  }

  impl<API: test_sender_test_sender_Put_Api> test_sender_test_sender_Application_Api<API> {
    pub fn put_output(
      &mut self,
      value: SNG_Data_Model::Message)
      ensures
        self.output == Some(value),
    {
      self.api.unverified_put_output(value);
      self.output = Some(value);
    }
  }

  impl<API: test_sender_test_sender_Get_Api> test_sender_test_sender_Application_Api<API> {
  }

  pub struct test_sender_test_sender_Initialization_Api;
  impl test_sender_test_sender_Api for test_sender_test_sender_Initialization_Api {}
  impl test_sender_test_sender_Put_Api for test_sender_test_sender_Initialization_Api {}

  pub const fn init_api() -> test_sender_test_sender_Application_Api<test_sender_test_sender_Initialization_Api> {
    return test_sender_test_sender_Application_Api {
      api: test_sender_test_sender_Initialization_Api {},

      output: None
    }
  }

  pub struct test_sender_test_sender_Compute_Api;
  impl test_sender_test_sender_Api for test_sender_test_sender_Compute_Api {}
  impl test_sender_test_sender_Put_Api for test_sender_test_sender_Compute_Api {}
  impl test_sender_test_sender_Get_Api for test_sender_test_sender_Compute_Api {}
  impl test_sender_test_sender_Full_Api for test_sender_test_sender_Compute_Api {}

  pub const fn compute_api() -> test_sender_test_sender_Application_Api<test_sender_test_sender_Compute_Api> {
    return test_sender_test_sender_Application_Api {
      api: test_sender_test_sender_Compute_Api {},

      output: None
    }
  }
}