// This file will not be overwritten if HAMR codegen is rerun

//============================================================================
//  T e m p   S e n s o r  -- Thread Component
//
//  This Thread component implements a (simulated) air temperature sensor.
//  The "sensed" value is placed on the component's current_temp output data
//  port, and -- new in this EDP variant -- a temp_changed event data message
//  (carrying the new value) is emitted exactly when the sensed value changes.
//
//  There is no software application level input.  The component encapsulates
//  a hardware driver that fetches information from a simulated hardware
//  interface.  The simulation produces temperature values within a range
//  specified by constants declared in this file.
//
//  The behavior of the temperature simulation is as follows:
//    - the latest value of the simulated sensed temperature is stored in the
//      component state (HAMR-generated struct for the component)
//    - the simulated temperature is only updated every Nth activation of the
//      Compute Entry Point (N = activations_between_changes).  On the
//      activations in between, the sensed value is unchanged and NO
//      temp_changed event is emitted -- this makes "no trigger" frames
//      observable downstream (the Thermostat's control logic idles)
//    - when the simulation updates, a new simulated temperature value is
//      generated by incrementing or decrementing the latest temperature value
//    - a component state variable indicates the simulation temperature
//      trajectory (trending up (+1 value), or trending down (-1 value)
//    - if the simulated temperature reaches a declared upper or lower bound,
//      the trajectory is reversed.  This ensures the simulated temperature
//      value stays within a declared range.
//
//  Verus notes: the temp_range / temp_changed_range integration guarantees
//  from the model become `requires` clauses on the put_ API methods, so the
//  simulation arithmetic below is written with explicit range guards
//  (see clamp_to_sensed_range) that let Verus prove the sent values lie in
//  [sensed_temp_lower_bound, sensed_temp_upper_bound] and that the +/-1
//  updates cannot overflow.
//============================================================================

use data::*;
use data::Isolette_Data_Model::*;  // Add for easy access to data type names
use crate::bridge::temp_sensor_temp_sensor_api::*;
use vstd::prelude::*;

verus! {

  //-------------------------------------------
  //  Constants
  //-------------------------------------------

  // --- temp bounds ---
  //  ..Upper and lower bounds for sensed temperature
  pub const sensed_temp_lower_bound: i32 = 96;
  pub const sensed_temp_upper_bound: i32 = 103;

  // constants declared to support temp simulation (not publicly visible)
  const temp_trajectory_up: i32 = 1;
  const temp_trajectory_down: i32 = -1;

  // number of activations the sensed value is held before the simulation
  // produces a new value (so temp_changed events are NOT raised on every
  // dispatch -- some frames have no trigger)
  pub const activations_between_changes: i32 = 2;

  //-------------------------------------------
  //  Application State (as a struct)
  //-------------------------------------------

  pub struct temp_sensor_temp_sensor {
    // PLACEHOLDER MARKER STATE VARS

    //  ..Note: if GUMBO state variable declarations are declared,
    //   HAMR uses the marker above to weave autogenerated variable
    //   declarations into the code at the point of the marker.
    //   We recommend not deleting the marker.

    // The variables below are used for sensor simulation.
    // This also illustrates non-GUMBO declared state variables for a component
    pub latest_temp: i32,
    pub temp_trajectory: i32,
    pub activations_until_change: i32,
  }

  impl temp_sensor_temp_sensor {
    //-------------------------------------------
    //  Application Component Constructor
    //-------------------------------------------
    pub fn new() -> Self
    {
      Self {
        // PLACEHOLDER MARKER STATE VAR INIT

        // initialization of non-GUMBO declared state variables
        latest_temp: sensed_temp_lower_bound,
        temp_trajectory: temp_trajectory_up, // value will either be +1 or -1
        activations_until_change: activations_between_changes,
      }
    }

    //-------------------------------------------
    //  Initialize Entry Point
    //-------------------------------------------
    pub fn initialize<API: temp_sensor_temp_sensor_Put_Api> (
      &mut self,
      api: &mut temp_sensor_temp_sensor_Application_Api<API>)
      ensures
        // PLACEHOLDER MARKER INITIALIZATION ENSURES
    {
      log_info("initialize entrypoint invoked");

      self.latest_temp = sensed_temp_lower_bound;
      //  ...set the temperature trajectory to be increasing
      self.temp_trajectory = temp_trajectory_up;
      self.activations_until_change = activations_between_changes;

      // put the "sensed value" on the current_temp output data port
      // (output DATA ports must be initialized; the temp_changed event data
      //  port needs no initialization message, and semantically nothing has
      //  "changed" yet, so no event is emitted here)
      api.put_current_temp(Temp { degrees: self.latest_temp });
    }

    //-------------------------------------------
    //  Compute Entry Point
    //-------------------------------------------
    pub fn timeTriggered<API: temp_sensor_temp_sensor_Full_Api> (
      &mut self,
      api: &mut temp_sensor_temp_sensor_Application_Api<API>)
      requires
        // PLACEHOLDER MARKER TIME TRIGGERED REQUIRES
      ensures
        // PLACEHOLDER MARKER TIME TRIGGERED ENSURES
    {
      log_info("compute entrypoint invoked");

      if self.activations_until_change > 0 {
        // Case: holding the current sensed value -- no change, no event.
        self.activations_until_change = self.activations_until_change - 1;

        // refresh the current_temp data port with the (unchanged) value
        let reported: i32 = clamp_to_sensed_range(self.latest_temp);
        api.put_current_temp(Temp { degrees: reported });
        log_temp_simulation(reported, self.temp_trajectory, false);
      } else {
        // Case: ((mock read of temperature sensor))
        //   ..update simulation according to trajectory.
        //   The previous value is clamped into the sensed range first so that
        //   Verus can discharge the overflow and range obligations.
        let prev: i32 = clamp_to_sensed_range(self.latest_temp);
        let next: i32;
        if self.temp_trajectory >= 0 {
          if prev < sensed_temp_upper_bound { next = prev + 1; } else { next = sensed_temp_upper_bound; }
        } else {
          if prev > sensed_temp_lower_bound { next = prev - 1; } else { next = sensed_temp_lower_bound; }
        }

        //   ..reverse the simulation trajectory when temp reaches bounds
        if next >= sensed_temp_upper_bound {
          self.temp_trajectory = temp_trajectory_down;
        } else if next <= sensed_temp_lower_bound {
          self.temp_trajectory = temp_trajectory_up;
        }

        self.latest_temp = next;
        self.activations_until_change = activations_between_changes;

        // put the "sensed" value on the current_temp output data port
        api.put_current_temp(Temp { degrees: next });

        // announce the change on the temp_changed event data port -- exactly
        // when the sensed value actually differs from the previous value
        if next != prev {
          api.put_temp_changed(Temp { degrees: next });
        }
        log_temp_simulation(next, self.temp_trajectory, next != prev);
      }
    }

    //-------------------------------------------
    //  seL4 / Microkit Error Handling
    //-------------------------------------------
    pub fn notify(
      &mut self,
      channel: microkit_channel)
    {
      // this method is called when the monitor does not handle the passed in channel
      match channel {
        _ => {
          log_warn_channel(channel)
        }
      }
    }
  }

  //-------------------------------------------
  //  Helper Functions
  //-------------------------------------------

  // Clamp a value into the sensed temperature range.  The ensures clauses give
  // Verus what it needs to discharge the put_ API range requirements; at
  // runtime the simulation never actually leaves the range, so the second
  // ensures clause guarantees the clamp is the identity on simulated values.
  pub fn clamp_to_sensed_range(v: i32) -> (res: i32)
    ensures
      sensed_temp_lower_bound <= res && res <= sensed_temp_upper_bound,
      (sensed_temp_lower_bound <= v && v <= sensed_temp_upper_bound) ==> res == v,
  {
    if v > sensed_temp_upper_bound {
      sensed_temp_upper_bound
    } else if v < sensed_temp_lower_bound {
      sensed_temp_lower_bound
    } else {
      v
    }
  }

  //-------------------------------------------
  //  Logging Helper Functions
  //-------------------------------------------
  #[verifier::external_body]
  pub fn log_temp_simulation(latest_temp: i32, temp_trajectory: i32, changed: bool)
  {
     log::info!("Sensed Temp: {} (trajectory {}, changed: {})", latest_temp, temp_trajectory, changed);
  }

  #[verifier::external_body]
  pub fn log_info(msg: &str)
  {
    log::info!("{0}", msg);
  }

  #[verifier::external_body]
  pub fn log_warn_channel(channel: u32)
  {
    log::warn!("Unexpected channel: {0}", channel);
  }

  // PLACEHOLDER MARKER GUMBO METHODS

}
