#include "cons_cons.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void cons_cons_initialize(void);
void cons_cons_notify(microkit_channel channel);
void cons_cons_timeTriggered(void);

volatile sb_queue_ProdCons_Message_1_t *input_queue_1;
sb_queue_ProdCons_Message_1_Recv_t input_recv_queue;

#define PORT_FROM_MON 58

bool input_is_empty(void) {
  return sb_queue_ProdCons_Message_1_is_empty(&input_recv_queue);
}

bool get_input_poll(sb_event_counter_t *numDropped, ProdCons_Message *data) {
  return sb_queue_ProdCons_Message_1_dequeue((sb_queue_ProdCons_Message_1_Recv_t *) &input_recv_queue, numDropped, data);
}

bool get_input(ProdCons_Message *data) {
  sb_event_counter_t numDropped;
  return get_input_poll (&numDropped, data);
}

void init(void) {
  sb_queue_ProdCons_Message_1_Recv_init(&input_recv_queue, (sb_queue_ProdCons_Message_1_t *) input_queue_1);

  cons_cons_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      cons_cons_timeTriggered();
      break;
    default:
      cons_cons_notify(channel);
  }
}
