// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{

}

/// setter for component's incoming port values
pub fn put_concrete_inputs()
{

}

/// getter for OUT DataPort
pub fn get_desired_temp() -> Isolette_Data_Model::Set_Points
{
  return extern_api::OUT_desired_temp.lock().unwrap().expect("Not expecting None")
}
