// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property consume_range_loop_invariant -- Post-Pre VC: the END assertion implies the START assertion across hyperperiod boundaries.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::consume_range_loop_invariant::assertions::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[18]: Post-Pre -- END |- START (hyperperiod loop invariant) */
pub proof fn vc_post_pre(st: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_END(st),
  ensures
    sys_assert_consume_range_loop_invariant_START(st),
{}

} // verus!
