// Do not edit this file as it will be overwritten if codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_input(value: *mut SNG_Data_Model::Message) -> bool;
}

pub fn unsafe_get_input() -> Option<SNG_Data_Model::Message>
{
  unsafe {
    let value: *mut SNG_Data_Model::Message = &mut SNG_Data_Model::Message::default();
    if (get_input(value)) {
      return Some(*value);
    } else {
      return None;
    }
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_input: Mutex<Option<SNG_Data_Model::Message>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_input.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_input(value: *mut SNG_Data_Model::Message) -> bool
{
  unsafe {
    match *IN_input.lock().unwrap_or_else(|e| e.into_inner()) {
      Some(v) => {
        *value = v;
        return true;
      },
      None => return false,
    }
  }
}
