// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait test_receiver_test_receiver_Api {}

  pub trait test_receiver_test_receiver_Put_Api: test_receiver_test_receiver_Api {
  }

  pub trait test_receiver_test_receiver_Get_Api: test_receiver_test_receiver_Api {
    #[verifier::external_body]
    fn unverified_get_input(
      &mut self,
      value: &Ghost<Option<SNG_Data_Model::Message>>) -> (res : Option<SNG_Data_Model::Message>)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_input();
    }
  }

  pub trait test_receiver_test_receiver_Full_Api: test_receiver_test_receiver_Put_Api + test_receiver_test_receiver_Get_Api {}

  pub struct test_receiver_test_receiver_Application_Api<API: test_receiver_test_receiver_Api> {
    pub api: API,

    pub ghost input: Option<SNG_Data_Model::Message>
  }

  impl<API: test_receiver_test_receiver_Put_Api> test_receiver_test_receiver_Application_Api<API> {
  }

  impl<API: test_receiver_test_receiver_Get_Api> test_receiver_test_receiver_Application_Api<API> {
    pub fn get_input(&mut self) -> (res : Option<SNG_Data_Model::Message>)
      ensures
        old(self).input == self.input,
        res == self.input,
    {
      self.api.unverified_get_input(&Ghost(self.input))
    }
  }

  pub struct test_receiver_test_receiver_Initialization_Api;
  impl test_receiver_test_receiver_Api for test_receiver_test_receiver_Initialization_Api {}
  impl test_receiver_test_receiver_Put_Api for test_receiver_test_receiver_Initialization_Api {}

  pub const fn init_api() -> test_receiver_test_receiver_Application_Api<test_receiver_test_receiver_Initialization_Api> {
    return test_receiver_test_receiver_Application_Api {
      api: test_receiver_test_receiver_Initialization_Api {},

      input: None
    }
  }

  pub struct test_receiver_test_receiver_Compute_Api;
  impl test_receiver_test_receiver_Api for test_receiver_test_receiver_Compute_Api {}
  impl test_receiver_test_receiver_Put_Api for test_receiver_test_receiver_Compute_Api {}
  impl test_receiver_test_receiver_Get_Api for test_receiver_test_receiver_Compute_Api {}
  impl test_receiver_test_receiver_Full_Api for test_receiver_test_receiver_Compute_Api {}

  pub const fn compute_api() -> test_receiver_test_receiver_Application_Api<test_receiver_test_receiver_Compute_Api> {
    return test_receiver_test_receiver_Application_Api {
      api: test_receiver_test_receiver_Compute_Api {},

      input: None
    }
  }
}