// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Message {
    pub payload: i32,
    pub control_num: i32
  }

  impl Default for Message {
    fn default() -> Self
    {
      Self { payload: 0, control_num: 0 }
    }
  }
}