// Do not edit this file as it will be overwritten if codegen is rerun

include!("Message.rs");

/*
NOTE: the include!("xx.rs") inlines the file contents directly so a module for
xx is not created.  An alternative would be to do

pub mod xx.rs;
pub use xx::*;

however this would create a module out of xx.rs so to refer to the datatype
it contains you'd have to do something like "use data::xx::xx"
in lib.rs. A workaround is to rename the file, e.g. xx_STRUCT.rs but leave the
file contents unchanged.  Then in this file do

pub mod xx_STRUCT;
pub use xx_STRUCT::*;

then xx would be imported in lib.rs via "use data::ProdCons::*"
*/
