#include "temp_sensor_temp_sensor.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void temp_sensor_temp_sensor_initialize(void);
void temp_sensor_temp_sensor_notify(microkit_channel channel);
void temp_sensor_temp_sensor_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_Temp_1_t *current_temp_queue_1;

#define PORT_FROM_MON 60

bool put_current_temp(const Isolette_Data_Model_Temp *data) {
  sb_queue_Isolette_Data_Model_Temp_1_enqueue((sb_queue_Isolette_Data_Model_Temp_1_t *) current_temp_queue_1, (Isolette_Data_Model_Temp *) data);

  return true;
}

void init(void) {
  sb_queue_Isolette_Data_Model_Temp_1_init((sb_queue_Isolette_Data_Model_Temp_1_t *) current_temp_queue_1);

  temp_sensor_temp_sensor_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      temp_sensor_temp_sensor_timeTriggered();
      break;
    default:
      temp_sensor_temp_sensor_notify(channel);
  }
}
