// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_display_temp: Isolette_Data_Model::Temp
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_display_temp(container.api_display_temp);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(display_temp: Isolette_Data_Model::Temp)
{
  put_display_temp(display_temp);
}

/// getter for OUT DataPort
pub fn get_desired_temp() -> Isolette_Data_Model::Set_Points
{
  return extern_api::OUT_desired_temp.lock().unwrap().expect("Not expecting None")
}

/// setter for IN DataPort
pub fn put_display_temp(value: Isolette_Data_Model::Temp)
{
  *extern_api::IN_display_temp.lock().unwrap() = Some(value)
}
