// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn put_outstruct(value: *mut SysPropStructSplit_Data_Model::StructXY) -> bool;
}

pub fn unsafe_put_outstruct(value: &SysPropStructSplit_Data_Model::StructXY) -> bool
{
  unsafe {
    return put_outstruct(value as *const SysPropStructSplit_Data_Model::StructXY as *mut SysPropStructSplit_Data_Model::StructXY);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref OUT_outstruct: Mutex<Option<SysPropStructSplit_Data_Model::StructXY>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *OUT_outstruct.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn put_outstruct(value: *mut SysPropStructSplit_Data_Model::StructXY) -> bool
{
  unsafe {
    *OUT_outstruct.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
