// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{

}

/// setter for component's incoming port values
pub fn put_concrete_inputs()
{

}

/// getter for OUT EventDataPort
pub fn get_output() -> Option<SNG_Data_Model::Message>
{
  return extern_api::OUT_output.lock().unwrap_or_else(|e| e.into_inner()).clone()
}
