// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait msg_filter_msg_filter_Api {}

  pub trait msg_filter_msg_filter_Put_Api: msg_filter_msg_filter_Api {
    #[verifier::external_body]
    fn unverified_put_output(
      &mut self,
      value: SNG_Data_Model::Message)
    {
      extern_api::unsafe_put_output(&value);
    }
  }

  pub trait msg_filter_msg_filter_Get_Api: msg_filter_msg_filter_Api {
    #[verifier::external_body]
    fn unverified_get_input(
      &mut self,
      value: &Ghost<Option<SNG_Data_Model::Message>>) -> (res : Option<SNG_Data_Model::Message>)
      ensures
        res == value@,
        (res.is_none() ||
          // assume No_Critical_Input
          GumboLib::allowedSecurityLevel_spec(res.unwrap())),
    {
      return extern_api::unsafe_get_input();
    }
  }

  pub trait msg_filter_msg_filter_Full_Api: msg_filter_msg_filter_Put_Api + msg_filter_msg_filter_Get_Api {}

  pub struct msg_filter_msg_filter_Application_Api<API: msg_filter_msg_filter_Api> {
    pub api: API,

    pub ghost input: Option<SNG_Data_Model::Message>,
    pub ghost output: Option<SNG_Data_Model::Message>
  }

  impl<API: msg_filter_msg_filter_Put_Api> msg_filter_msg_filter_Application_Api<API> {
    pub fn put_output(
      &mut self,
      value: SNG_Data_Model::Message)
      ensures
        old(self).input == self.input,
        self.output == Some(value),
    {
      self.api.unverified_put_output(value);
      self.output = Some(value);
    }
  }

  impl<API: msg_filter_msg_filter_Get_Api> msg_filter_msg_filter_Application_Api<API> {
    pub fn get_input(&mut self) -> (res : Option<SNG_Data_Model::Message>)
      ensures
        old(self).input == self.input,
        res == self.input,
        old(self).output == self.output,
        (res.is_none() ||
          // assume No_Critical_Input
          GumboLib::allowedSecurityLevel_spec(res.unwrap())),
    {
      self.api.unverified_get_input(&Ghost(self.input))
    }
  }

  pub struct msg_filter_msg_filter_Initialization_Api;
  impl msg_filter_msg_filter_Api for msg_filter_msg_filter_Initialization_Api {}
  impl msg_filter_msg_filter_Put_Api for msg_filter_msg_filter_Initialization_Api {}

  pub const fn init_api() -> msg_filter_msg_filter_Application_Api<msg_filter_msg_filter_Initialization_Api> {
    return msg_filter_msg_filter_Application_Api {
      api: msg_filter_msg_filter_Initialization_Api {},

      input: None,
      output: None
    }
  }

  pub struct msg_filter_msg_filter_Compute_Api;
  impl msg_filter_msg_filter_Api for msg_filter_msg_filter_Compute_Api {}
  impl msg_filter_msg_filter_Put_Api for msg_filter_msg_filter_Compute_Api {}
  impl msg_filter_msg_filter_Get_Api for msg_filter_msg_filter_Compute_Api {}
  impl msg_filter_msg_filter_Full_Api for msg_filter_msg_filter_Compute_Api {}

  pub const fn compute_api() -> msg_filter_msg_filter_Application_Api<msg_filter_msg_filter_Compute_Api> {
    return msg_filter_msg_filter_Application_Api {
      api: msg_filter_msg_filter_Compute_Api {},

      input: None,
      output: None
    }
  }
}