// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_inxfield: i32
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_inxfield(container.api_inxfield);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(inxfield: i32)
{
  put_inxfield(inxfield);
}

/// setter for IN DataPort
pub fn put_inxfield(value: i32)
{
  *extern_api::IN_inxfield.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// getter for OUT DataPort
pub fn get_outxfield() -> i32
{
  return extern_api::OUT_outxfield.lock().unwrap_or_else(|e| e.into_inner()).expect("Not expecting None")
}
