// #Sireum

package TempControlMixedUI.TempSensor

import org.sireum._
import TempControlMixedUI._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

object Temperature_i {
  def example(): TempSensor.Temperature_i = {
    return TempSensor.Temperature_i(
      degrees = Base_Types.Float_32_example(),
      unit = TempSensor.TempUnit.byOrdinal(0).get)
  }
}

@datatype class Temperature_i(
  val degrees: F32,
  val unit: TempSensor.TempUnit.Type) {
}

object Temperature_i_Payload {
  def example(): Temperature_i_Payload = {
    return Temperature_i_Payload(TempSensor.Temperature_i.example())
  }
}

@datatype class Temperature_i_Payload(value: TempSensor.Temperature_i) extends art.DataContent
