// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_heat_control: Isolette_Data_Model::On_Off
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_heat_control(container.api_heat_control);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(heat_control: Isolette_Data_Model::On_Off)
{
  put_heat_control(heat_control);
}

/// setter for IN DataPort
pub fn put_heat_control(value: Isolette_Data_Model::On_Off)
{
  *extern_api::IN_heat_control.lock().unwrap() = Some(value)
}
