// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on prod's outgoing event data port output
  *
  * guarantee Payload_Range
  */
pub fn I_Guar_output(output: ProdCons::Message) -> bool
{
  (0i32 <= output.payload) &
    (output.payload <= 90i32)
}

/** I-Guar: Integration constraint on prod's outgoing event data port output
  *
  * guarantee Payload_Range
  */
pub fn I_Guar_Guard_output(output: Option<ProdCons::Message>) -> bool
{
  implies!(
    output.is_some(),
    I_Guar_output(output.unwrap())
  )
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_output outgoing event data port
  */
pub fn initialize_IEP_Post(api_output: Option<ProdCons::Message>) -> bool
{
  // I-Guar-Guard: Integration constraints for prod's outgoing ports"
  I_Guar_Guard_output(api_output)
}

/** CEP-Post: Compute Entrypoint Post-Condition for prod
  *
  * @param api_output outgoing event data port
  */
pub fn compute_CEP_Post(api_output: Option<ProdCons::Message>) -> bool
{
  // I-Guar-Guard: Integration constraints for prod's outgoing ports
  let r0: bool = I_Guar_Guard_output(api_output);

  return r0;
}
