// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {
  pub trait prod_prod_Api {}

  pub trait prod_prod_Put_Api: prod_prod_Api {
    #[verifier::external_body]
    fn unverified_put_output(
      &mut self,
      value: ProdCons::Message)
    {
      extern_api::unsafe_put_output(&value);
    }
  }

  pub trait prod_prod_Get_Api: prod_prod_Api {
  }

  pub trait prod_prod_Full_Api: prod_prod_Put_Api + prod_prod_Get_Api {}

  pub struct prod_prod_Application_Api<API: prod_prod_Api> {
    pub api: API,

    pub ghost output: Option<ProdCons::Message>
  }

  impl<API: prod_prod_Put_Api> prod_prod_Application_Api<API> {
    pub fn put_output(
      &mut self,
      value: ProdCons::Message)
      requires
        // guarantee Payload_Range
        (0i32 <= value.payload) &&
          (value.payload <= 90i32),
      ensures
        self.output == Some(value),
    {
      self.api.unverified_put_output(value);
      self.output = Some(value);
    }
  }

  impl<API: prod_prod_Get_Api> prod_prod_Application_Api<API> {
  }

  pub struct prod_prod_Initialization_Api;
  impl prod_prod_Api for prod_prod_Initialization_Api {}
  impl prod_prod_Put_Api for prod_prod_Initialization_Api {}

  pub const fn init_api() -> prod_prod_Application_Api<prod_prod_Initialization_Api> {
    return prod_prod_Application_Api {
      api: prod_prod_Initialization_Api {},

      output: None
    }
  }

  pub struct prod_prod_Compute_Api;
  impl prod_prod_Api for prod_prod_Compute_Api {}
  impl prod_prod_Put_Api for prod_prod_Compute_Api {}
  impl prod_prod_Get_Api for prod_prod_Compute_Api {}
  impl prod_prod_Full_Api for prod_prod_Compute_Api {}

  pub const fn compute_api() -> prod_prod_Application_Api<prod_prod_Compute_Api> {
    return prod_prod_Application_Api {
      api: prod_prod_Compute_Api {},

      output: None
    }
  }
}