// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_instruct: SysPropStructSplit_Data_Model::StructXY
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_instruct(container.api_instruct);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(instruct: SysPropStructSplit_Data_Model::StructXY)
{
  put_instruct(instruct);
}

/// setter for IN DataPort
pub fn put_instruct(value: SysPropStructSplit_Data_Model::StructXY)
{
  *extern_api::IN_instruct.lock().unwrap_or_else(|e| e.into_inner()) = Some(value)
}

/// getter for OUT DataPort
pub fn get_xfield() -> i32
{
  return extern_api::OUT_xfield.lock().unwrap_or_else(|e| e.into_inner()).expect("Not expecting None")
}

/// getter for OUT DataPort
pub fn get_yfield() -> i32
{
  return extern_api::OUT_yfield.lock().unwrap_or_else(|e| e.into_inner()).expect("Not expecting None")
}
