#pragma once

#include <stdbool.h>
#include <stdint.h>

// Do not edit this file as it will be overwritten if codegen is rerun

typedef
  enum {Public, Restricted, Critical} SNG_Data_Model_SecurityLevel;

typedef struct SNG_Data_Model_Message {
  int32_t payload;
  SNG_Data_Model_SecurityLevel security_level;
} SNG_Data_Model_Message;
