#pragma once

// Do not edit this file as it will be overwritten if codegen is rerun

#include <sb_aadl_types.h>
#include <sb_queue_SNG_Data_Model_Message_1.h>
#include <sb_queue_SNG_Data_Model_Message_1.h>
#include <sb_queue_SNG_Data_Model_Message_1.h>
