# Do not edit this file as it will be overwritten if HAMR codegen is rerun

MICROKIT_TOOL ?= $(MICROKIT_SDK)/bin/microkit

CFLAGS := -mcpu=$(CPU) \
	-mstrict-align \
	-ffreestanding \
	-nostdlib \
	-g3 \
	-O3 \
	-Wall -Wno-unused-function -Werror -Wno-unused-command-line-argument \
	-I$(MICROKIT_BOARD_DIR)/include \
	-target $(TARGET)

LDFLAGS := -L$(MICROKIT_BOARD_DIR)/lib
LIBS := --start-group -lmicrokit -Tmicrokit.ld --end-group

MSD ?= microkit.system

IMAGES := prod_prod.elf prod_prod_MON.elf cons_cons.elf cons_cons_MON.elf pacer.elf
IMAGE_FILE = loader.img
REPORT_FILE = report.txt

UTIL_OBJS = printf.o util.o

TYPES_DIR = $(TOP_DIR)/types
TYPE_OBJS := $(TOP_DIR)/build/sb_queue_ProdCons_Message_1.o

# exporting TOP_TYPES_INCLUDE in case other makefiles need it
export TOP_TYPES_INCLUDE = -I$(TYPES_DIR)/include

TOP_INCLUDE = $(TOP_TYPES_INCLUDE) -I$(TOP_DIR)/util/include

all: $(IMAGE_FILE)
	CHECK_FLAGS_BOARD_MD5:=.board_cflags-$(shell echo -- ${CFLAGS} ${MICROKIT_BOARD} ${MICROKIT_CONFIG}| shasum | sed 's/ *-//')

${CHECK_FLAGS_BOARD_MD5}:
	-rm -f .board_cflags-*
	touch $@

%.o: ${TOP_DIR}/util/src/%.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_DIR)/util/include

$(TOP_DIR)/build/sb_queue_ProdCons_Message_1.o: $(TOP_DIR)/types/src/sb_queue_ProdCons_Message_1.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE)


# monitor
prod_prod_MON.o: $(TOP_DIR)/components/prod_prod/src/prod_prod_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/prod_prod/include

# user code
prod_prod_rust:
	make -C ${CRATES_DIR}/prod_prod $(RUST_MAKE_TARGET)

prod_prod.o: $(TOP_DIR)/components/prod_prod/src/prod_prod.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/prod_prod/include

# monitor
cons_cons_MON.o: $(TOP_DIR)/components/cons_cons/src/cons_cons_MON.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cons_cons/include

# user code
cons_cons_rust:
	make -C ${CRATES_DIR}/cons_cons $(RUST_MAKE_TARGET)

cons_cons.o: $(TOP_DIR)/components/cons_cons/src/cons_cons.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ $(TOP_INCLUDE) -I$(TOP_DIR)/components/cons_cons/include

pacer.o: $(TOP_DIR)/components/pacer/src/pacer.c Makefile
	$(CC) -c $(CFLAGS) $< -o $@ -I$(TOP_INCLUDE)

prod_prod_MON.elf: prod_prod_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

prod_prod.elf: $(UTIL_OBJS) $(TYPE_OBJS) prod_prod_rust prod_prod.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/prod_prod/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lprod_prod -o $@

cons_cons_MON.elf: cons_cons_MON.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

cons_cons.elf: $(UTIL_OBJS) $(TYPE_OBJS) cons_cons_rust cons_cons.o
	$(LD) $(LDFLAGS) -L ${CRATES_DIR}/cons_cons/target/aarch64-unknown-none/release $(filter %.o, $^) $(LIBS) -lcons_cons -o $@

pacer.elf: $(UTIL_OBJS) $(TYPE_OBJS) pacer.o
	$(LD) $(LDFLAGS) $^ $(LIBS) -o $@

$(IMAGE_FILE): $(IMAGES) $(TOP_DIR)/$(MSD)
	xmllint --xinclude $(TOP_DIR)/$(MSD) | awk 'FNR==1{print; print "<!--"; print "  DO NOT EDIT: This file is generated by merging"; print "    $(TOP_DIR)/$(MSD)"; print "  and its xi:included files."; print "  Modify the source files and run make instead."; print "-->"; next}1' > $(TOP_BUILD_DIR)/$(MSD).merged
	$(MICROKIT_TOOL) $(TOP_BUILD_DIR)/$(MSD).merged --search-path $(TOP_BUILD_DIR) --board $(MICROKIT_BOARD) --config $(MICROKIT_CONFIG) -o $(IMAGE_FILE) -r $(REPORT_FILE)


qemu:
	$(QEMU) -machine virt,virtualization=on \
			-cpu cortex-a53 \
			-serial mon:stdio \
			-device loader,file=$(IMAGE_FILE),addr=0x70000000,cpu-num=0 \
			-m size=2G \
			-nographic

clean::
	rm -f *.o

test:: 
	make -C ${CRATES_DIR}/prod_prod test
	make -C ${CRATES_DIR}/cons_cons test

clean:: 
	make -C ${CRATES_DIR}/prod_prod clean
	make -C ${CRATES_DIR}/cons_cons clean

verus: 
	make -C ${CRATES_DIR}/prod_prod verus
	make -C ${CRATES_DIR}/cons_cons verus
