// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait consume_consume_Api {}

  pub trait consume_consume_Put_Api: consume_consume_Api {
  }

  pub trait consume_consume_Get_Api: consume_consume_Api {
    #[verifier::external_body]
    fn unverified_get_instruct(
      &mut self,
      value: &Ghost<SysPropStructSplit_Data_Model::StructXY>) -> (res : SysPropStructSplit_Data_Model::StructXY)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_instruct();
    }
  }

  pub trait consume_consume_Full_Api: consume_consume_Put_Api + consume_consume_Get_Api {}

  pub struct consume_consume_Application_Api<API: consume_consume_Api> {
    pub api: API,

    pub ghost instruct: SysPropStructSplit_Data_Model::StructXY
  }

  impl<API: consume_consume_Put_Api> consume_consume_Application_Api<API> {
  }

  impl<API: consume_consume_Get_Api> consume_consume_Application_Api<API> {
    pub fn get_instruct(&mut self) -> (res : SysPropStructSplit_Data_Model::StructXY)
      ensures
        old(self).instruct == self.instruct,
        res == self.instruct,
    {
      self.api.unverified_get_instruct(&Ghost(self.instruct))
    }
  }

  pub struct consume_consume_Initialization_Api;
  impl consume_consume_Api for consume_consume_Initialization_Api {}
  impl consume_consume_Put_Api for consume_consume_Initialization_Api {}

  pub const fn init_api() -> consume_consume_Application_Api<consume_consume_Initialization_Api> {
    return consume_consume_Application_Api {
      api: consume_consume_Initialization_Api {},

      instruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 }
    }
  }

  pub struct consume_consume_Compute_Api;
  impl consume_consume_Api for consume_consume_Compute_Api {}
  impl consume_consume_Put_Api for consume_consume_Compute_Api {}
  impl consume_consume_Get_Api for consume_consume_Compute_Api {}
  impl consume_consume_Full_Api for consume_consume_Compute_Api {}

  pub const fn compute_api() -> consume_consume_Application_Api<consume_consume_Compute_Api> {
    return consume_consume_Application_Api {
      api: consume_consume_Compute_Api {},

      instruct: SysPropStructSplit_Data_Model::StructXY { x: 0, y: 0 }
    }
  }

}