// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** Initialize EntryPointContract
  *
  * guarantee init_last_x
  *   The state variable starts at zero.
  * @param last_x post-state state variable
  */
pub fn initialize_init_last_x(last_x: i32) -> bool
{
  last_x == 0i32
}

/** IEP-Guar: Initialize Entrypoint for consume
  *
  * @param last_x post-state state variable
  */
pub fn initialize_IEP_Guar(last_x: i32) -> bool
{
  initialize_init_last_x(last_x)
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param last_x post-state state variable
  */
pub fn initialize_IEP_Post(last_x: i32) -> bool
{
  initialize_IEP_Guar(last_x)
}

/** Compute Entrypoint Contract
  *
  * assumes instruct_range
  *   Incoming struct fields lie in [-200, 200].
  * @param api_instruct incoming data port
  */
pub fn compute_spec_instruct_range_assume(api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (-200i32 <= api_instruct.x) &
    (api_instruct.x <= 200i32) &
    (-200i32 <= api_instruct.y) &
    (api_instruct.y <= 200i32)
}

/** CEP-T-Assm: Top-level assume contracts for consume's compute entrypoint
  *
  * @param api_instruct incoming data port
  */
pub fn compute_CEP_T_Assm(api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  let r0: bool = compute_spec_instruct_range_assume(api_instruct);

  return r0;
}

/** CEP-Pre: Compute Entrypoint Pre-Condition for consume
  *
  * @param In_last_x pre-state state variable
  * @param api_instruct incoming data port
  */
pub fn compute_CEP_Pre(
  In_last_x: i32,
  api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  // CEP-Assm: assume clauses of consume's compute entrypoint
  let r0: bool = compute_CEP_T_Assm(api_instruct);

  return r0;
}

/** Compute Entrypoint Contract
  *
  * guarantee track_x
  *   last_x records the x field of the most recently consumed struct.
  * @param last_x post-state state variable
  * @param api_instruct incoming data port
  */
pub fn compute_spec_track_x_guarantee(
  last_x: i32,
  api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  last_x == api_instruct.x
}

/** CEP-T-Guar: Top-level guarantee contracts for consume's compute entrypoint
  *
  * @param last_x post-state state variable
  * @param api_instruct incoming data port
  */
pub fn compute_CEP_T_Guar(
  last_x: i32,
  api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  let r0: bool = compute_spec_track_x_guarantee(last_x, api_instruct);

  return r0;
}

/** CEP-Post: Compute Entrypoint Post-Condition for consume
  *
  * @param In_last_x pre-state state variable
  * @param last_x post-state state variable
  * @param api_instruct incoming data port
  */
pub fn compute_CEP_Post(
  In_last_x: i32,
  last_x: i32,
  api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  // CEP-Guar: guarantee clauses of consume's compute entrypoint
  let r0: bool = compute_CEP_T_Guar(last_x, api_instruct);

  return r0;
}
