// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Uninterpreted component action abstractions, used ONLY by the
//! Commutativity VCs. Verus proves those VCs for ALL interpretations of
//! the action fns; the real component behaviors are one interpretation
//! (components only write their declared out ports/state, and outputs
//! depend only on the read scope), so a discharged Commutativity VC
//! establishes the Isabelle `execIndependent` obligation.

#![allow(non_snake_case)]
#![allow(unused_variables)]

use data::*;
use vstd::prelude::*;

use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

// -- StructSplit_System_Instance.gen.gen --

pub uninterp spec fn gen_action_outstruct(outstruct: SysPropStructSplit_Data_Model::StructXY) -> SysPropStructSplit_Data_Model::StructXY;

/** "GEN fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn gen_fire(pre: SystemState, post: SystemState) -> bool
{
  post.gen_out == gen_action_outstruct(pre.gen_out)
  && gen_global_write_frame(pre, post)
}

// -- StructSplit_System_Instance.splitter.splitter --

pub uninterp spec fn split_stage_action_xfield(instruct: SysPropStructSplit_Data_Model::StructXY, xfield: i32, yfield: i32) -> i32;
pub uninterp spec fn split_stage_action_yfield(instruct: SysPropStructSplit_Data_Model::StructXY, xfield: i32, yfield: i32) -> i32;

/** "SPLIT_STAGE fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn split_stage_fire(pre: SystemState, post: SystemState) -> bool
{
  post.x0 == split_stage_action_xfield(pre.gen_out, pre.x0, pre.y0)
  && post.y0 == split_stage_action_yfield(pre.gen_out, pre.x0, pre.y0)
  && split_stage_global_write_frame(pre, post)
}

// -- StructSplit_System_Instance.incx.incx --

pub uninterp spec fn incx_action_outxfield(inxfield: i32, outxfield: i32) -> i32;

/** "INCX fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn incx_fire(pre: SystemState, post: SystemState) -> bool
{
  post.x1 == incx_action_outxfield(pre.x0, pre.x1)
  && incx_global_write_frame(pre, post)
}

// -- StructSplit_System_Instance.clampx.clampx --

pub uninterp spec fn clampx_action_outxfield(inxfield: i32, outxfield: i32) -> i32;

/** "CLAMPX fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn clampx_fire(pre: SystemState, post: SystemState) -> bool
{
  post.x2 == clampx_action_outxfield(pre.x1, pre.x2)
  && clampx_global_write_frame(pre, post)
}

// -- StructSplit_System_Instance.decy.decy --

pub uninterp spec fn decy_action_outyfield(inyfield: i32, outyfield: i32) -> i32;

/** "DECY fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn decy_fire(pre: SystemState, post: SystemState) -> bool
{
  post.y1 == decy_action_outyfield(pre.y0, pre.y1)
  && decy_global_write_frame(pre, post)
}

// -- StructSplit_System_Instance.merger.merger --

pub uninterp spec fn merge_stage_action_outstruct(inxfield: i32, inyfield: i32, outstruct: SysPropStructSplit_Data_Model::StructXY) -> SysPropStructSplit_Data_Model::StructXY;

/** "MERGE_STAGE fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn merge_stage_fire(pre: SystemState, post: SystemState) -> bool
{
  post.merged == merge_stage_action_outstruct(pre.x2, pre.y1, pre.merged)
  && merge_stage_global_write_frame(pre, post)
}

// -- StructSplit_System_Instance.consume.consume --

pub uninterp spec fn consume_action_last_x(last_x: i32, instruct: SysPropStructSplit_Data_Model::StructXY) -> i32;

/** "CONSUME fires": every written field is determined by the read scope;
  * everything else is framed.
  */
pub open spec fn consume_fire(pre: SystemState, post: SystemState) -> bool
{
  post.consume_last_x == consume_action_last_x(pre.consume_last_x, pre.merged)
  && consume_global_write_frame(pre, post)
}

} // verus!
