// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! System-level GUMBO functions (e.g. sysProp_*) called by the
//! properties' place-assertion spec functions.

#![allow(non_snake_case)]

use data::*;
use vstd::prelude::*;

use crate::system_state::SystemState;

verus! {

pub open spec fn inRange100(v: i32) -> bool
{
  (-100i32 <= v) &&
    (v <= 100i32)
}

pub open spec fn inConsumeRange(s: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (((-200i32 <= s.x) &&
    (s.x <= 200i32)) &&
    (-200i32 <= s.y)) &&
    (s.y <= 200i32)
}

pub open spec fn inRange200(v: i32) -> bool
{
  (-200i32 <= v) &&
    (v <= 200i32)
}

pub open spec fn mergedReflectsGen(
  m: SysPropStructSplit_Data_Model::StructXY,
  g: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (((g.x < 100i32) ==>
    (m.x == g.x + 1i32)) &&
    ((g.x == 100i32) ==>
      (m.x == 100i32))) &&
    (m.y == g.y - 1i32)
}

pub open spec fn yStaysBelowX(
  m: SysPropStructSplit_Data_Model::StructXY,
  g: SysPropStructSplit_Data_Model::StructXY) -> bool
{
  (g.y <= g.x) ==>
    (m.y < m.x)
}

} // verus!
