// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Copies of the component GUMBO contracts for system-level verification.
//! The originals live in the component crates, which this crate cannot
//! depend on (they are staticlibs); both are generated from the same
//! GUMBO source, so they are identical by construction (TCB item T3).

#![allow(non_snake_case)]

use data::*;
use vstd::prelude::*;

verus! {

// -- StructSplit_System_Instance.gen.gen --
pub mod gen {
  use super::*;

  /** initialize guarantee init_outstruct
    *   The output data port must be initialized.
    */
  pub open spec fn initialize_init_outstruct(
    api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    (api_outstruct.x == 0i32) &&
      (api_outstruct.y == 0i32)
  }

  /** integration guarantee outstruct_range (I-Guar, outgoing port outstruct)
    *   Both fields of the generated struct lie in [-100, 100].
    */
  pub open spec fn integration_spec_outstruct_range_guarantee(
    api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    (((-100i32 <= api_outstruct.x) &&
      (api_outstruct.x <= 100i32)) &&
      (-100i32 <= api_outstruct.y)) &&
      (api_outstruct.y <= 100i32)
  }
}

// -- StructSplit_System_Instance.splitter.splitter --
pub mod split_stage {
  use super::*;

  /** compute guarantee split_x
    *   xfield equals the x field of the incoming struct.
    */
  pub open spec fn compute_spec_split_x_guarantee(
    api_instruct: SysPropStructSplit_Data_Model::StructXY,
    api_xfield: i32) -> bool
  {
    api_xfield == api_instruct.x
  }

  /** compute guarantee split_y
    *   yfield equals the y field of the incoming struct.
    */
  pub open spec fn compute_spec_split_y_guarantee(
    api_instruct: SysPropStructSplit_Data_Model::StructXY,
    api_yfield: i32) -> bool
  {
    api_yfield == api_instruct.y
  }

  /** integration assume instruct_range (I-Assm, incoming port instruct)
    *   Incoming struct fields lie in [-100, 100].
    */
  pub open spec fn integration_spec_instruct_range_assume(
    api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    (((-100i32 <= api_instruct.x) &&
      (api_instruct.x <= 100i32)) &&
      (-100i32 <= api_instruct.y)) &&
      (api_instruct.y <= 100i32)
  }

  /** integration guarantee xfield_range (I-Guar, outgoing port xfield)
    *   xfield lies in [-100, 100].
    */
  pub open spec fn integration_spec_xfield_range_guarantee(
    api_xfield: i32) -> bool
  {
    (-100i32 <= api_xfield) &&
      (api_xfield <= 100i32)
  }

  /** integration guarantee yfield_range (I-Guar, outgoing port yfield)
    *   yfield lies in [-100, 100].
    */
  pub open spec fn integration_spec_yfield_range_guarantee(
    api_yfield: i32) -> bool
  {
    (-100i32 <= api_yfield) &&
      (api_yfield <= 100i32)
  }
}

// -- StructSplit_System_Instance.incx.incx --
pub mod incx {
  use super::*;

  /** compute assume inxfield_bounded
    *   Overflow guard only: the input lies in a
    *   conservative [-1000, 1000] envelope so the increment cannot overflow.
    */
  pub open spec fn compute_spec_inxfield_bounded_assume(
    api_inxfield: i32) -> bool
  {
    (-1000i32 <= api_inxfield) &&
      (api_inxfield <= 1000i32)
  }

  /** compute guarantee incx
    *   Output is the input incremented by one.
    */
  pub open spec fn compute_spec_incx_guarantee(
    api_inxfield: i32,
    api_outxfield: i32) -> bool
  {
    api_outxfield == api_inxfield + 1i32
  }
}

// -- StructSplit_System_Instance.clampx.clampx --
pub mod clampx {
  use super::*;

  /** compute case In_Range
    *   values already in [-100, 100] pass through unchanged
    */
  pub open spec fn compute_case_In_Range(
    api_inxfield: i32,
    api_outxfield: i32) -> bool
  {
    ((-100i32 <= api_inxfield) &&
      (api_inxfield <= 100i32))
    ==> (api_outxfield == api_inxfield)
  }

  /** compute case Above
    *   values above 100 saturate to 100
    */
  pub open spec fn compute_case_Above(
    api_inxfield: i32,
    api_outxfield: i32) -> bool
  {
    (api_inxfield > 100i32)
    ==> (api_outxfield == 100i32)
  }

  /** compute case Below
    *   values below -100 saturate to -100
    */
  pub open spec fn compute_case_Below(
    api_inxfield: i32,
    api_outxfield: i32) -> bool
  {
    (api_inxfield < -100i32)
    ==> (api_outxfield == -100i32)
  }
}

// -- StructSplit_System_Instance.decy.decy --
pub mod decy {
  use super::*;

  /** compute assume inyfield_bounded
    *   Underflow guard only: the input lies in a
    *   conservative [-1000, 1000] envelope so the decrement cannot underflow.
    */
  pub open spec fn compute_spec_inyfield_bounded_assume(
    api_inyfield: i32) -> bool
  {
    (-1000i32 <= api_inyfield) &&
      (api_inyfield <= 1000i32)
  }

  /** compute guarantee decy
    *   Output is the input decremented by one.
    */
  pub open spec fn compute_spec_decy_guarantee(
    api_inyfield: i32,
    api_outyfield: i32) -> bool
  {
    api_outyfield == api_inyfield - 1i32
  }
}

// -- StructSplit_System_Instance.merger.merger --
pub mod merge_stage {
  use super::*;

  /** compute guarantee merge_x
    *   Output struct's x field equals the inxfield input.
    */
  pub open spec fn compute_spec_merge_x_guarantee(
    api_inxfield: i32,
    api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    api_outstruct.x == api_inxfield
  }

  /** compute guarantee merge_y
    *   Output struct's y field equals the inyfield input.
    */
  pub open spec fn compute_spec_merge_y_guarantee(
    api_inyfield: i32,
    api_outstruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    api_outstruct.y == api_inyfield
  }
}

// -- StructSplit_System_Instance.consume.consume --
pub mod consume {
  use super::*;

  /** initialize guarantee init_last_x
    *   The state variable starts at zero.
    */
  pub open spec fn initialize_init_last_x(
    last_x: i32) -> bool
  {
    last_x == 0i32
  }

  /** compute assume instruct_range
    *   Incoming struct fields lie in [-200, 200].
    */
  pub open spec fn compute_spec_instruct_range_assume(
    api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    (((-200i32 <= api_instruct.x) &&
      (api_instruct.x <= 200i32)) &&
      (-200i32 <= api_instruct.y)) &&
      (api_instruct.y <= 200i32)
  }

  /** compute guarantee track_x
    *   last_x records the x field of the most recently consumed struct.
    */
  pub open spec fn compute_spec_track_x_guarantee(
    last_x: i32,
    api_instruct: SysPropStructSplit_Data_Model::StructXY) -> bool
  {
    last_x == api_instruct.x
  }
}

} // verus!
