// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Write frames -- per component, the global frame constrains every
//! SystemState field outside the component's write set to be unchanged
//! across its firing; the local frame is `true`.

#![allow(non_snake_case)]

use vstd::prelude::*;

use crate::system_state::SystemState;

verus! {

/** GEN writes: gen_out.
  * Everything else must be unchanged.
  */
pub open spec fn gen_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.x0 == post.x0
  && pre.y0 == post.y0
  && pre.x1 == post.x1
  && pre.x2 == post.x2
  && pre.y1 == post.y1
  && pre.merged == post.merged
  && pre.consume_last_x == post.consume_last_x
}

/** GEN local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn gen_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** SPLIT_STAGE writes: x0, y0.
  * Everything else must be unchanged.
  */
pub open spec fn split_stage_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.gen_out == post.gen_out
  && pre.x1 == post.x1
  && pre.x2 == post.x2
  && pre.y1 == post.y1
  && pre.merged == post.merged
  && pre.consume_last_x == post.consume_last_x
}

/** SPLIT_STAGE local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn split_stage_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** INCX writes: x1.
  * Everything else must be unchanged.
  */
pub open spec fn incx_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.gen_out == post.gen_out
  && pre.x0 == post.x0
  && pre.y0 == post.y0
  && pre.x2 == post.x2
  && pre.y1 == post.y1
  && pre.merged == post.merged
  && pre.consume_last_x == post.consume_last_x
}

/** INCX local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn incx_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** CLAMPX writes: x2.
  * Everything else must be unchanged.
  */
pub open spec fn clampx_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.gen_out == post.gen_out
  && pre.x0 == post.x0
  && pre.y0 == post.y0
  && pre.x1 == post.x1
  && pre.y1 == post.y1
  && pre.merged == post.merged
  && pre.consume_last_x == post.consume_last_x
}

/** CLAMPX local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn clampx_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** DECY writes: y1.
  * Everything else must be unchanged.
  */
pub open spec fn decy_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.gen_out == post.gen_out
  && pre.x0 == post.x0
  && pre.y0 == post.y0
  && pre.x1 == post.x1
  && pre.x2 == post.x2
  && pre.merged == post.merged
  && pre.consume_last_x == post.consume_last_x
}

/** DECY local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn decy_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** MERGE_STAGE writes: merged.
  * Everything else must be unchanged.
  */
pub open spec fn merge_stage_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.gen_out == post.gen_out
  && pre.x0 == post.x0
  && pre.y0 == post.y0
  && pre.x1 == post.x1
  && pre.x2 == post.x2
  && pre.y1 == post.y1
  && pre.consume_last_x == post.consume_last_x
}

/** MERGE_STAGE local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn merge_stage_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

/** CONSUME writes: consume_last_x.
  * Everything else must be unchanged.
  */
pub open spec fn consume_global_write_frame(pre: SystemState, post: SystemState) -> bool
{
  pre.gen_out == post.gen_out
  && pre.x0 == post.x0
  && pre.y0 == post.y0
  && pre.x1 == post.x1
  && pre.x2 == post.x2
  && pre.y1 == post.y1
  && pre.merged == post.merged
}

/** CONSUME local write frame: the component may modify anything in its
  * own scope (Isabelle `lFrame := (λ_ _. True)`).
  */
pub open spec fn consume_local_write_frame(pre: SystemState, post: SystemState) -> bool
{
  true
}

} // verus!
