// Do not edit this file as it will be overwritten if codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn ProdCons_Message_strategy_default() -> impl Strategy<Value = ProdCons::Message>
{
  ProdCons_Message_strategy_cust(
    any::<i32>(),
    any::<i32>()
  )
}

pub fn ProdCons_Message_strategy_cust
  <payload_i32_strategy: Strategy<Value = i32>, 
   control_num_i32_strategy: Strategy<Value = i32>> (
  payload_strategy: payload_i32_strategy,
  control_num_strategy: control_num_i32_strategy) -> impl Strategy<Value = ProdCons::Message>
{
  (payload_strategy, control_num_strategy).prop_map(|(payload, control_num)| {
    ProdCons::Message { payload, control_num }
  })
}
