// Do not edit this file as it will be overwritten if codegen is rerun

use crate::bridge::extern_c_api as extern_api;
use data::*;

use proptest::prelude::*;

/// container for component's incoming port values
pub struct PreStateContainer {
  pub api_input: Option<ProdCons::Message>
}

/// container for component's incoming port values and GUMBO state variables
pub struct PreStateContainer_wGSV {
  pub In_payload_sum: i32,
  pub api_input: Option<ProdCons::Message>
}

/// setter for component's incoming port values
pub fn put_concrete_inputs_container(container: PreStateContainer)
{
  put_input(container.api_input);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_container_wGSV(container: PreStateContainer_wGSV)
{
  put_payload_sum(container.In_payload_sum);
  put_input(container.api_input);
}

/// setter for component's incoming port values
pub fn put_concrete_inputs(input: Option<ProdCons::Message>)
{
  put_input(input);
}

/// setter for component's incoming port values and GUMBO state variables
pub fn put_concrete_inputs_wGSV(
  In_payload_sum: i32,
  input: Option<ProdCons::Message>)
{
  put_payload_sum(In_payload_sum);
  put_input(input);
}

/// setter for IN EventDataPort
pub fn put_input(value: Option<ProdCons::Message>)
{
  *extern_api::IN_input.lock().unwrap_or_else(|e| e.into_inner()) = value
}

/// getter for GUMBO State Variable
pub fn get_payload_sum() -> i32
{
  unsafe {
    match &crate::app {
      Some(inner) => inner.payload_sum,
      None => panic!("The app is None")
    }
  }
}

/// setter for GUMBO State Variable
pub fn put_payload_sum(value: i32)
{
  unsafe {
    match &mut crate::app {
      Some(inner) => inner.payload_sum = value,
      None => panic!("The app is None")
    }
  }
}
