#include "merger_merger.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void merger_merger_initialize(void);
void merger_merger_notify(microkit_channel channel);
void merger_merger_timeTriggered(void);

volatile sb_queue_int32_t_1_t *inxfield_queue_1;
sb_queue_int32_t_1_Recv_t inxfield_recv_queue;
volatile sb_queue_int32_t_1_t *inyfield_queue_1;
sb_queue_int32_t_1_Recv_t inyfield_recv_queue;
volatile sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *outstruct_queue_1;

#define PORT_FROM_MON 50

int32_t last_inxfield_payload;

bool get_inxfield(int32_t *data) {
  sb_event_counter_t numDropped;
  int32_t fresh_data;
  bool isFresh = sb_queue_int32_t_1_dequeue((sb_queue_int32_t_1_Recv_t *) &inxfield_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_inxfield_payload = fresh_data;
  }
  *data = last_inxfield_payload;
  return isFresh;
}

int32_t last_inyfield_payload;

bool get_inyfield(int32_t *data) {
  sb_event_counter_t numDropped;
  int32_t fresh_data;
  bool isFresh = sb_queue_int32_t_1_dequeue((sb_queue_int32_t_1_Recv_t *) &inyfield_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_inyfield_payload = fresh_data;
  }
  *data = last_inyfield_payload;
  return isFresh;
}

bool put_outstruct(const SysPropStructSplit_Data_Model_StructXY *data) {
  sb_queue_SysPropStructSplit_Data_Model_StructXY_1_enqueue((sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *) outstruct_queue_1, (SysPropStructSplit_Data_Model_StructXY *) data);

  return true;
}

void init(void) {
  sb_queue_int32_t_1_Recv_init(&inxfield_recv_queue, (sb_queue_int32_t_1_t *) inxfield_queue_1);

  sb_queue_int32_t_1_Recv_init(&inyfield_recv_queue, (sb_queue_int32_t_1_t *) inyfield_queue_1);

  sb_queue_SysPropStructSplit_Data_Model_StructXY_1_init((sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *) outstruct_queue_1);

  merger_merger_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      merger_merger_timeTriggered();
      break;
    default:
      merger_merger_notify(channel);
  }
}
