// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait clampx_clampx_Api {}

  pub trait clampx_clampx_Put_Api: clampx_clampx_Api {
    #[verifier::external_body]
    fn unverified_put_outxfield(
      &mut self,
      value: i32)
    {
      extern_api::unsafe_put_outxfield(&value);
    }
  }

  pub trait clampx_clampx_Get_Api: clampx_clampx_Api {
    #[verifier::external_body]
    fn unverified_get_inxfield(
      &mut self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_inxfield();
    }
  }

  pub trait clampx_clampx_Full_Api: clampx_clampx_Put_Api + clampx_clampx_Get_Api {}

  pub struct clampx_clampx_Application_Api<API: clampx_clampx_Api> {
    pub api: API,

    pub ghost inxfield: i32,
    pub ghost outxfield: i32
  }

  impl<API: clampx_clampx_Put_Api> clampx_clampx_Application_Api<API> {
    pub fn put_outxfield(
      &mut self,
      value: i32)
      ensures
        old(self).inxfield == self.inxfield,
        self.outxfield == value,
    {
      self.api.unverified_put_outxfield(value);
      self.outxfield = value;
    }
  }

  impl<API: clampx_clampx_Get_Api> clampx_clampx_Application_Api<API> {
    pub fn get_inxfield(&mut self) -> (res : i32)
      ensures
        old(self).inxfield == self.inxfield,
        res == self.inxfield,
        old(self).outxfield == self.outxfield,
    {
      self.api.unverified_get_inxfield(&Ghost(self.inxfield))
    }
  }

  pub struct clampx_clampx_Initialization_Api;
  impl clampx_clampx_Api for clampx_clampx_Initialization_Api {}
  impl clampx_clampx_Put_Api for clampx_clampx_Initialization_Api {}

  pub const fn init_api() -> clampx_clampx_Application_Api<clampx_clampx_Initialization_Api> {
    return clampx_clampx_Application_Api {
      api: clampx_clampx_Initialization_Api {},

      inxfield: 0,
      outxfield: 0
    }
  }

  pub struct clampx_clampx_Compute_Api;
  impl clampx_clampx_Api for clampx_clampx_Compute_Api {}
  impl clampx_clampx_Put_Api for clampx_clampx_Compute_Api {}
  impl clampx_clampx_Get_Api for clampx_clampx_Compute_Api {}
  impl clampx_clampx_Full_Api for clampx_clampx_Compute_Api {}

  pub const fn compute_api() -> clampx_clampx_Application_Api<clampx_clampx_Compute_Api> {
    return clampx_clampx_Application_Api {
      api: clampx_clampx_Compute_Api {},

      inxfield: 0,
      outxfield: 0
    }
  }

}