// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** guarantee In_Range
  *   values already in [-100, 100] pass through unchanged
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_case_In_Range(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  implies!(
    (-100i32 <= api_inxfield) &
      (api_inxfield <= 100i32),
    api_outxfield == api_inxfield)
}

/** guarantee Above
  *   values above 100 saturate to 100
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_case_Above(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  implies!(
    api_inxfield > 100i32,
    api_outxfield == 100i32)
}

/** guarantee Below
  *   values below -100 saturate to -100
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_case_Below(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  implies!(
    api_inxfield < -100i32,
    api_outxfield == -100i32)
}

/** CEP-T-Case: Top-Level case contracts for clampx's compute entrypoint
  *
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_CEP_T_Case(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  let r0: bool = compute_case_In_Range(api_inxfield, api_outxfield);
  let r1: bool = compute_case_Above(api_inxfield, api_outxfield);
  let r2: bool = compute_case_Below(api_inxfield, api_outxfield);

  return r0 && r1 && r2;
}

/** CEP-Post: Compute Entrypoint Post-Condition for clampx
  *
  * @param api_inxfield incoming data port
  * @param api_outxfield outgoing data port
  */
pub fn compute_CEP_Post(
  api_inxfield: i32,
  api_outxfield: i32) -> bool
{
  // CEP-T-Case: case clauses of clampx's compute entrypoint
  let r0: bool = compute_CEP_T_Case(api_inxfield, api_outxfield);

  return r0;
}
