#include "splitter_splitter.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void splitter_splitter_initialize(void);
void splitter_splitter_notify(microkit_channel channel);
void splitter_splitter_timeTriggered(void);

volatile sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *instruct_queue_1;
sb_queue_SysPropStructSplit_Data_Model_StructXY_1_Recv_t instruct_recv_queue;
volatile sb_queue_int32_t_1_t *xfield_queue_1;
volatile sb_queue_int32_t_1_t *yfield_queue_1;

#define PORT_FROM_MON 58

SysPropStructSplit_Data_Model_StructXY last_instruct_payload;

bool get_instruct(SysPropStructSplit_Data_Model_StructXY *data) {
  sb_event_counter_t numDropped;
  SysPropStructSplit_Data_Model_StructXY fresh_data;
  bool isFresh = sb_queue_SysPropStructSplit_Data_Model_StructXY_1_dequeue((sb_queue_SysPropStructSplit_Data_Model_StructXY_1_Recv_t *) &instruct_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_instruct_payload = fresh_data;
  }
  *data = last_instruct_payload;
  return isFresh;
}

bool put_xfield(const int32_t *data) {
  sb_queue_int32_t_1_enqueue((sb_queue_int32_t_1_t *) xfield_queue_1, (int32_t *) data);

  return true;
}

bool put_yfield(const int32_t *data) {
  sb_queue_int32_t_1_enqueue((sb_queue_int32_t_1_t *) yfield_queue_1, (int32_t *) data);

  return true;
}

void init(void) {
  sb_queue_SysPropStructSplit_Data_Model_StructXY_1_Recv_init(&instruct_recv_queue, (sb_queue_SysPropStructSplit_Data_Model_StructXY_1_t *) instruct_queue_1);

  sb_queue_int32_t_1_init((sb_queue_int32_t_1_t *) xfield_queue_1);

  sb_queue_int32_t_1_init((sb_queue_int32_t_1_t *) yfield_queue_1);

  splitter_splitter_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      splitter_splitter_timeTriggered();
      break;
    default:
      splitter_splitter_notify(channel);
  }
}
