// #Sireum

package TempControlMixedUI.CoolingFan

import org.sireum._
import TempControlMixedUI._

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

@enum object FanCmd {
  "On"
  "Off"
}

object FanCmd_Payload {
  def example(): FanCmd_Payload = {
    return FanCmd_Payload(CoolingFan.FanCmd.byOrdinal(0).get)
  }
}

@datatype class FanCmd_Payload(value: CoolingFan.FanCmd.Type) extends art.DataContent
