// This file will not be overwritten if codegen is rerun

//============================================================================
//  T e s t R e c e i v e r  -- Thread Component
//
//  Test infrastructure: receives and logs messages that have passed
//  through the guard pipeline (Gate -> Filter).  Counts messages
//  received for observability.
//
//  Data flow: TestSender -> Gate -> Filter -> [TestReceiver]
//============================================================================

use data::*;
use crate::bridge::test_receiver_test_receiver_api::*;
use vstd::prelude::*;

verus! {

  // ── Manual invariant for non-GUMBO state ──────────────────────────────
  //
  // The `num_received` field is an implementation-level counter used
  // only for logging.  Unlike test_sender's `test_case_index` (which
  // wraps at a small bound), this counter grows monotonically with no
  // natural upper limit.  To prevent overflow on `num_received + 1`,
  // we use a *saturating* counter that stops incrementing at
  // MAX_RECEIVED.  The invariant is: 0 <= num_received <= MAX_RECEIVED.
  //
  // See test_sender_test_sender_app.rs for a fuller explanation of why
  // manual invariants are needed for non-GUMBO state variables.
  pub const MAX_RECEIVED: i32 = i32::MAX - 1;

  pub open spec fn num_received_inv(n: i32) -> bool {
    0 <= n && n <= MAX_RECEIVED
  }

  //-------------------------------------------
  //  Application State (as a struct)
  //-------------------------------------------
  pub struct test_receiver_test_receiver {
    // PLACEHOLDER MARKER STATE VARS

    // Counter of messages received
    pub num_received: i32,
  }

  impl test_receiver_test_receiver {
    //-------------------------------------------
    //  Application Component Constructor
    //-------------------------------------------
    pub fn new() -> Self
    {
      Self {
        // PLACEHOLDER MARKER STATE VAR INIT

        num_received: 0,
      }
    }

    //-------------------------------------------
    //  Initialize Entry Point
    //-------------------------------------------
    pub fn initialize<API: test_receiver_test_receiver_Put_Api> (
      &mut self,
      api: &mut test_receiver_test_receiver_Application_Api<API>)
      ensures
        // PLACEHOLDER MARKER INITIALIZATION ENSURES
        num_received_inv(self.num_received), // manual invariant: established by init
    {
      log_info("initialize entrypoint invoked");
      self.num_received = 0;
    }

    //-------------------------------------------
    //  Compute Entry Point
    //-------------------------------------------
    pub fn timeTriggered<API: test_receiver_test_receiver_Full_Api> (
      &mut self,
      api: &mut test_receiver_test_receiver_Application_Api<API>)
      requires
        // PLACEHOLDER MARKER TIME TRIGGERED REQUIRES
        num_received_inv(old(self).num_received), // manual invariant: assumed at entry
      ensures
        // PLACEHOLDER MARKER TIME TRIGGERED ENSURES
        num_received_inv(self.num_received), // manual invariant: re-established at exit
    {
      let input_contents = api.get_input();
      match input_contents {
        Some(msg) => {
          // Saturating increment: stop counting at MAX_RECEIVED to avoid overflow.
          // The counter is only used for log output, so capping has no functional impact.
          if self.num_received < MAX_RECEIVED {
            self.num_received = self.num_received + 1;
          }
          log_message_received(self.num_received, msg);
        }
        None => {
          // no message present on input port
        }
      };
    }

    //-------------------------------------------
    //  seL4 / Microkit Error Handling
    //-------------------------------------------
    pub fn notify(
      &mut self,
      channel: microkit_channel)
    {
      // this method is called when the monitor does not handle the passed in channel
      match channel {
        _ => {
          log_warn_channel(channel)
        }
      }
    }
  }

  //-------------------------------------------
  //  Logging Helper Functions
  //-------------------------------------------
  #[verifier::external_body]
  pub fn log_info(msg: &str)
  {
    log::info!("{0}", msg);
  }

  #[verifier::external_body]
  pub fn log_message_received(count: i32, msg: SNG_Data_Model::Message)
  {
    log::info!("TestReceiver: [msg #{0}] received (security_level={1:?}, payload={2})",
      count, msg.security_level, msg.payload);
  }

  #[verifier::external_body]
  pub fn log_warn_channel(channel: u32)
  {
    log::warn!("Unexpected channel: {0}", channel);
  }

  //-------------------------------------------
  //  GUMBO-derived functions/constants auto-generated by HAMR from
  //  model.
  //-------------------------------------------

  // PLACEHOLDER MARKER GUMBO METHODS

}
