// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property gen_range_sanity -- Non-Blocking and Preservation VCs for every
//! MHIP transition pair (per direction whose firing member is a component).
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::gen_range_sanity::assertions::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[19]: Non-Blocking -- INCX firing does not block DECY (MHIP pair t2/t4) */
pub proof fn vc_non_blocking_incx_decy(pre: SystemState, post: SystemState)
  requires
    true /* before_incx has no assertion */,
    true /* before_decy has no assertion */,
    incx_global_write_frame(pre, post),
  ensures
    true /* before_decy has no assertion */,
{}

/** VC[20]: Non-Blocking -- DECY firing does not block INCX (MHIP pair t2/t4) */
pub proof fn vc_non_blocking_decy_incx(pre: SystemState, post: SystemState)
  requires
    true /* before_incx has no assertion */,
    true /* before_decy has no assertion */,
    decy_global_write_frame(pre, post),
  ensures
    true /* before_incx has no assertion */,
{}

/** VC[21]: Preservation -- INCX firing preserves DECY's post-assertions (MHIP pair t2/t4) */
pub proof fn vc_preservation_incx_decy(pre: SystemState, post: SystemState)
  requires
    true /* before_incx has no assertion */,
    true /* after_decy has no assertion */,
    incx_global_write_frame(pre, post),
  ensures
    true /* after_decy has no assertion */,
{}

/** VC[22]: Preservation -- DECY firing preserves INCX's post-assertions (MHIP pair t2/t4) */
pub proof fn vc_preservation_decy_incx(pre: SystemState, post: SystemState)
  requires
    true /* before_decy has no assertion */,
    true /* after_incx has no assertion */,
    decy_global_write_frame(pre, post),
  ensures
    true /* after_incx has no assertion */,
{}

/** VC[23]: Non-Blocking -- CLAMPX firing does not block DECY (MHIP pair t3/t4) */
pub proof fn vc_non_blocking_clampx_decy(pre: SystemState, post: SystemState)
  requires
    true /* after_incx has no assertion */,
    true /* before_decy has no assertion */,
    clampx_global_write_frame(pre, post),
  ensures
    true /* before_decy has no assertion */,
{}

/** VC[24]: Non-Blocking -- DECY firing does not block CLAMPX (MHIP pair t3/t4) */
pub proof fn vc_non_blocking_decy_clampx(pre: SystemState, post: SystemState)
  requires
    true /* after_incx has no assertion */,
    true /* before_decy has no assertion */,
    decy_global_write_frame(pre, post),
  ensures
    true /* after_incx has no assertion */,
{}

/** VC[25]: Preservation -- CLAMPX firing preserves DECY's post-assertions (MHIP pair t3/t4) */
pub proof fn vc_preservation_clampx_decy(pre: SystemState, post: SystemState)
  requires
    true /* after_incx has no assertion */,
    true /* after_decy has no assertion */,
    clampx_global_write_frame(pre, post),
  ensures
    true /* after_decy has no assertion */,
{}

/** VC[26]: Preservation -- DECY firing preserves CLAMPX's post-assertions (MHIP pair t3/t4) */
pub proof fn vc_preservation_decy_clampx(pre: SystemState, post: SystemState)
  requires
    true /* before_decy has no assertion */,
    true /* after_clampx has no assertion */,
    decy_global_write_frame(pre, post),
  ensures
    true /* after_clampx has no assertion */,
{}

} // verus!
