// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property gen_range_sanity -- Post-Pre VC: the END assertion implies the START assertion across hyperperiod boundaries.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::gen_range_sanity::assertions::*;
use crate::contracts::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[18]: Post-Pre -- END |- START (hyperperiod loop invariant) */
pub proof fn vc_post_pre(st: SystemState)
  requires
    true /* END has no assertion */,
  ensures
    true /* START has no assertion */,
{}

} // verus!
