#include "thermostat_thermostat.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void thermostat_thermostat_initialize(void);
void thermostat_thermostat_notify(microkit_channel channel);
void thermostat_thermostat_timeTriggered(void);

volatile sb_queue_Isolette_Data_Model_Temp_1_t *current_temp_queue_1;
sb_queue_Isolette_Data_Model_Temp_1_Recv_t current_temp_recv_queue;
volatile sb_queue_Isolette_Data_Model_Set_Points_1_t *desired_temp_queue_1;
sb_queue_Isolette_Data_Model_Set_Points_1_Recv_t desired_temp_recv_queue;
volatile sb_queue_Isolette_Data_Model_On_Off_1_t *heat_control_queue_1;

#define PORT_FROM_MON 56

Isolette_Data_Model_Temp last_current_temp_payload;

bool get_current_temp(Isolette_Data_Model_Temp *data) {
  sb_event_counter_t numDropped;
  Isolette_Data_Model_Temp fresh_data;
  bool isFresh = sb_queue_Isolette_Data_Model_Temp_1_dequeue((sb_queue_Isolette_Data_Model_Temp_1_Recv_t *) &current_temp_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_current_temp_payload = fresh_data;
  }
  *data = last_current_temp_payload;
  return isFresh;
}

Isolette_Data_Model_Set_Points last_desired_temp_payload;

bool get_desired_temp(Isolette_Data_Model_Set_Points *data) {
  sb_event_counter_t numDropped;
  Isolette_Data_Model_Set_Points fresh_data;
  bool isFresh = sb_queue_Isolette_Data_Model_Set_Points_1_dequeue((sb_queue_Isolette_Data_Model_Set_Points_1_Recv_t *) &desired_temp_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_desired_temp_payload = fresh_data;
  }
  *data = last_desired_temp_payload;
  return isFresh;
}

bool put_heat_control(const Isolette_Data_Model_On_Off *data) {
  sb_queue_Isolette_Data_Model_On_Off_1_enqueue((sb_queue_Isolette_Data_Model_On_Off_1_t *) heat_control_queue_1, (Isolette_Data_Model_On_Off *) data);

  return true;
}

void init(void) {
  sb_queue_Isolette_Data_Model_Temp_1_Recv_init(&current_temp_recv_queue, (sb_queue_Isolette_Data_Model_Temp_1_t *) current_temp_queue_1);

  sb_queue_Isolette_Data_Model_Set_Points_1_Recv_init(&desired_temp_recv_queue, (sb_queue_Isolette_Data_Model_Set_Points_1_t *) desired_temp_queue_1);

  sb_queue_Isolette_Data_Model_On_Off_1_init((sb_queue_Isolette_Data_Model_On_Off_1_t *) heat_control_queue_1);

  thermostat_thermostat_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      thermostat_thermostat_timeTriggered();
      break;
    default:
      thermostat_thermostat_notify(channel);
  }
}
