// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct Message {
    pub payload: i32,
    pub security_level: SecurityLevel
  }

  impl Default for Message {
    fn default() -> Self
    {
      Self { payload: 0, security_level: SNG_Data_Model::SecurityLevel::default() }
    }
  }
}