// Do not edit this file as it will be overwritten if codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {
  #[repr(C)]
  #[derive(Copy, Clone, Debug, PartialEq, Eq)]
  pub enum SecurityLevel {
    pub Public = 0,
    pub Restricted = 1,
    pub Critical = 2,
  }

  impl Default for SecurityLevel {
    fn default() -> Self
    {
      SecurityLevel::Public
    }
  }
}