// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Flat system state for the system-level verification conditions.
//! One field per AADL connection channel (owned by its source out port),
//! unconnected port, and GUMBO state variable across all components.

use data::*;
use vstd::prelude::*;

verus! {

pub struct SystemState {
  // -- StructSplit_System_Instance.gen.gen --
  pub gen_out: SysPropStructSplit_Data_Model::StructXY, // channel

  // -- StructSplit_System_Instance.splitter.splitter --
  pub x0: i32, // channel
  pub y0: i32, // channel

  // -- StructSplit_System_Instance.incx.incx --
  pub x1: i32, // channel

  // -- StructSplit_System_Instance.clampx.clampx --
  pub x2: i32, // channel

  // -- StructSplit_System_Instance.decy.decy --
  pub y1: i32, // channel

  // -- StructSplit_System_Instance.merger.merger --
  pub merged: SysPropStructSplit_Data_Model::StructXY, // channel

  // -- StructSplit_System_Instance.consume.consume --
  pub consume_last_x: i32, // state variable
}

} // verus!
