// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Integration-constraint VCs, one per connected port pair whose
//! destination in-port has an integration assume. Each states that the
//! sender's integration guarantee on the source out-port (or `true`, when
//! the sender declares none) implies the receiver's integration assume on
//! the destination in-port, over the value the connection carries. Static
//! (schedule- and property-independent) -- shared by the whole composition.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::contracts::*;

verus! {

/** VC[0]: Integration -- connection StructSplit_System_Instance.gen.gen.outstruct -> StructSplit_System_Instance.splitter.splitter.instruct: gen.outstruct's I-Guar `outstruct_range`
  * implies split_stage.instruct's I-Assm `instruct_range`, over
  * the value the connection carries. Discharges when the sender's
  * guarantee is at least as strong as the receiver's assume. */
pub proof fn vc_integration_gen_outstruct_to_split_stage_instruct(wire: SysPropStructSplit_Data_Model::StructXY)
  requires
    gen::integration_spec_outstruct_range_guarantee(wire),
  ensures
    split_stage::integration_spec_instruct_range_assume(wire),
{}

} // verus!
