#include "incx_incx.h"

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

void incx_incx_initialize(void);
void incx_incx_notify(microkit_channel channel);
void incx_incx_timeTriggered(void);

volatile sb_queue_int32_t_1_t *inxfield_queue_1;
sb_queue_int32_t_1_Recv_t inxfield_recv_queue;
volatile sb_queue_int32_t_1_t *outxfield_queue_1;

#define PORT_FROM_MON 56

int32_t last_inxfield_payload;

bool get_inxfield(int32_t *data) {
  sb_event_counter_t numDropped;
  int32_t fresh_data;
  bool isFresh = sb_queue_int32_t_1_dequeue((sb_queue_int32_t_1_Recv_t *) &inxfield_recv_queue, &numDropped, &fresh_data);
  if (isFresh) {
    last_inxfield_payload = fresh_data;
  }
  *data = last_inxfield_payload;
  return isFresh;
}

bool put_outxfield(const int32_t *data) {
  sb_queue_int32_t_1_enqueue((sb_queue_int32_t_1_t *) outxfield_queue_1, (int32_t *) data);

  return true;
}

void init(void) {
  sb_queue_int32_t_1_Recv_init(&inxfield_recv_queue, (sb_queue_int32_t_1_t *) inxfield_queue_1);

  sb_queue_int32_t_1_init((sb_queue_int32_t_1_t *) outxfield_queue_1);

  incx_incx_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      incx_incx_timeTriggered();
      break;
    default:
      incx_incx_notify(channel);
  }
}
