#![cfg_attr(not(test), no_std)]

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#![allow(dead_code)]
#![allow(static_mut_refs)]
#![allow(unused_imports)]
#![allow(unused_macros)]
#![allow(unused_parens)]
#![allow(unused_unsafe)]
#![allow(unused_variables)]

#![feature(proc_macro_hygiene)]
#![cfg_attr(not(verus_keep_ghost), feature(stmt_expr_attributes))]

// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! System-level verification conditions of composition `nominal`,
//! discharged by Verus -- shared modules (state, contracts, frames,
//! actions, commutativity, integration) plus one module group per
//! property. See the proof-fn doc comments for the VC indices tying each
//! obligation back to the generator output.

pub mod actions;
pub mod assertions;
pub mod contracts;
pub mod system_state;
pub mod vc_commutativity;
pub mod vc_integration;
pub mod write_frames;

pub mod gen_range_sanity;
pub mod merged_in_consume_range;
pub mod end_to_end_functional;
pub mod consume_range_loop_invariant;
pub mod y_stays_strictly_below_x;
