// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Commutativity VCs (execIndependent), one per component-component MHIP
//! pair. Assertion-free state equalities over the action abstractions --
//! shared by all of the composition's properties.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]

use vstd::prelude::*;

use crate::actions::*;
use crate::system_state::SystemState;

verus! {

/** VC[0]: Commutativity (execIndependent) -- firing INCX then DECY
  * yields the same state as DECY then INCX (MHIP pair t2/t4).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_incx_decy(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    incx_fire(st, mid_a),
    decy_fire(mid_a, post_a),
    decy_fire(st, mid_b),
    incx_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

/** VC[1]: Commutativity (execIndependent) -- firing CLAMPX then DECY
  * yields the same state as DECY then CLAMPX (MHIP pair t3/t4).
  * Discharges by congruence when the write sets are disjoint from each
  * other's write sets and read scopes. */
pub proof fn vc_commutativity_clampx_decy(st: SystemState, mid_a: SystemState, post_a: SystemState, mid_b: SystemState, post_b: SystemState)
  requires
    clampx_fire(st, mid_a),
    decy_fire(mid_a, post_a),
    decy_fire(st, mid_b),
    clampx_fire(mid_b, post_b),
  ensures
    post_a == post_b,
{}

} // verus!
