#include "gate_gate.h"

// Do not edit this file as it will be overwritten if codegen is rerun

void gate_gate_initialize(void);
void gate_gate_notify(microkit_channel channel);
void gate_gate_timeTriggered(void);

volatile sb_queue_SNG_Data_Model_Message_1_t *output_queue_1;
volatile sb_queue_SNG_Data_Model_Message_1_t *input_queue_1;
sb_queue_SNG_Data_Model_Message_1_Recv_t input_recv_queue;

#define PORT_FROM_MON 60

bool put_output(const SNG_Data_Model_Message *data) {
  sb_queue_SNG_Data_Model_Message_1_enqueue((sb_queue_SNG_Data_Model_Message_1_t *) output_queue_1, (SNG_Data_Model_Message *) data);

  return true;
}

bool input_is_empty(void) {
  return sb_queue_SNG_Data_Model_Message_1_is_empty(&input_recv_queue);
}

bool get_input_poll(sb_event_counter_t *numDropped, SNG_Data_Model_Message *data) {
  return sb_queue_SNG_Data_Model_Message_1_dequeue((sb_queue_SNG_Data_Model_Message_1_Recv_t *) &input_recv_queue, numDropped, data);
}

bool get_input(SNG_Data_Model_Message *data) {
  sb_event_counter_t numDropped;
  return get_input_poll (&numDropped, data);
}

void init(void) {
  sb_queue_SNG_Data_Model_Message_1_init((sb_queue_SNG_Data_Model_Message_1_t *) output_queue_1);

  sb_queue_SNG_Data_Model_Message_1_Recv_init(&input_recv_queue, (sb_queue_SNG_Data_Model_Message_1_t *) input_queue_1);

  gate_gate_initialize();
}

void notified(microkit_channel channel) {
  switch (channel) {
    case PORT_FROM_MON:
      gate_gate_timeTriggered();
      break;
    default:
      gate_gate_notify(channel);
  }
}
