// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

use proptest::prelude::*;

pub fn option_strategy_default
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (base: S) -> impl Strategy<Value = Option<T>>
{
  option_strategy_bias(1, base)
}

pub fn option_strategy_bias
  <T: Clone + std::fmt::Debug, 
   S:  Strategy<Value = T>> (
  bias: u32,
  base: S) -> impl Strategy<Value = Option<T>>
{
  prop_oneof![
    bias => base.prop_map(Some),
    1 => Just(None),
  ]
}

pub fn SysPropStructSplit_Data_Model_StructXY_strategy_default() -> impl Strategy<Value = SysPropStructSplit_Data_Model::StructXY>
{
  SysPropStructSplit_Data_Model_StructXY_strategy_cust(
    any::<i32>(),
    any::<i32>()
  )
}

pub fn SysPropStructSplit_Data_Model_StructXY_strategy_cust
  <x_i32_strategy: Strategy<Value = i32>, 
   y_i32_strategy: Strategy<Value = i32>> (
  x_strategy: x_i32_strategy,
  y_strategy: y_i32_strategy) -> impl Strategy<Value = SysPropStructSplit_Data_Model::StructXY>
{
  (x_strategy, y_strategy).prop_map(|(x, y)| {
    SysPropStructSplit_Data_Model::StructXY { x, y }
  })
}
