// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! C-interface for the component.
//! This code must be unsafe.
//! Assumptions about correctness are introduced and need to be verified by other means.

use data::*;

#[cfg(test)]
use std::sync::Mutex;

#[cfg(not(test))]
extern "C" {
  fn get_inxfield(value: *mut i32) -> bool;
  fn put_outxfield(value: *mut i32) -> bool;
}

pub fn unsafe_get_inxfield() -> i32
{
  unsafe {
    let value: *mut i32 = &mut 0;
    get_inxfield(value);
    return *value;
  }
}

pub fn unsafe_put_outxfield(value: &i32) -> bool
{
  unsafe {
    return put_outxfield(value as *const i32 as *mut i32);
  }
}

//////////////////////////////////////////////////////////////////////////////////
// Testing Versions
//////////////////////////////////////////////////////////////////////////////////

#[cfg(test)]
lazy_static::lazy_static! {
  // simulate the global C variables that point to the microkit shared memory regions.  In a full
  // microkit system we would be able to mutate the shared memory for out ports since they're r/w,
  // but we couldn't do that for in ports since they are read-only
  pub static ref IN_inxfield: Mutex<Option<i32>> = Mutex::new(None);
  pub static ref OUT_outxfield: Mutex<Option<i32>> = Mutex::new(None);
}

#[cfg(test)]
pub fn initialize_test_globals() {
  unsafe {
    *IN_inxfield.lock().unwrap_or_else(|e| e.into_inner()) = None;
    *OUT_outxfield.lock().unwrap_or_else(|e| e.into_inner()) = None;
  }
}

#[cfg(test)]
pub fn get_inxfield(value: *mut i32) -> bool
{
  unsafe {
    let guard = IN_inxfield.lock().unwrap_or_else(|e| e.into_inner());
    *value = guard.expect("Not expecting None");
    true
  }
}

#[cfg(test)]
pub fn put_outxfield(value: *mut i32) -> bool
{
  unsafe {
    *OUT_outxfield.lock().unwrap_or_else(|e| e.into_inner()) = Some(*value);
    return true;
  }
}
