// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;
use data::*;
use super::extern_c_api as extern_api;

verus! {

  pub trait incx_incx_Api {}

  pub trait incx_incx_Put_Api: incx_incx_Api {
    #[verifier::external_body]
    fn unverified_put_outxfield(
      &mut self,
      value: i32)
    {
      extern_api::unsafe_put_outxfield(&value);
    }
  }

  pub trait incx_incx_Get_Api: incx_incx_Api {
    #[verifier::external_body]
    fn unverified_get_inxfield(
      &mut self,
      value: &Ghost<i32>) -> (res : i32)
      ensures
        res == value@,
    {
      return extern_api::unsafe_get_inxfield();
    }
  }

  pub trait incx_incx_Full_Api: incx_incx_Put_Api + incx_incx_Get_Api {}

  pub struct incx_incx_Application_Api<API: incx_incx_Api> {
    pub api: API,

    pub ghost inxfield: i32,
    pub ghost outxfield: i32
  }

  impl<API: incx_incx_Put_Api> incx_incx_Application_Api<API> {
    pub fn put_outxfield(
      &mut self,
      value: i32)
      ensures
        old(self).inxfield == self.inxfield,
        self.outxfield == value,
    {
      self.api.unverified_put_outxfield(value);
      self.outxfield = value;
    }
  }

  impl<API: incx_incx_Get_Api> incx_incx_Application_Api<API> {
    pub fn get_inxfield(&mut self) -> (res : i32)
      ensures
        old(self).inxfield == self.inxfield,
        res == self.inxfield,
        old(self).outxfield == self.outxfield,
    {
      self.api.unverified_get_inxfield(&Ghost(self.inxfield))
    }
  }

  pub struct incx_incx_Initialization_Api;
  impl incx_incx_Api for incx_incx_Initialization_Api {}
  impl incx_incx_Put_Api for incx_incx_Initialization_Api {}

  pub const fn init_api() -> incx_incx_Application_Api<incx_incx_Initialization_Api> {
    return incx_incx_Application_Api {
      api: incx_incx_Initialization_Api {},

      inxfield: 0,
      outxfield: 0
    }
  }

  pub struct incx_incx_Compute_Api;
  impl incx_incx_Api for incx_incx_Compute_Api {}
  impl incx_incx_Put_Api for incx_incx_Compute_Api {}
  impl incx_incx_Get_Api for incx_incx_Compute_Api {}
  impl incx_incx_Full_Api for incx_incx_Compute_Api {}

  pub const fn compute_api() -> incx_incx_Application_Api<incx_incx_Compute_Api> {
    return incx_incx_Application_Api {
      api: incx_incx_Compute_Api {},

      inxfield: 0,
      outxfield: 0
    }
  }

}