// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Place-assertion spec functions of property `y_stays_strictly_below_x` -- one per
//! point its decoration binds (unbound points carry `true`, design D5).

#![allow(non_snake_case)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::assertions::*;
use crate::system_state::SystemState;

verus! {

/** property y_stays_strictly_below_x, bound 'after gen' (place after_gen)
  *   GenStruct guarantees both fields in [-100, 100]
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_after_gen(st: SystemState) -> bool
{
  inRange100(st.gen_out.x) && inRange100(st.gen_out.y)
}

/** property y_stays_strictly_below_x, bound 'after split_stage' (place after_split_stage)
  *   SplitStruct forwards each field, preserving [-100, 100]
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_after_split_stage(st: SystemState) -> bool
{
  (inRange100(st.x0) && inRange100(st.y0)) &&
    ((st.x0 == st.gen_out.x) &&
      (st.y0 == st.gen_out.y))
}

/** property y_stays_strictly_below_x, bound 'before incx' (place before_incx)
  *   branch entry: x still in [-100, 100] -- discharges IncX's
  *   [-1000, 1000] overflow-guard compute assume
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_before_incx(st: SystemState) -> bool
{
  inRange100(st.x0) &&
    (st.x0 == st.gen_out.x)
}

/** property y_stays_strictly_below_x, bound 'after incx' (place after_incx)
  *   IncX's compute guarantee (x1 == x0 + 1) plus the carried
  *   [-100, 100] range yield x1 in [-99, 101]; this place IS `before clampx`
  *   (consecutive branch elements share a place), and ClampX -- whose
  *   compute_cases are total -- needs no assume discharged here
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_after_incx(st: SystemState) -> bool
{
  ((-99i32 <= st.x1) &&
    (st.x1 <= 101i32)) &&
    (st.x1 == st.gen_out.x + 1i32)
}

/** property y_stays_strictly_below_x, bound 'after clampx' (place after_clampx)
  *   ClampX saturates back into [-100, 100]
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_after_clampx(st: SystemState) -> bool
{
  (inRange100(st.x2) &&
    (((st.gen_out.x < 100i32) ==>
      (st.x2 == st.gen_out.x + 1i32)) &&
      ((st.gen_out.x == 100i32) ==>
        (st.x2 == 100i32)))) &&
    (st.gen_out.x <= 100i32)
}

/** property y_stays_strictly_below_x, bound 'before decy' (place before_decy)
  *   branch entry: y still in [-100, 100] -- discharges DecY's
  *   [-1000, 1000] underflow-guard compute assume
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_before_decy(st: SystemState) -> bool
{
  inRange100(st.y0) &&
    (st.y0 == st.gen_out.y)
}

/** property y_stays_strictly_below_x, bound 'after decy' (place after_decy)
  *   DecY's compute guarantee (y1 == y0 - 1) plus the carried
  *   [-100, 100] range yield y1 in [-101, 99]
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_after_decy(st: SystemState) -> bool
{
  ((-101i32 <= st.y1) &&
    (st.y1 <= 99i32)) &&
    (st.y1 == st.gen_out.y - 1i32)
}

/** property y_stays_strictly_below_x, bound 'at branches_joined' (place post_join_1)
  *   join: both transformed ranges are available to the merger
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_post_join_1(st: SystemState) -> bool
{
  (((inRange100(st.x2) &&
    (-101i32 <= st.y1)) &&
    (st.y1 <= 99i32)) &&
    ((((st.gen_out.x < 100i32) ==>
      (st.x2 == st.gen_out.x + 1i32)) &&
      ((st.gen_out.x == 100i32) ==>
        (st.x2 == 100i32))) &&
      (st.y1 == st.gen_out.y - 1i32))) &&
    (st.gen_out.x <= 100i32)
}

/** property y_stays_strictly_below_x, bound 'before consume' (place after_merge_stage)
  *   the end-to-end conclusion at the consumer's dispatch
  */
pub open spec fn sys_assert_y_stays_strictly_below_x_after_merge_stage(st: SystemState) -> bool
{
  yStaysBelowX(st.merged, st.gen_out)
}

} // verus!
