// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use vstd::prelude::*;

use super::*;

verus! {

  #[repr(C)]
  #[derive(Debug, Clone, Copy, PartialEq, Eq)]
  pub struct StructXY {
    pub x: i32,
    pub y: i32
  }

  impl Default for StructXY {
    fn default() -> Self
    {
      Self { x: 0, y: 0 }
    }
  }

}