// Do not edit this file as it will be overwritten if HAMR codegen is rerun

use data::*;

macro_rules! implies {
  ($lhs: expr, $rhs: expr) => {
    !$lhs || $rhs
  };
}

macro_rules! impliesL {
  ($lhs: expr, $rhs: expr) => {
    !$lhs | $rhs
  };
}

/** I-Guar: Integration constraint on operator_interface's outgoing event data port desired_temp
  *
  * guarantee LDT_LE_UDT
  *  The lower desired temperature is at most the
  *  upper desired temperature in every emitted message.
  */
pub fn I_Guar_desired_temp(desired_temp: Isolette_Data_Model::Set_Points) -> bool
{
  desired_temp.lower.degrees <= desired_temp.upper.degrees
}

/** I-Guar: Integration constraint on operator_interface's outgoing event data port desired_temp
  *
  * guarantee LDT_LE_UDT
  *  The lower desired temperature is at most the
  *  upper desired temperature in every emitted message.
  */
pub fn I_Guar_Guard_desired_temp(desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  implies!(
    desired_temp.is_some(),
    I_Guar_desired_temp(desired_temp.unwrap())
  )
}

/** IEP-Post: Initialize Entrypoint Post-Condition
  *
  * @param api_desired_temp outgoing event data port
  */
pub fn initialize_IEP_Post(api_desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  // I-Guar-Guard: Integration constraints for operator_interface's outgoing ports"
  I_Guar_Guard_desired_temp(api_desired_temp)
}

/** CEP-Post: Compute Entrypoint Post-Condition for operator_interface
  *
  * @param api_desired_temp outgoing event data port
  */
pub fn compute_CEP_Post(api_desired_temp: Option<Isolette_Data_Model::Set_Points>) -> bool
{
  // I-Guar-Guard: Integration constraints for operator_interface's outgoing ports
  let r0: bool = I_Guar_Guard_desired_temp(api_desired_temp);

  return r0;
}
