// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Place-assertion spec functions of property `consume_range_loop_invariant` -- one per
//! point its decoration binds (unbound points carry `true`, design D5).

#![allow(non_snake_case)]
#![allow(unused_imports)]

use data::*;
use vstd::prelude::*;

use crate::assertions::*;
use crate::system_state::SystemState;

verus! {

/** property consume_range_loop_invariant, bound 'after gen' (place after_gen)
  *   GenStruct guarantees both fields in [-100, 100]
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_gen(st: SystemState) -> bool
{
  inRange100(st.gen_out.x) && inRange100(st.gen_out.y)
}

/** property consume_range_loop_invariant, bound 'after split_stage' (place after_split_stage)
  *   SplitStruct forwards each field, preserving [-100, 100]
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_split_stage(st: SystemState) -> bool
{
  inRange100(st.x0) && inRange100(st.y0)
}

/** property consume_range_loop_invariant, bound 'before incx' (place before_incx)
  *   branch entry: x still in [-100, 100] -- discharges IncX's
  *   [-1000, 1000] overflow-guard compute assume
  */
pub open spec fn sys_assert_consume_range_loop_invariant_before_incx(st: SystemState) -> bool
{
  inRange100(st.x0)
}

/** property consume_range_loop_invariant, bound 'after incx' (place after_incx)
  *   IncX's compute guarantee (x1 == x0 + 1) plus the carried
  *   [-100, 100] range yield x1 in [-99, 101]; this place IS `before clampx`
  *   (consecutive branch elements share a place), and ClampX -- whose
  *   compute_cases are total -- needs no assume discharged here
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_incx(st: SystemState) -> bool
{
  (-99i32 <= st.x1) &&
    (st.x1 <= 101i32)
}

/** property consume_range_loop_invariant, bound 'after clampx' (place after_clampx)
  *   ClampX saturates back into [-100, 100]
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_clampx(st: SystemState) -> bool
{
  inRange100(st.x2)
}

/** property consume_range_loop_invariant, bound 'before decy' (place before_decy)
  *   branch entry: y still in [-100, 100] -- discharges DecY's
  *   [-1000, 1000] underflow-guard compute assume
  */
pub open spec fn sys_assert_consume_range_loop_invariant_before_decy(st: SystemState) -> bool
{
  inRange100(st.y0)
}

/** property consume_range_loop_invariant, bound 'after decy' (place after_decy)
  *   DecY's compute guarantee (y1 == y0 - 1) plus the carried
  *   [-100, 100] range yield y1 in [-101, 99]
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_decy(st: SystemState) -> bool
{
  (-101i32 <= st.y1) &&
    (st.y1 <= 99i32)
}

/** property consume_range_loop_invariant, bound 'at branches_joined' (place post_join_1)
  *   join: both transformed ranges are available to the merger
  */
pub open spec fn sys_assert_consume_range_loop_invariant_post_join_1(st: SystemState) -> bool
{
  (inRange100(st.x2) &&
    (-101i32 <= st.y1)) &&
    (st.y1 <= 99i32)
}

/** property consume_range_loop_invariant, bound 'at START' (place START)
  *   frame entry: established initially by consume's initialize guarantee
  */
pub open spec fn sys_assert_consume_range_loop_invariant_START(st: SystemState) -> bool
{
  inRange200(st.consume_last_x)
}

/** property consume_range_loop_invariant, bound 'before consume' (place after_merge_stage)
  *   the merged range fact at consume's dispatch; discharges
  *   consume's [-200, 200] compute assume
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_merge_stage(st: SystemState) -> bool
{
  inConsumeRange(st.merged)
}

/** property consume_range_loop_invariant, bound 'after consume' (place after_consume)
  *   consume's guarantee last_x == instruct.x re-establishes the invariant
  */
pub open spec fn sys_assert_consume_range_loop_invariant_after_consume(st: SystemState) -> bool
{
  inRange200(st.consume_last_x)
}

/** property consume_range_loop_invariant, bound 'at END' (place END)
  *   loop closure: carried from `after consume` to the frame boundary
  */
pub open spec fn sys_assert_consume_range_loop_invariant_END(st: SystemState) -> bool
{
  inRange200(st.consume_last_x)
}

} // verus!
