// Do not edit this file as it will be overwritten if HAMR codegen is rerun

//! Property consume_range_loop_invariant -- non-disabling VCs, part of the independence proof,
//! for every MHIP transition pair (per direction whose firing member is a
//! component): pre-assertions preservation (the firing does not disable another
//! transition -- its pre-assertions still hold) and post-assertions preservation
//! (the firing preserves another transition's established post-assertions).
//! Together with the property-independent Commutativity VCs, these establish
//! that concurrently-enabled transitions do not interfere.
//! Each proof fn has an empty body: Verus discharges `requires ==> ensures`
//! via SMT; add proof hints in the body if a VC does not discharge.

#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_imports)]

use vstd::prelude::*;

use crate::assertions::*;
use crate::consume_range_loop_invariant::assertions::*;
use crate::system_state::SystemState;
use crate::write_frames::*;

verus! {

/** VC[19]: Pre-Assertions Preservation -- INCX firing does not disable DECY (preserves its pre-assertions; MHIP pair t2/t4) */
pub proof fn vc_pre_assertions_preservation_incx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_before_incx(pre),
    sys_assert_consume_range_loop_invariant_before_decy(pre),
    incx_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_before_decy(post),
{}

/** VC[20]: Pre-Assertions Preservation -- DECY firing does not disable INCX (preserves its pre-assertions; MHIP pair t2/t4) */
pub proof fn vc_pre_assertions_preservation_decy_incx(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_before_incx(pre),
    sys_assert_consume_range_loop_invariant_before_decy(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_before_incx(post),
{}

/** VC[21]: Post-Assertions Preservation -- INCX firing preserves DECY's post-assertions (MHIP pair t2/t4) */
pub proof fn vc_post_assertions_preservation_incx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_before_incx(pre),
    sys_assert_consume_range_loop_invariant_after_decy(pre),
    incx_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_after_decy(post),
{}

/** VC[22]: Post-Assertions Preservation -- DECY firing preserves INCX's post-assertions (MHIP pair t2/t4) */
pub proof fn vc_post_assertions_preservation_decy_incx(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_before_decy(pre),
    sys_assert_consume_range_loop_invariant_after_incx(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_after_incx(post),
{}

/** VC[23]: Pre-Assertions Preservation -- CLAMPX firing does not disable DECY (preserves its pre-assertions; MHIP pair t3/t4) */
pub proof fn vc_pre_assertions_preservation_clampx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_after_incx(pre),
    sys_assert_consume_range_loop_invariant_before_decy(pre),
    clampx_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_before_decy(post),
{}

/** VC[24]: Pre-Assertions Preservation -- DECY firing does not disable CLAMPX (preserves its pre-assertions; MHIP pair t3/t4) */
pub proof fn vc_pre_assertions_preservation_decy_clampx(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_after_incx(pre),
    sys_assert_consume_range_loop_invariant_before_decy(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_after_incx(post),
{}

/** VC[25]: Post-Assertions Preservation -- CLAMPX firing preserves DECY's post-assertions (MHIP pair t3/t4) */
pub proof fn vc_post_assertions_preservation_clampx_decy(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_after_incx(pre),
    sys_assert_consume_range_loop_invariant_after_decy(pre),
    clampx_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_after_decy(post),
{}

/** VC[26]: Post-Assertions Preservation -- DECY firing preserves CLAMPX's post-assertions (MHIP pair t3/t4) */
pub proof fn vc_post_assertions_preservation_decy_clampx(pre: SystemState, post: SystemState)
  requires
    sys_assert_consume_range_loop_invariant_before_decy(pre),
    sys_assert_consume_range_loop_invariant_after_clampx(pre),
    decy_global_write_frame(pre, post),
  ensures
    sys_assert_consume_range_loop_invariant_after_clampx(post),
{}

} // verus!
