name: Linux

on: 
   push:
   workflow_dispatch:
   schedule:
     - cron: '0 0 * * 0'  # every Sunday at 12AM

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: sireum/kekinian
          path: kekinian
          submodules: recursive          
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: kekinian/bin/linux/java
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-java          
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: kekinian/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-coursier
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v3
        with:
          path: |
            kekinian/bin/linux/cvc
            kekinian/bin/linux/.cvc.ver
            kekinian/bin/linux/cvc5
            kekinian/bin/linux/.cvc5.ver
            kekinian/bin/linux/z3
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-smt2          
      - name: Cache OSATE
        id: cache-osate
        uses: actions/cache@v3
        with:
          path: kekinian/bin/linux/osate
          key: ${{ runner.os }}-${{ hashFiles('kekinian/hamr/codegen/jvm/src/main/resources/phantom_versions.properties') }}-osate
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE

          # see https://github.com/sireum/osate-plugin/blob/57785407d84793cf1f8d5926647e4dc75ab197a9/org.sireum.aadl.osate.cli/src/org/sireum/aadl/osate/cli/Phantom.java#L508-L517
          export CHECK_PHANTOM_HAMR_API_COMPATIBILITY=true

          git config user.name github-actions
          git config user.email github-actions@github.com

          kekinian/bin/build.cmd setup

          export SIREUM_HOME=$(pwd)/kekinian
          export JAVA_HOME=$SIREUM_HOME/bin/linux/java
          export PATH=$SIREUM_HOME/bin:$JAVA_HOME/bin:$PATH

          # note: workflows have to have read and write permissions if the workflow pushes changes
          #       back to the repo.
          #       Settings >> General >> Actions >> General >> Workflow permissions

          bin/build.cmd



          

