name: Mac

on: 
   workflow_call:

jobs:
  ci:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: sireum/kekinian
          path: kekinian
          submodules: recursive          
      - name: Cache Java
        id: cache-java
        uses: actions/cache@v3
        with:
          path: kekinian/bin/mac/java
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-java          
      - name: Cache Scala
        id: cache-scala
        uses: actions/cache@v3
        with:
          path: kekinian/bin/scala
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-scala
      - name: Cache Coursier
        id: cache-coursier
        uses: actions/cache@v3
        with:
          path: cache/coursier
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-coursier
      - name: Cache SMT2 solvers
        id: cache-smt2
        uses: actions/cache@v3
        with:
          path: |
            kekinian/bin/mac/cvc
            kekinian/bin/mac/.cvc.ver
            kekinian/bin/mac/cvc5
            kekinian/bin/mac/.cvc5.ver
            kekinian/bin/mac/z3
          key: ${{ runner.os }}-${{ hashFiles('kekinian/versions.properties') }}-smt2          
      - name: Cache OSATE
        id: cache-osate
        uses: actions/cache@v3
        with:
          path: kekinian/bin/mac/osate.app
          key: ${{ runner.os }}-${{ hashFiles('kekinian/hamr/codegen/jvm/src/main/resources/phantom_versions.properties') }}-osate
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier
          cd $GITHUB_WORKSPACE

          # see https://github.com/sireum/osate-plugin/blob/57785407d84793cf1f8d5926647e4dc75ab197a9/org.sireum.aadl.osate.cli/src/org/sireum/aadl/osate/cli/Phantom.java#L508-L517
          export CHECK_PHANTOM_HAMR_API_COMPATIBILITY=true

          kekinian/bin/build.cmd setup

          export SIREUM_HOME=$(pwd)/kekinian
          export JAVA_HOME=$SIREUM_HOME/bin/mac/java
          export PATH=$SIREUM_HOME/bin:$JAVA_HOME/bin:$PATH

          bin/build.cmd



          

